#!/usr/bin/env bash

set -euo pipefail

source "$DOTF/framework"
source "$DOTF/scripts/build-helper"

version="$(dotf-trim < "$DOTF/core/vifm/VERSION")"
prepare_build vifm "$version" "$*"

git clone --depth 1 --branch "$version" https://github.com/vifm/vifm

cd vifm

# cleanup the directory before starting (to avoid aclocal-1.15 issue)
autoreconf -f -i
./configure --prefix="$INSTALL_DIR"
make
make install

install_symlinks bin/vifm
install_symlinks bin/vifm-pause
