#!/usr/bin/env bash

source "$DOTF/framework"

version="$(dotf-trim < "$DOTF/core/vifm/VERSION")"

dotf-bullet "Installing vifm..."

if dotf-is-linux; then
  if command_missing vifm; then
    PRIMARY=yes "$DOTF/core/vifm/build" && dotf-success "done."
  else
    current_version="$(vifm --version | head -1 | cut -d: -f2 | dotf-trim)"
    if [ "$current_version" == "$version" ]; then
      dotf-info "version $version already installed."
    else
      dotf-info "found $current_version, upgrading to $version..."
      PRIMARY=yes "$DOTF/core/vifm/build" && dotf-success "done."
    fi
  fi
fi

mkdir -p ~/.vifm/colors
dotf-symlink "$DOTF/core/vifm/vifmrc" "$HOME/.vifm/vifmrc"
dotf-symlink "$DOTF/core/vifm/gruvbox.vifm" "$HOME/.vifm/colors/gruvbox.vifm"
