#!/usr/bin/env bash

source "$DOTF/framework"

if command_missing vifm; then
  PRIMARY=yes "$DOTF/core/vifm/build"
fi

mkdir -p ~/.vifm/colors
symlink "$DOTF/core/vifm/vifmrc" "$HOME/.vifm/vifmrc"
symlink "$DOTF/core/vifm/gruvbox.vifm" "$HOME/.vifm/colors/gruvbox.vifm"
