#!/usr/bin/env bash

source $DOTF/framework
source $DOTF/scripts/build-helper

prepare_build alacritty $VERSION "$*"


cd $INSTALL_DIR
FILENAME=Alacritty-v$VERSION-ubuntu_18_04_amd64.tar.gz

curl -L -O https://github.com/jwilm/alacritty/releases/download/v$VERSION/$FILENAME
tar xzvf $FILENAME

install_symlinks alacritty
install_desktop_entry alacritty Alacritty
