#!/usr/bin/env bash

source $DOTF/framework

export VERSION=0.4.0-rc5

main() {
  if command_missing alacritty; then
    if is_linux; then
      PRIMARY=yes $DOTF/plugins/alacritty/install-binary
    else
      echo "Error: I've only setup alacritty installer for linux"
      exit 1
    fi
  fi

  mkdir -p ~/.config/alacritty
  symlink $DOTF/plugins/alacritty/alacritty.yml ~/.config/alacritty/alacritty.yml
}

main "$@"
