theme = "catppuccin_mocha"

[editor]
line-number = "relative"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
esc = ["keep_primary_selection", "collapse_selection"]

[keys.insert.j]
k = "normal_mode"
l = "normal_mode"

[keys.normal.space]
e = ["move_prev_long_word_start", "move_next_long_word_end", ":pipe-to dotf-open -", "remove_primary_selection"]
w = { w = ":write" } 

[keys.normal.space.l]
g = [":run-shell-command dotf-tmux-popup lazygit"]
