return {}
-- return {
--   "kevinhwang91/nvim-ufo",
--   dependencies = { "kevinhwang91/promise-async" },
--   config = function()
--     local ufo = require("ufo")
--
--     vim.o.foldcolumn = "0"
--     vim.o.foldlevel = 99 -- Using ufo provider need a large value, feel free to decrease the value
--     vim.o.foldlevelstart = 99
--     vim.o.foldenable = true
--
--     -- Using ufo provider need remap `zR` and `zM`. If Neovim is 0.6.1, remap yourself
--     vim.keymap.set("n", "zR", ufo.openAllFolds)
--     vim.keymap.set("n", "zM", ufo.closeAllFolds)
--
--     ufo.setup({})
--     -- ufo.setup({
--     --   provider_selector = function(bufnr, filetype, buftype)
--     --     return { "lsp", "treesitter", "indent" }
--     --   end,
--     -- })
--   end,
-- }
