#!/usr/bin/env bash

set -euo pipefail

source "$DOTF/framework.sh"

if dfl os is-linux; then
  echo "See install-on-linux"
  exit 1
fi

brew install colima docker docker-compose
colima start

# test that docker works
docker run hello-world
