#!/usr/bin/env bash

set -euo pipefail

# Allow non-root runs (https://docs.docker.com/engine/install/linux-postinstall/)

#sudo groupadd docker
sudo usermod -aG docker "$USER"
newgrp docker

docker run hello-world
