#!/usr/bin/env bash

source $(dirname $0)/../../framework.sh

# Install the Arduino command line toolkit (http://inotool.org/)
#pip2_install ino

# Install PlatformIO
python -c "$(curl -fsSL https://raw.githubusercontent.com/ivankravets/platformio/master/scripts/get-platformio.py)"

# Install a dumb-terminal emulator (https://code.google.com/p/picocom/)
dotf-brew picocom
