#!/usr/bin/env bash

set -euo pipefail

source "$DOTF/framework"
source "$DOTF/core/scripts/lib/build-helper.sh"

prepare_build neovim master "$*"

if is_debian; then
  dotf-apt ninja-build gettext libtool libtool-bin autoconf \
    automake cmake g++ pkg-config unzip
elif dotf-is-mac; then
  dotf-brew ninja libtool automake cmake pkg-config gettext
fi

git clone --depth 1 --branch "$VERSION" https://github.com/neovim/neovim.git

cd neovim
make \
  CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX=$INSTALL_DIR" \
  CMAKE_BUILD_TYPE=RelWithDebInfo

make install

install_symlinks bin/nvim
