#!/usr/bin/env bash

set -euo pipefail

source "$DOTF/framework.sh"

mkdir -p ~/.config
dotf-symlink "$DOTF/core/nvim" ~/.config/nvim

nvim --headless "+lua require('elentok.treesitter-parsers')" +qa
