#!/usr/bin/env bash

set -euo pipefail

source "$DOTF/framework.sh"

dfl mkdir ~/.config
dfl symlink "$DOTF/core/nvim" ~/.config/nvim

dfl step start "Installing plugins..."
nvim --headless "+lua vim.pack.update(nil, { target = 'lockfile'})" +qa &&
  dfl step success ||
  dfl step error

dfl step start "Installing treesitter parsers..."
nvim --headless "+lua require('elentok.treesitter-parsers')" +qa &&
  dfl step success ||
  dfl step error

function build-blink-fuzzy() {
  echo
  echo
  dfl step start "Checking blink's fuzzy library..."
  cd ~/.local/share/nvim/lazy/blink.cmp
  if [ ! -e target/release/libblink_cmp_fuzzy.dylib ]; then
    echo "  not found, building..."
    cargo build --release
    dfl step success "Built blink's fuzzy library"
  else
    dfl step skip "already present"
  fi
}

# build-blink-fuzzy
