#!/usr/bin/env bash

set -euo pipefail

source "$DOTF/core/scripts/lib/os.sh"

if dotf-is-linux; then
  dotf-apt luarocks libmagickwand-dev
else
  dotf-brew luarocks
fi

if [ ! -e ~/.luarocks/share/lua/5.1/magick ]; then
  luarocks --local --lua-version=5.1 install magick
fi
