#!/usr/bin/env bash

set -euo pipefail

source "$DOTF/framework"

main() {
  install-symlinks
  install-packer-plugins
  "$DOTF/core/nvim/install-lua"

  (cd "$DOTF/core/nvim/ctags" && ./build)
}

install-symlinks() {
  mkdir -p ~/.config
  symlink "$DOTF/core/nvim" ~/.config/nvim

  symlink "$DOTF/core/nvim/pylintrc" ~/.pylintrc
  mkdir -p ~/.config/yamllint
  symlink "$DOTF/core/nvim/yamllint-config" ~/.config/yamllint/config
}

install-packer-plugins() {
  bullet "Running PackerInstall... "
  nvim-packer-sync
  success "done"
}

main "$@"
