#!/usr/bin/env bash

set -euo pipefail

function main() {
  echo "FILES  LINES  DIR"
  find . -maxdepth 1 -type d | while read -r dir; do
    files="$(count_files "$dir")"
    lines="$(count_loc "$dir")"
    if [ -n "$lines" ]; then
      printf %5d "$files"
      echo -n "  "
      printf %5d "$lines"
      echo "  $dir"
    fi
  done
}

function count_loc() {
  local dir="$1"
  (cloc --not-match-f="packer_compiled.lua" "$dir" | grep "^Lua" || true) | awk '{print $5}'
}

function count_files() {
  local dir="$1"
  find "$dir" -type f -name '*.lua' | grep -cv packer_compiled.lua || true
}

main "$@"
