#!/usr/bin/env bash

set -euo pipefail

config_dir=~/.qutebrowser
if dfl os is-linux; then
  config_dir=~/.config/qutebrowser
fi

mkdir -p $config_dir
dfl symlink "$DOTF/extra/qutebrowser/config.py" $config_dir/config.py
dfl symlink "$DOTF/extra/qutebrowser/catppuccin.py" $config_dir/catppuccin.py
dfl symlink ~/notes/qutemarks $config_dir/bookmarks
