#!/usr/bin/env bash

source $DOTF/framework
source $DOTF/scripts/build-helper

prepare_build tig 2.5.1 "$*"

if is_debian; then
  apt-fast-install libncursesw5-dev build-essential
fi

BASENAME=tig-$VERSION
FILENAME=$BASENAME.tar.gz

curl -O -L https://github.com/jonas/tig/releases/download/$BASENAME/$FILENAME
tar xzvf $FILENAME

cd $BASENAME

./configure
make prefix=$INSTALL_DIR
make install prefix=$INSTALL_DIR

install_symlinks bin/tig
