#!/usr/bin/env bash

source $DOTF/framework

main() {
  if is_arch; then
    pacman_install tig
  elif is_mac; then
    brew_install tig
  elif command_missing tig; then
    $DOTF/plugins/tig/build
  fi

  symlink "$DOTF/plugins/tig/tigrc" ~/.tigrc
}

main "$@"
