#!/usr/bin/env bash

source $DOTF/framework

TIG_VERSION=2.3.2

main() {
  if is_arch; then
    pacman_install tig
  elif is_mac; then
    brew_install tig
  elif command_missing tig; then
    install_tig_targz
  fi

  symlink "$DOTF/plugins/tig/tigrc" ~/.tigrc
}

install_tig_targz() {
  is_debian && apt_install libncursesw5-dev build-essential
  is_fedora && yum_install ncurses-devel

  local filename=tig-$TIG_VERSION.tar.gz

  if [ ! -e $TMP/$filename ]; then
    curl -L https://github.com/jonas/tig/releases/download/tig-$TIG_VERSION/$filename \
      -o $TMP/$filename
  fi

  if [ ! -d $TMP/tig-$TIG_VERSION ]; then
    cd $TMP
    tar xzvf $filename
  fi

  cd $TMP/tig-$TIG_VERSION
  INSTALL_DIR=$HOME/.apps/tig/$TIG_VERSION
  mkdir -p $INSTALL_DIR

  ./configure
  make prefix=$INSTALL_DIR
  make install prefix=$INSTALL_DIR

  symlink $INSTALL_DIR/bin/tig $HOME/bin/tig
}

main "$@"
