#!/usr/bin/env bash

source "$DOTF/framework.sh"

SWAY="$DOTF/extra/sway"

main() {
  dotf-apt sway waybar swaylock swayidle sway-notification-center
  dotf-symlink "$SWAY" "$HOME/.config/sway"

  # install_session_file
}

install_session_file() {
  dotf-bullet "Installing sway-custom.desktop... "
  local tmpfile=/tmp/sway-custom.desktop
  local targetfile=/usr/share/wayland-sessions/sway-custom.desktop

  rm -f $tmpfile
  sed "s#{ROOT}#$SWAY#" $SWAY/sway-custom.desktop > $tmpfile

  if diff $tmpfile $targetfile > /dev/null 2>&1; then
    dotf-info 'already installed'
  else
    sudo mv -f $tmpfile $targetfile
    show_result die_on_error
  fi

  update-desktop-database -q
}

main "$@"
