#!/usr/bin/env bash

SWAY="$DOTF/extra/sway"

main() {
  dfl pkg apt install sway waybar swaylock swayidle sway-notification-center
  dfl symlink "$SWAY" "$HOME/.config/sway"
  dfl symlink "$SWAY/waybar" "$HOME/.config/waybar"

  # install_session_file
}

install_session_file() {
  dfl step start "Installing sway-custom.desktop..."
  local tmpfile=/tmp/sway-custom.desktop
  local targetfile=/usr/share/wayland-sessions/sway-custom.desktop

  rm -f $tmpfile
  sed "s#{ROOT}#$SWAY#" $SWAY/sway-custom.desktop >$tmpfile

  if diff $tmpfile $targetfile >/dev/null 2>&1; then
    dfl step skip 'already installed'
  else
    sudo mv -f $tmpfile $targetfile || exit 1
    dfl step success 'done'
  fi

  update-desktop-database -q
}

main "$@"
