# [font]
# size = 18
#
# [[font.normal]]
# family = "Agave Nerd Font"
# hinting = "normal"

# [font]
# # normal = ["ComicShannsMono Nerd Font Mono"]
# # normal = ["ZedMono NF Light"]
# normal = ["Agave Nerd Font"]
# size = 16

# [font.features]
# "ZedMono NF Light" = ["-calt"]

# [[font.italic]]
# family = "Operator Mono"
# style = "W400"
