#!/usr/bin/env bash

set -euo pipefail

dfl shell "Installing gopls..." -- \
  go install github.com/xieyuschen/gopls-mcp@latest

dfl shell "Installing mcp-go..." -- \
  go install github.com/inja-online/golang-mcp/cmd/mcp-go@latest

dfl shell "Installing GOPLS on Codex..." -- \
  codex mcp add gopls-mcp -- gopls-mcp

dfl shell "Installing GOPLS on Claude..." -- \
  claude mcp add --scope user gopls-mcp -- gopls-mcp
