#!/usr/bin/env bash

set -euo pipefail

dfl shell "Installing GOPLS on Codex..." -- \
  codex mcp add gopls-mcp -- gopls-mcp

dfl shell "Installing GOPLS on Claude..." -- \
  claude mcp add --scope user gopls-mcp -- gopls-mcp
