#!/usr/bin/env zsh

ROOT=$TMP/test-rename

function main() {
  setup
  rename-js 'file' 'newname' **/*
}

function setup() {
  rm -rf $ROOT
  mkdir -p $ROOT
  cd $ROOT

  echo file1 > file1
  echo file2 > file2
  mkdir dir1
  echo dir1/subfile1 > dir1/subfile1
  echo dir1/subfile2 > dir1/subfile2
}

main "$@"
