#!/usr/bin/env bash

set -euo pipefail

LOG=$HOME/.local/share/internet-status.log
SHORT_LOG=$HOME/.local/share/internet-status.short.log
ONLINE_INTERVAL=60
OFFLINE_INTERVAL=20
TRIES=3
STATUS="unknown"

DOMAINS="www.google.com
www.kan.org.il
www.youtube.com
www.cnn.com
www.bbc.com
www.microsoft.com
www.ynet.co.il
www.bing.com
www.yahoo.com
www.twitter.com"

LINE_COUNTER=0
MAX_LINES=10000
LINES_TO_KEEP=100

function main() {
  mkdir -p "$(dirname "$LOG")"
  log ",Monitoring internet connection..."

  while true; do
    test-connection
    if [ "$STATUS" == "up" ]; then
      sleep "$ONLINE_INTERVAL"
    else
      sleep "$OFFLINE_INTERVAL"
    fi
  done
}

function pick-random-domain() {
  echo "$DOMAINS" | shuf -n 1
}

function test-connection() {
  try=0
  failed_domains=()
  while [ $try -lt $TRIES ]; do
    domain="$(pick-random-domain)"
    echo "$(timestamp) Pinging ${domain}"
    if curl --silent -I "https://$domain" | head -1 | grep -E '([23]0[0-9])' > /dev/null; then
      log "ONLINE,$domain"
      if [ "$STATUS" != "up" ]; then
        STATUS="up"
        on-first-online
      fi
      # return 0
    else
      failed_domains+=("$domain")
      try=$((try + 1))
    fi
  done

  log "OFFLINE,${failed_domains[*]}"

  if [ "$STATUS" != "down" ]; then
    STATUS="down"
    on-first-offline
  fi
  # return 1
}

function on-first-online() {
  echo "$(timestamp),ONLINE" >> "$SHORT_LOG"
  notify-internet-restored
}

function on-first-offline() {
  echo "$(timestamp),OFFLINE" >> "$SHORT_LOG"
}

function notify-internet-restored() {
  last_online="$(grep ",ONLINE," "$LOG" | tail -1)"
  curl -d "message=Internet down time from ${last_online} to $(timestamp)" \
    "http://localhost:10000/send"
}

function log() {
  if [ "$LINE_COUNTER" -ge "$MAX_LINES" ]; then
    rotate-log
  fi

  echo "$(timestamp),$*" >> "$LOG"
  LINE_COUNTER=$((LINE_COUNTER+1))
}

function rotate-log() {
  LINE_COUNTER=0
  mv -f "$LOG" "$LOG.old"
  tail -$LINES_TO_KEEP "$LOG.old" > "$LOG"
}

function timestamp() {
  date +%Y-%m-%d\ %H:%M:%S
}

main "$@"
