extends: 'eslint:recommended'

env:
  es6: true
  node: true

rules:
  # Possible Errors
  no-unsafe-negation: error

  # Best Practices
  array-callback-return: error
  complexity: [error, 10]
  consistent-return: error
  dot-location: [error, property]
  dot-notation: error
  eqeqeq: [error, always, { null: ignore }]
  no-console: [error, { allow: [info, warn, error] }]
  no-extend-native: error
  no-extra-bind: error
  no-global-assign: error
  no-implicit-coercion: error
  no-implied-eval: error
  no-lone-blocks: error
  no-loop-func: error
  # no-magic-numbers: [error, { ignore: [0, 1, 2], ignoreArrayIndexes: true }]
  no-multi-spaces: [error,
                    {exceptions: {Property: true,
                                  VariableDeclarator: true,
                                  ImportDeclaration: true}}]
  no-proto: error
  no-throw-literal: error
  no-unmodified-loop-condition: error
  no-unused-expressions: error
  no-useless-call: warn
  no-useless-concat: warn
  no-useless-escape: warn
  radix: error
  yoda: error

  # Variables
  no-use-before-define: [error, nofunc]

  # Stylistic Issues
  array-bracket-spacing: [error, never]
  block-spacing: [error, always]
  brace-style: [error, 1tbs, { allowSingleLine: true }]
  camelcase: [error, { properties: always }]

  comma-spacing: [error, { before: false, after: true }]
  func-call-spacing: [error, never]
  indent: [error, 2, { SwitchCase: 1 }]
  key-spacing: [error, { beforeColon: false, afterColon: true }]
  keyword-spacing: [error, { before: true, after: true }]
  max-depth: [error, { max: 4 }]
  max-len: [error, { code: 100 }]
  max-lines: [error, { max: 200 }]
  max-nested-callbacks: [error, { max: 3 }]
  max-params: [error, { max: 4 }]
  max-statements: [error, { max: 20 }]
  no-multiple-empty-lines: [error, { max: 1 }]
  no-nested-ternary: error
  no-trailing-spaces: error
  no-whitespace-before-property: error
  object-curly-spacing: [error, always]
  padded-blocks: [error, never]
  space-before-blocks: [error, always]
  space-before-function-paren: [error, never]
  space-in-parens: [error, never]
  spaced-comment: [error, always]

  # ECMAScript 6
  no-duplicate-imports: error
  no-useless-computed-key: error
  no-useless-constructor: error
  no-useless-rename: error
  no-var: error
  object-shorthand: error
  prefer-const: [error, { destructuring: all }]
  prefer-rest-params: error
  prefer-spread: error
  template-curly-spacing: [error, never]
  rest-spread-spacing: [error, always]
