#!/bin/bash

source `dirname $0`/config.sh

main() {
  cmd="$1"
  shift
  case "$cmd" in
  "list")
    list-plugins
    ;;
  "install")
    install "$@"
    ;;
  *)
    usage
    ;;
  esac
}

list-plugins() {
  (
    echo vim
    echo zsh
    /bin/ls -1 $DOTF/plugins
  ) | sort
}

install() {
  if [ $# -eq 0 ]; then
    common_plugins
    is_mac && mac_plugins
    is_linux && linux_plugins
  else
    plugins "$@"
  fi
}

common_plugins() {
  plugin nodejs
  plugin git
  plugin zsh
  plugin tmux
  plugin vim
  plugin ruby
  plugin mpd
}

mac_plugins() {
  plugin keyremap4macbook
  plugin homebrew-cask
  brew_install imagemagick
  brew_install ghostscript
}

linux_plugins() {
  apt_install mercurial htop samba libpam-smbpass unrar

  if [ "$HAS_GUI" = 'yes' ]; then
    plugin linux-gui-apps
  fi
}

plugins() {
  while [ $# -gt 0 ]; do
    plugin $1
    shift
  done
}

plugin() {
  local filename="$DOTF/${1}/install.sh"

  if [ ! -x $filename ]; then
    local filename="$DOTF/plugins/${1}.sh"
  fi

  if [ ! -x $filename ]; then
    filename="$DOTF/plugins/$1/install.sh"
  fi

  if [ ! -x $filename ]; then
    error "Cannot find plugin '$1'"
    return
  fi

  $filename
}

usage() {
  echo
  echo "Elentok's dotfiles"
  echo
  echo "Usage:"
  echo
  echo "  dotf list               - lists all plugins"
  echo "  dotf install            - installs all plugin"
  echo "  dotf install [plugin]   - install specific plugins"
}

main "$@"
