#!/usr/bin/env bash

set -euo pipefail

function main() {
  if ! command -v dfl >/dev/null 2>&1; then
    source install-dfl.sh
  fi

  dfl mkdir ~/.config

  install-homebrew

  dfl step start "Installing homebrew package..."
  brew bundle check || brew bundle install
  dfl step success

  remove-temporary-dfl

  install-apt-pkgs

  dfl install fish nvim git ripgrep tig bat bash tmux yazi nodejs python ai

  if dfl os is-mac; then
    dfl symlink ~/Library/Mobile\ Documents/com~apple~CloudDocs ~/iCloud
    dfl install osx-tuning
  fi
}

function install-homebrew() {
  if dfl os is-mac; then
    export PATH="/opt/homebrew/bin:$PATH"
  else
    export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
  fi

  if dfl has-command brew; then
    return
  fi

  # Install curl on Linux
  dfl os is-linux && dfl pkg apt install curl

  # Install homebrew
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
}

function remove-temporary-dfl() {
  # After installing dfl via homebrew remove the one in ~/.local/bin to avoid duplication
  if [ -e ~/.local/bin/dfl ]; then
    dfl pkg step start "Removing temporary dfl binary..."
    rm ~/.local/bin/dfl
    hash -r
    dfl pkg step success
  fi
}

function install-apt-pkgs() {
  if dfl os is-linux; then
    dfl pkg apt install build-essential cmake libreadline-dev cifs-utils curl git htop ncdu plantuml \
      unzip wget qalc ffmpeg pv fish xclip toilet
  fi
}

main "$@"
