#!/usr/bin/env node

const fs = require("fs");

function parse(str) {
  let url;
  try {
    url = new URL(str);
  } catch {
    return new URLSearchParams(str);
  }

  return url.searchParams;
}

function parseQueryString(str) {
  const params = parse(str);

  if (process.argv.length > 2) {
    const key = process.argv[2];
    console.info(params.getAll(key));
  } else {
    console.info(params);
  }
}

parseQueryString(fs.readFileSync(0).toString());
