#!/usr/bin/env bash

function main() {
  set-fish-as-default-shell

  dfl symlink "$DOTF/core/fish" "$HOME/.config/fish"

  # fish "$DOTF/core/fish/install.fish"
}

function set-fish-as-default-shell() {
  dfl step start "Setting fish as the default shell..."

  fish_bin="$(which fish)"
  if dfl os is-mac; then
    my_shell=$(echo "$SHELL" | rev | cut -d/ -f1 | rev)
    if [ "$my_shell" == "fish" ]; then
      dfl step skip "already set"
    else
      edit-etc-shells
      echo "  Changing shell to ${fish_bin}... "
      chsh -s "$fish_bin" && dfl step success || dfl step error
    fi
  else
    echo "  Changing user's shell to $fish_bin... "
    if [[ "$SHELL" =~ /fish ]]; then
      dfl step skip "already set"
    else
      chsh -s "$fish_bin" && dfl step success || dfl step error
    fi
  fi
}

function edit-etc-shells() {
  fish_bin="$(which fish)"
  dfl step start "Adding fish to /etc/shells..."
  if grep -q "$fish_bin" /etc/shells >/dev/null; then
    dotf step skip 'already up to date'
  else
    sudo bash -c "echo '$fish_bin' >> /etc/shells"
    dotf step success "added $fish_bin"
  fi
}

main "$@"
