#!/usr/bin/env bash
#
# Based on instructions at
# https://www.home-assistant.io/installation/linux#install-home-assistant-container

set -euo pipefail

name="homeassistant"
timezone="$(cat /etc/timezone)"
image="ghcr.io/home-assistant/home-assistant:stable"

if [ "${1:-}" == "upgrade" ]; then
  docker stop "$name"
  docker pull "$image"
fi

docker run -d \
  --name "$name" \
  --privileged \
  --restart=unless-stopped \
  -e "TZ=$timezone" \
  -v "$DOTL/config/home-assistant":/config \
  --network=host \
  "$image"
