#!/usr/bin/env bash

set -euo pipefail

function has-version() {
  fnm list | grep " v${1}\\." >/dev/null
}

function node-version() {
  local version_file="$DFL_ROOT/.node-version"

  if [[ ! -f "$version_file" ]]; then
    dfl step error "Missing $version_file"
    exit 1
  fi

  local version
  version="$(<"$version_file")"
  version="${version//$'\n'/}"
  version="${version//$'\r'/}"

  if [[ -z "$version" ]]; then
    dfl step error "$version_file is empty"
    exit 1
  fi

  printf '%s\n' "$version"
}

function main() {
  local node_ver
  node_ver="$(node-version)"

  dfl step start "Installing node..."
  if ! dfl has-command fnm; then
    dfl step error "fnm is missing, it should have been installed with brew"
    exit 1
  fi

  eval "$(fnm env --use-on-cd --shell bash --log-level quiet)"

  if has-version "$node_ver"; then
    dfl step skip "Node $node_ver already installed"
  else
    if ! fnm install "$node_ver"; then
      dfl step error "Failed to install Node $node_ver"
      exit 1
    fi

    dfl step success "Installed Node $node_ver"
  fi

  fnm default "$node_ver" >/dev/null
  fnm use "$node_ver" >/dev/null
  dfl pkg npm install cloc fx json live-server yarn markserv neovim
}

main "$@"
