#!/bin/bash

setxkbmap -option 'grp:alt_shift_toggle' -option 'ctrl:nocaps'
(sleep 3; feh --bg-fill ~/.config/wallpaper.jpg) &
mpd &
gnome-settings-daemon &
nm-applet &
dropbox start &
google-chrome &
x-terminal-emulator &

i3
