#!/usr/bin/env bash

source `dirname $0`/../../framework

set -e

main() {
  if ! is_linux; then
    echo 'Only supported on linux'
    exit 1
  fi

  header "Samba sharing"

  if is_arch; then
    pacman_install samba
    if [ ! -e /etc/samba/smb.conf ]; then
      bullet "Creating /etc/samba/smb.conf (sudo)... "
      sudo cp /etc/samba/smb.conf{.default,}
      show_result die_on_error
    fi
    systemctl enable smb.service
    systemctl enable nmb.service
  else
    apt_install samba
  fi
  init_samba_username
  create_group sambashare
  create_system_user
  create_samba_user
  add_to_smbusers
}

init_samba_username() {
  if [ -z "$samba_username" ]; then
    ask 'Enter the samba username: ' samba_username
    store_variable samba_username "$samba_username"
  fi
}

create_system_user() {
  bullet 'Creating system user... '
  if user_exists $samba_username; then
    info 'already exists.'
    return
  else
    sudo useradd $samba_username -g sambashare && success 'done'
  fi
}

create_samba_user() {
  bullet 'Creating samba user... '
  if smb_user_exists $samba_username; then
    info 'already exists.'
  else
    sudo smbpasswd -a $samba_username && success 'done'
  fi
}

add_to_smbusers() {
  bullet 'Adding user to /etc/samba/smbusers... '
  if is_in_smbusers; then
    info 'already exists.'
  else
    line="$samba_username = $samba_username"
    sudo sh -c "echo '$line' >> /etc/samba/smbusers" & success 'done'
  fi
}

is_in_smbusers() {
  cat /etc/samba/smbusers | grep "^$samba_username\s*=" > /dev/null
}

list_smb_users() {
  sudo pdbedit -L
}

list_smb_usernames() {
  list_smb_users | cut -d: -f1
}

smb_user_exists() {
  list_smb_usernames | grep "^$1$" > /dev/null
}

main "$@"
