#!/usr/bin/env bash

set -euo pipefail

dotf_root="${DOTF:-$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../.." && pwd)}"
project_root="${1:-$(pwd)}"

mkdir -p .ai
cp $dotf_root/.ai/* .ai/

ln -sf .ai/index.md AGENTS.md
ln -sf .ai/index.md CLAUDE.md
