#!/usr/bin/env bash

root="/sys/devices/system/cpu/cpu0/cpufreq"

state="`cat $root/scaling_governor`"

function current_state() {
  echo "Current CPU State: $state"
  echo "Current Frequency: `cat $root/scaling_cur_freq`"
}

if [ "$1" == "" ]; then
  current_state
fi

