#!/usr/bin/env bash

if dfl os is-mac; then
  OS=mac
else
  OS=linux
fi

main() {
  local disk
  disk="$(list-mounts | fzf)"

  if [ -z "$disk" ]; then
    exit 1
  fi

  local device
  device="$(echo "$disk" | awk '{print $2}')"
  local mountpoint
  mountpoint="$(echo "$disk" | awk '{print $1}')"

  if dfl confirm "Eject $device (mounted at $mountpoint)?" yes; then
    dfl step start "Ejecting..."
    "eject-$OS" "$mountpoint"
    dfl step success 'done'
  fi
}

list-mounts() {
  mount | grep -E '/(media|Volumes)' | awk '{print $1,$3}'
}

eject-mac() {
  diskutil eject "$mountpoint"
}

eject-linux() {
  umount "$mountpoint"
}

main "$@"
