#!/usr/bin/env python3

import sys
import requests

message = sys.stdin.read()

if len(sys.argv) > 1 and sys.argv[1] == "--code":
    message = f"```\n{message}\n```"

data = {"message": message}
requests.post("http://localhost:10000/send", data=data)
