#!/usr/bin/env bash

set -e

source "$DOTF/framework"

main() {
  dotf-header h1 'Git Sync'

  commit-if-needed
  pull
  push
  dotf-success 'done'
}

commit-if-needed() {
  dotf-bullet 'Checking for changes... '
  if git-repo-is-dirty; then
    echo
    commit
  else
    dotf-info 'no changes'
  fi
}

commit() {
  dotf-bullet "Commiting changes..."
  echo
  date=$(date +%Y-%m-%d\ %H:%M)
  host=$(short-hostname)
  git add --all
  git commit -m "Update $date ($host)"
  echo
}

pull() {
  dotf-bullet "Pulling changes... "
  git pull --rebase
}

push() {
  dotf-bullet "Pushing changes... "
  git push
}

main "$@"
