#!/usr/bin/env bash

remote='origin'
branch=$(git rev-parse --abbrev-ref HEAD)

read -r -p "Push $branch to $remote? [Y/n] " yesno

echo

if [[ "$yesno" =~ [nN] ]]; then
  echo "Aborted."
else
  echo "Pushing ${branch} to ${remote}..."
  git push $remote "$branch" "$@"
fi
