#!/usr/bin/env bash

remote="noreview"
branch=$(git rev-parse --abbrev-ref HEAD)

read -p "Pull from $remote/$branch? [Y/n] " yesno

echo

if [[ "$yesno" =~ [nN] ]]; then
  echo "Aborted."
else
  echo "Pulling from $remote/${branch}..."
  git pull --rebase $remote $branch
fi

