#!/usr/bin/env bash

source "$DOTF/framework"

if dotf-confirm 'Merge develop into master (ff-only)' yes; then
  set -e
  git checkout master
  git merge --ff-only develop

  if dotf-confirm 'Switch back to develop' yes; then
    git checkout develop
  fi
fi
