#!/usr/bin/env bash

source $DOTF/framework.sh

if dotf-confirm 'Merge master into production (ff-only)' yes; then
  set -e
  git checkout production
  git merge --ff-only master

  if dotf-confirm 'Switch back to master' yes; then
    git checkout master
  fi
fi
