#!/usr/bin/env bash
#
# Usage:
#
#   git nf <branch-name>

set -euo pipefail

if [ $# -eq 0 ]; then
  usage "$0"
  exit 1
fi

cd "$(git-bare-root)"

branch_name="$1"

echo "About to create branch ${branch_name}"
echo "  in ${PWD}"
echo
echo "Press any key to continue..."
read -r -n1

git remote update origin
git worktree add -b "$branch_name" "$branch_name"
cd "$branch_name"
