#!/usr/bin/env bash

set -euo pipefail

current_branch="$(git branch --show-current)"
remote_url="$(git config --get remote.origin.url)"

# shellcheck disable=SC2001
echo "$remote_url" \
  | sed -E "s|git@(.*):(.*)(.git)?|https://\1/\2/tree/${current_branch}|"
