#!/usr/bin/env fish

function find_workspace_id
    herdr workspace list | jq -r ".result.workspaces[] | select (.label==\"$argv[1]\") | .workspace_id"
end

set workspace_id (find_workspace_id $argv[1])

if test -z "$workspace_id"
    echo "Could not find workspace titled '$argv[1]'"
    exit 1
end

herdr workspace focus $workspace_id
