#!/usr/bin/env bash
#
# install-service {service-filename-erb} [user|system]


filename="$1"
mode="$2"
name="$(basename "$filename" | sed -E 's/\.service(\.erb)?$//')"

function main() {
  if [ ! -e "$filename" ]; then
    usage "$0"
    exit 1
  fi

  if [ "$mode" == "user" ]; then
    fill-in-vars "$filename" > "$HOME/.local/share/systemd/user/$name.service"
  elif [ "$mode" == "system" ]; then
    fill-in-vars "$filename" > "/tmp/$name.service"
    sudo mkdir -p /usr/lib/systemd/system
    sudo mv -f "/tmp/$name.service" "/usr/lib/systemd/system/$name.service"
  else
    usage "$0"
    exit 1
  fi
}

function fill-in-vars() {
  if [[ "$filename" =~ .erb$ ]]; then
    erb "$filename"
  else
    MAINPID="\$MAINPID" \
      envsubst < "$filename"
  fi
}

main "$@"
