#!/usr/bin/env bash

ip addr |
  grep -E '(^[0-9]|inet |inet6 )' |
  sed -E $'s/^([0-9]: [^:]*).*/\\033[34m\\1\\033[0m/' |
  sed -E $'s/(inet [^ ]+).*/\\033[32m\\1\\033[0m/' |
  sed -E 's/(inet6 [^ ]+).*/\1/'
