#!/usr/bin/env bash

if [[ "$*" == "" ]]; then
  echo "Usage: israelpost {itemcode}"
else
  url="http://www.israelpost.co.il/itemtrace.nsf/trackandtraceJSON?openagent&_=1372171578320&lang=EN&itemcode=$*"
  curl -s $url | json itemcodeinfo | w3m -T text/html -dump | fribidi
fi
