#!/usr/bin/env bash
#
# Usage:
#
#   jr pick query...
#   jr open query...
#   jr title ticket-or-url      prints a pretty title and copies to clipboard

set -euo pipefail

function main() {
  local cmd="${1:-}"
  shift || true

  if type "jr-${cmd}" >/dev/null 2>&1; then
    "jr-${cmd}" "$@"
  else
    usage "$0"
    exit 1
  fi
}

function jr-pick() {
  jira-search "$@" | tv
}

function jr-info() {
  id="$(jr-pick "$@" | cut -d: -f1)"
  if [ -n "$id" ]; then
    jira view "$id"
  fi
}

function jr-open() {
  id="$(jr-pick "$@" | cut -d: -f1)"
  if [ -n "$id" ]; then
    dotf-open "https://salto-io.atlassian.net/browse/$id"
    jira view "$id"
  fi
}

function jira-search() {
  jira list -q "description ~ \"$*\" OR summary ~ \"$*\""
}

function jr-title() {
  id="$(extract-ticket "${1:-}")"

  summary="$(jira issue view --raw "$id" | fx .fields.summary)"

  pretty="$id: $summary"
  echo "$pretty" | dotf-clipboard copy
  echo "$pretty"
}

function extract-ticket() {
  id="${1:-}"
  if [ -z "${1:-}" ]; then
    id="$(dotf-clipboard paste)"
  fi

  if [[ "$id" == http* ]]; then
    clean_url=$(echo "$id" | cut -d? -f1)
    basename "$clean_url"
  else
    echo "$id"
  fi
}

main "$@"
