#!/usr/bin/env bash
#
# Add .desktop entries to ~/.config/autostart
#
# linux-add-to-startup --name="Music Player Daemon"
#                      --file="mpd"
#                      --exec="mpd"

AUTOSTART="$HOME/.config/autostart"

extract_flag() {
  if [[ "$1" =~ ^-- ]]; then
    local flag_name="${1/--/}"
    local value='yes'

    if [[ "$flag_name" =~ "=" ]]; then
      value="$(echo "$flag_name" | cut -d= -f2)"
      flag_name="$(echo "$flag_name" | cut -d= -f1)"
    fi

    flag_name="${flag_name^^}"

    eval "$flag_name=\"$value\""
    return 0
  fi

  return 1
}

main() {
  FILE=''
  NAME=''
  EXEC=''
  while extract_flag "$1"; do shift; done

  echo "FILE=$FILE"
  echo "NAME=$NAME"
  echo "EXEC=$EXEC"

  if [ -z "$FILE" -o -z "$NAME" -o -z "$EXEC" ]; then
    usage "$0"
    exit 1
  fi

  mkdir -p "$AUTOSTART"

  local filename="$AUTOSTART/${FILE}.desktop"

  dfl step start "Creating ${filename}..."
  if [ -e "$filename" ]; then
    dfl step skip 'already exists'
    exit 0
  fi

  cat >"${filename}" <<EOF
[Desktop Entry]
Encoding=UTF-8
Type=Application
Name=${NAME}
Exec=${EXEC}
StartupNotify=false
Terminal=false
Hidden=false
X-GNOME-Autostart-enabled=false
EOF

  dfl step success 'created'
}

main "$@"
