#!/usr/bin/env bash

source $DOTF/framework

main() {
  # start_mpd
  run_command --sudo 'Nginx' nginx
  echo
  add_ssh_key
}

run_app() {
  dotf-bullet "Starting $1... "
  if is_running "$1"; then
    dotf-info 'already started.'
  else
    open /Applications/$1.app
  fi
}

start_mpd() {
  dotf-bullet 'Starting Music Player Daemon... '
  if is_running mpd; then
    dotf-info 'Already running.'
  else
    echo '(running in background...)'
    mpd &
    sleep 1
    is_running mpd
    show_result
  fi
  echo
}

add_ssh_key() {
  dotf-bullet "Add ssh key... "
  if [ -z "$(ssh-add -l | grep '\.ssh/id_')" ]; then
    ssh-add
  else
    dotf-info 'already added.'
  fi
}

main "$@"
