#!/usr/bin/env fish

if not type -q md2slack-plugin
    function md2slack-plugin
        cat
    end
end

sed 's/  /    /g' \
    | sed -E 's/\[([^]]+)\]\(\.\.[^)]*\)/\1/' \
    | sed -E 's/\[\[.*\|(.*)\]\]/\1/' \
    | md2slack-plugin \
    | sed -E 's/\[ \]( -)?/☐/' \
    | sed -E 's#\[/\]( -)?#:arrow_forward:#' \
    | sed -E 's/\[w\]( -)?/:double_vertical_bar:/' \
    | sed -E 's/\[x\]( -)?/:white_check_mark:/' \
    | sed -E 's/^### (.*)$/        *\1*/' \
    | sed -E 's/^## (.*)$/    *\1*/' \
    | sed -E 's/^# (.*)$/*\1*/' \
    | sed -E 's/\*\*([^\*]+)\*\*/*\1*/g'
