#!/usr/bin/env fish

if not type -q md2slack-plugin
    # @fish-lsp-disable-next-line 4004
    function md2slack-plugin
        cat
    end
end

set codereview "In code review:"
set waiting ":double_vertical_bar:" # :arrow_forward:
set inprogress "◐" # :arrow_forward:
set done "✓" #:white_check_mark: 

dprint fmt --config ~/.dotfiles/extra/scripts/md2slack-dprint.json --stdin file.md \
    | sed 's/  /    /g' \
    | sed -E 's/\[([^]]+)\]\(\.\.[^)]*\)/\1/' \
    | sed -E 's/\[\[.*\|(.*)\]\]/\1/' \
    | md2slack-plugin \
    | sed -E "s#\[/\]( -)?#$inprogress#" \
    | sed -E "s/\[w\]( -)?/$waiting/" \
    | sed -E "s/\[r\]( -)?/$codereview/" \
    | sed -E "s/\[x\]( -)?/$done/"
# | sed -E 's/\[ \]( -)?/☐/' \
# | sed -E 's/^### (.*)$/*\1*/' \
# | sed -E 's/^## (.*)$/```## \1```/' \
# | sed -E 's/^# (.*)$/```# \1```/' \
# | sed -E 's/\*\*([^\*]+)\*\*/*\1*/g'
