#!/usr/bin/env bash

source "$DOTF/framework"

dotf-header h1 'Good morning :-)'

dotf-header h2 'Setting up ssh agent...'
agent setup

dotf-header h2 'Add ssh key...'
ssh-add

if [ -e "$DOTL/scripts/morning-local" ]; then
  "$DOTL/scripts/morning-local"
fi

if [ -e ~/.dotlocal ]; then
  dotf-header h2 'Updating dotlocal...'
  cd ~/.dotlocal && git pull
fi

if [ -e ~/.dotprivate ]; then
  dotf-header h2 'Updating dotprivate...'
  cd ~/.dotprivate && git pull
fi

dotf-header h2 'Updating dotfiles...'
dotf update

note_dirs=(~/notes ~/notes/home ~/notes/work)

for dir in "${note_dirs[@]}"; do
  if [ -e "$dir/.git" ]; then
    dotf-header h2 "Syncing ${dir}..."
    (cd "$dir" && git sync)
  fi
done

dotf-header h1 'Have a wonderful day :-)'
