#!/usr/bin/env bash

source $DOTF/framework.sh

main() {
  netinfo
}

netinfo() {
  devices | while read device; do
    echo "$device:"
    echo "  ip:  $(device-ip $device)"
    echo "  mac: $(cat /sys/class/net/$device/address)"
    echo
  done
}

devices() {
  /bin/ls -1 /sys/class/net
}

device-ip() {
  ip addr show "$1" | grep 'inet ' | awk '{print $2}'
}

main "$@"
