#!/usr/bin/env bash
#
# PulseAudio helper script
#
# Usage:
#
#   pa (command)
#
# Commands:
#
#   pa ls             list sinks
#

source $DOTF/framework

main() {
  local cmd="$1"
  shift

  if has_command "cmd-$cmd"; then
    cmd-$cmd "$@"
  else
    usage "$0"
  fi
}

rcolor() {
  printf "$RESET"
}

green() {
  printf "$GREEN"
}

red() {
  printf "$RED"
}

cmd-ls() {
  pacmd list-sinks | cleanup
}

cmd-outputs() {
  pacmd list-source-outputs | cleanup
}

cleanup() {
  grep -E '(index:|name:|source:|state:|muted:|hdmi-output|alsa.card_name|application.name)' | \
  sed -e 's/^\s*//' | \
  sed -re "s/^\*\s*(.*)$/\1 << $(red)ACTIVE$(rcolor)/" | \
  sed -re 's/^index:/\n&/' | \
  sed -re 's/ = /: /' | \
  sed -re "s/^([^:]+:)/$(green)\1$(rcolor)/"
}

main "$@"
