#!/usr/bin/env bash

set -euo pipefail

CACHE_FILE=~/.local/cache/nerdfont.txt

function main {
  list-icons | fzf | awk '{print $1}'
}

function list-icons {
  if [ -e "$CACHE_FILE" ]; then
    cat "$CACHE_FILE"
  fi

  curl -s 'https://raw.githubusercontent.com/ryanoasis/nerd-fonts/refs/heads/master/glyphnames.json' |
    jq 'to_entries | map([.key, .value.char]) | del(.[0]) | .[] | reverse | join("  ")' |
    tr -d '"' >|"$CACHE_FILE"

  cat "$CACHE_FILE"
}

main "$@"
