#!/usr/bin/env fish

function main
    set action $argv[1]
    if test -z "$action"
        set action (echo -e "work\nrest" | tv --inline)
    end

    if test -z "$action"
        echo "User aborted."
        exit 1
    end

    if test "$action" = work
        work $argv[2]
    else if test "$action" = rest
        rest $argv[2]
    else
        echo "Usage: pomo <work|rest>"
    end
end

function work
    set length 24m
    if test -n "$argv[1]"
        set length $argv[1]
    end
    say "pomodoro session started" &&
        countdown $length &&
        say "one minute remaining" &&
        countdown -say 1m &&
        say "take a break"
end

function rest
    set length 5m
    if test -n "$argv[1]"
        set length $argv[1]
    end
    say rest &&
        countdown $length &&
        say "get back to work"
end

main $argv
