#!/usr/bin/env bash

set -euo pipefail

last_pkg=""

function identify-pkg() {
  local line="$1"
  pkg="$(echo "$line" | awk '{print $1}')"
  pkg="${pkg/\"/}"
  pkg="${pkg/\"/}"
  pkg="${pkg/\:/}"
  echo "$pkg"
}

function filter() {
  if [ -e ~/resolve-exclude.txt ]; then
    pattern="$(cat ~/resolve-exclude.txt)"
    grep -v "${pattern}"
  else
    cat
  fi
}

IFS=''
grep -vE '^(<<<|>>>|===)' | filter | sort -r -n | while read -r line; do
  pkg="$(identify-pkg "$line")"

  if [ "$pkg" != "$last_pkg" ]; then
    echo "$line"
    last_pkg="$pkg"
  fi
done | sort
