#!/usr/bin/env bash

MAX_LENGTH=15

hostname=$(hostname | sed -E 's/\.local(domain)?//')

# remove dashes and underscores
if [[ ${#hostname} -gt $MAX_LENGTH ]]; then
  hostname=${hostname//[-_]/}
fi

# remove i, a and u
if [[ ${#hostname} -gt $MAX_LENGTH ]]; then
  hostname=${hostname//[iau]/}
fi

if [[ ${#hostname} -gt $MAX_LENGTH ]]; then
  hostname=$(echo "$hostname" | cut -c 1-15)
fi

echo "$hostname"
