#!/usr/bin/env bash

verify-perms() {
  local expected="$1"
  local file="$2"

  printf "* Verifying '%s' has permissions '%s'... " "$file" "$expected"
  if [ ! -e "$file" ]; then
    echo 'skipping, file is missing'
    return
  fi

  local actual
  actual="$(stat --format=%a "$file")"
  if [ "$actual" == "$expected" ]; then
    echo 'ok'
  else
    chmod "$expected" "$file"
    echo 'fixed'
  fi
}

cd || exit
verify-perms 700 .ssh
verify-perms 600 .ssh/config
verify-perms 600 .ssh/authorized_keys
verify-perms 600 .ssh/id_rsa
verify-perms 600 .ssh/id_rsa.pub
verify-perms 600 .ssh/id_dsa
verify-perms 600 .ssh/id_dsa.pub
