#!/usr/bin/env bash

set -euo pipefail

function main() {
  name="$1"

  if [ ! -e "$name" ]; then
    name="$(toggle-visible "$name")"
  fi

  if [ ! -e "$name" ]; then
    echo "Could not find either '${1}' or '${name}'"
    exit 1
  fi

  new_name="$(toggle-visible "$name")"

  echo "Renaming '${name}' to '${new_name}'"
  mv "${name}" "${new_name}"
}

function is-hidden() {
  [[ "$1" =~ ^\. ]]
}

function toggle-visible() {
  local name="$1"
  if is-hidden "$name"; then
    echo "${name/\./}"
  else
    echo ".${name}"
  fi
}


main "$@"
