#!/usr/bin/env bash

source "$DOTF/framework"

function main() {
  dotf-header h1 'Updating stuff...'
  update-node
  dotf-github update
  dotf-pkgs upgrade
  update-neovim-stuff
}

function update-node() {
  if is-n-providing-node; then
    dotf-header h2 'Updating N...'
    (cd "$N_PREFIX" && git pull)

    dotf-header h2 'Updating NodeJS...'
    n --preserve lts # Preserve npm (don't downgrade to lts version)
  fi
}

function update-neovim-stuff() {
  dotf-header h2 'Neovim: Upgrade'
  dotf-github u nvim
  nvim-packer-sync
}

main "$@"
