#!/usr/bin/env bash
#
# Displays a usage message from the first comment block in the given file
#
# Usage:
#
#    usage <filename>

if [ $# -eq 0 ]; then
  usage "$0"
else
  while read -r line; do
    if [[ "$line" =~ ^# ]]; then
      echo "$line"
    else
      break
    fi
  done < "$1"
fi
