#!/usr/bin/env bash

set -euo pipefail

CACHE_DIR="$HOME/.local/cache/web-diff"
LINKS_FILE="$HOME/.config/web-diff.csv"
NEW_DIR="$TMP/web-diff"

function main() {
  if [ ! -e "$LINKS_FILE" ]; then
    echo "Error: No config file in $LINKS_FILE"
    exit 1
  fi

  mkdir -p "$CACHE_DIR"
  touch changes-log

  while true; do
    check-links
    sleep 60
  done
}

function check-links() {
  rm -rf "$NEW_DIR"
  mkdir -p "$NEW_DIR"

  while read -r line; do
    id="${line//,*/}"
    url="${line//*,/}"

    check-link "$id" "$url"

  done < "$LINKS_FILE"
}

function check-link() {
  local id="$1"
  local url="$2"

  local new_file="$NEW_DIR/${id}.html"
  local cached_file="$CACHE_DIR/${id}.html"

  echo "- ${id} (${url})..."
  curl --silent -L "${url}" -o "$new_file"

  if [ ! -e "$cached_file" ]; then
    echo "  not in cache yet."
    mv "$new_file" "$cached_file"
    return
  fi

  if diff "$cached_file" "$new_file" > /dev/null; then
    echo "  CHANGED!"
    mv -f "$new_file" "$cached_file"
    echo "$(timestamp) URL ${id} has changed" >> changes.log
    curl -d "message=URL ${id} has changed - ${url}" \
      "http://localhost:10000/send"
  else
    echo "  no change."
  fi
}

function timestamp() {
  date +%Y-%m-%d\ %H:%M:%S
}

main "$@"
