#!/usr/bin/env fish

function main
    if test -n "$TMUX"
        tmux-wezimg $argv
    else
        regular-wezimg $argv
    end
end

function tmux-wezimg
    set tab_width (tmux display -p '#{window_width}')
    set tab_height (tmux display -p '#{window_height}')

    set pane_width (tput cols)
    set pane_height (tput lines)

    clear
    # Check the orientation
    if test $pane_width -gt (math "$pane_height * 2")
        # Landscape
        set height (math "round ($pane_height / $tab_height * 90)")
        wezterm imgcat --height "$height%" --hold --no-move-cursor $argv
    else
        # Portrait
        set width (math "round ($pane_width / $tab_width * 90)")
        wezterm imgcat --width "$width%" --hold --no-move-cursor $argv
    end
    clear
end

function regular-wezimg
    set terminal_width (tput cols)
    set terminal_height (tput lines)

    echo width $terminal_width
    echo height $terminal_height

    # Check the orientation
    if test $terminal_width -gt (math "$terminal_height * 2")
        # Landscape
        wezterm imgcat --height 90% --hold $argv
    else
        # Portrait
        wezterm imgcat --width 90% --hold $argv
    end
end

main $argv
