#!/usr/bin/env bash
#
# Usage: worksesh <minutes>

set -euo pipefail

DATA_DIR=~/.local/share/worksesh
LOG_FILE="$DATA_DIR/sessions.log"
STATE_FILE="$DATA_DIR/state.txt"
mkdir -p "$DATA_DIR"

trap handle_ctrl_c INT

source "$DOTF/core/scripts/lib/os.sh"

function main() {
  if [ $# -eq 0 ]; then
    usage "$0"
    exit 1
  fi

  if [ "$1" == "?" ]; then
    if [ -e "$STATE_FILE" ]; then
      cat "$STATE_FILE"
    else
      echo "not running"
    fi
    exit
  fi

  local minutes="$1"
  local remaining=$minutes

  while [ "$remaining" -gt 0 ]; do
    echo "$remaining" > $STATE_FILE
    if [ "$remaining" -lt 3 ]; then
      notify "${remaining} minutes remaining"
    else
      echo "${remaining} minutes remaining"
    fi

    sleep 60
    remaining=$((remaining - 1))
  done

  echo "done" > $STATE_FILE

  write-to-log "complete: ${minutes}m session"

  lock
}

function notify() {
  echo "$@"
  dotf-notify "$@"
  if dotf-is-mac; then
    say "$@"
  fi
}

function lock() {
  notify "Locking in 5 seconds"
  sleep 5

  if dotf-is-mac; then
    pmset displaysleepnow
  else
    loginctl lock-session
  fi
}

function handle_ctrl_c() {
  echo "Work session aborted by user"
  write-to-log "aborted: ${minutes}m session (${remaining} remaining)"
  exit 1
}

function write-to-log() {
  echo "$(date '+%Y-%m-%d %H:%M') $*" >> "$LOG_FILE"
}

main "$@"
