#!/usr/bin/env bash

set -euo pipefail

source "$DOTF/framework.sh"

WIN_USERNAME="$(wsl-get-env USERNAME)"
WIN_HOME="/mnt/c/Users/$WIN_USERNAME"

echo "Username: $WIN_USERNAME"
dotf-symlink "$WIN_HOME" ~/winhome
dotf-symlink "$WIN_HOME/Documents" ~/Documents
dotf-symlink "$WIN_HOME/Downloads" ~/Downloads
