#!/usr/bin/env bash

set -euo pipefail

EXTERNAL="DP-2-2"
INTERNAL="eDP-1"
EXTERNAL_POSITION="left"

function main() {
  case "${1:-}" in
    l | 1 | "laptop")
      external-off
      restart-compton
      setup-wallpaper
      ;;
    m | 2 | "multi")
      external-off
      external-on
      restart-compton
      setup-wallpaper
      ;;
    *)
      echo "Usage: xdisp <laptop|multi>"
      ;;
  esac
}

function external-off() {
  xrandr --output "$EXTERNAL" --off
}

function external-on() {
  xrandr --output "$EXTERNAL" --primary --auto --$EXTERNAL_POSITION-of "$INTERNAL"
}

function restart-compton() {
  killall compton || true
  compton &
}

function setup-wallpaper() {
  if [ -e ~/.config/wallpaper.jpg ]; then
    feh --bg-fill ~/.config/wallpaper.jpg
  fi
}

main "$@"
