#!/usr/bin/env bash

MONITOR='DP-1'
WIDTH=1920
HEIGHT=1200
REFRESH=50.0Hz

modeline="$(cvt $WIDTH $HEIGHT $REFRESH | grep '^Modeline' | sed 's/^Modeline //' | sed 's/"//g')"
mode=$(echo $modeline | awk '{print $1}')

echo "Modeline:"
echo
echo "  $modeline"
echo

xrandr --newmode $modeline
xrandr --addmode $MONITOR $mode


# Remove mode:
# xrandr --output $MONITOR --mode 1024x768
# xrandr --delmode $MONITOR $mode
# xrandr --rmmode $mode
