#!/usr/bin/env bash

source "$DOTF/framework"

main() {
  if dotf-is-mac; then
    brew_install mc
  else
    dotf-apt mc
  fi

  make_dir ~/.config/mc
  symlink "$DOTF/plugin/mc/ini" ~/.config/mc/ini
}

main "$@"
