#!/usr/bin/env bash

source "$DOTF/framework.sh"

main() {
  if dotf-is-mac; then
    dotf-brew mc
  else
    dotf-apt mc
  fi

  make_dir ~/.config/mc
  dotf-symlink "$DOTF/plugin/mc/ini" ~/.config/mc/ini
}

main "$@"
