#!/usr/bin/env bash

source "$DOTF/framework"

main() {
  if is_mac; then
    brew_install mc
  else
    apt-fast-install mc
  fi

  make_dir ~/.config/mc
  symlink "$DOTF/plugin/mc/ini" ~/.config/mc/ini
}

main "$@"
