#!/usr/bin/env bash

(
  echo "======================================"

  source $HOME/.dotfiles/zsh/core.sh

  # Setup X11 keyboard
  xkeyboard
  xmouse

  light-locker --lock-on-suspend --no-late-locking &
  xfce4-clipman &
  # xfce4-session &

  # Network Management Applet
  dotf-has-command nm-applet && nm-applet &

  if dotf-has-command google-chrome-stable; then
    google-chrome-stable &
  elif dotf-has-command google-chrome; then
    google-chrome &
  fi

  if dotf-has-command x-terminal-emulator; then
    x-terminal-emulator &
  elif dotf-has-command i3-sensible-terminal; then
    i3-sensible-terminal &
  fi

  xrdb ~/.Xresources

  if [ -e $DOTL/i3-session ]; then
    source $DOTL/i3-session
  fi

  i3

) >> ~/.i3/log 2>&1
