#!/usr/bin/env bash

source `dirname $0`/../../framework

main() {
  header "SSH"
  install_symlinks
}

install_symlinks() {
  symlink "$DOTF/plugins/ssh/rc" ~/.ssh/rc
  symlink "$DOTF/plugins/ssh/config" ~/.ssh/config
}

main "$@"

