#!/bin/bash

source `dirname $0`/../config.sh

main() {
  header "Hydra Window Manager"

  brew_cask_install hydra

  install_symlinks
}

install_symlinks() {
  symlink "$DOTF/hydra" ~/.hydra
}

main $*
