#!/usr/bin/env bash

source $DOTF/framework
source $DOTF/scripts/build-helper

VERSION=v3.0.1

export PRIMARY=yes

prepare_build shfmt $VERSION "$*"

ARCH=linux_amd64
if is_mac; then ARCH=darwin_amd64; fi

cd $INSTALL_DIR
FILENAME=shfmt_${VERSION}_${ARCH}
echo https://github.com/mvdan/sh/releases/download/$VERSION/$FILENAME
curl -L -O https://github.com/mvdan/sh/releases/download/$VERSION/$FILENAME
chmod +x $FILENAME

install_symlinks $FILENAME shfmt
