#!/usr/bin/env bash

version="$(sed -E 's/(^\s+|\s+$)//g' <"$DOTF/extra/vifm/VERSION")"

mkdir -p ~/.vifm/colors
dfl symlink "$DOTF/extra/vifm/vifmrc" "$HOME/.vifm/vifmrc"
dfl symlink "$DOTF/extra/vifm/gruvbox.vifm" "$HOME/.vifm/colors/gruvbox.vifm"
