#!/usr/bin/env bash

source $DOTF/framework

ROOT=$DOTF/extra/vscode

if dotf-is-wsl; then
  dotf-symlink \
    $(wslpath $(wsl-get-env USERPROFILE))/AppData/Roaming/Code \
    $HOME/.config/Code
fi

npx vscode:sync
