#!/bin/bash

source `dirname $0`/../../framework

header "NodeJS"

if is_arch; then
  pacman_install nodejs npm
else
  brew_install node
fi

npm_install coffee-script
npm_install bower
npm_install json
npm_install jsontool
npm_install live-server
npm_install jade
npm_install jstransformer-coffee-script
npm_install jstransformer-less

npm_install tailr
