#!/usr/bin/env bash

set -euo pipefail

source `dirname $0`/../../framework

main() {
  header 'NodeJS'

  if is_arch; then
    pacman_install nodejs npm yarn
  else
    git_clone https://github.com/tj/n $N_PREFIX
  fi

  install_packages
}

install_packages() {
  npm_install yarn
  npm_install coffeescript
  npm_install json
  npm_install live-server
  npm_install tern
  npm_install eslint
  npm_install typescript
  npm_install tslint
}

main "$@"
