#!/usr/bin/env bash

set -euo pipefail

source `dirname $0`/../../framework

main() {
  header 'NodeJS'

  git_clone https://github.com/tj/n $N_PREFIX
  install_node

  install_packages
}

install_node() {
  if [[ ! "$(n ls)" =~ 'ο' ]]; then
    n latest
  fi
}

install_packages() {
  npm_install yarn
  npm_install coffeescript
  npm_install json
  npm_install live-server
  npm_install tern
  npm_install eslint
  npm_install typescript
  npm_install tslint
}

main "$@"
