#!/usr/bin/env bash

set -euo pipefail

source "$DOTF/framework.sh"

if [ ! -d /Applications/Phoenix.app ]; then
  brew install --cask phoenix
fi

dotf-symlink "$DOTF/extra/phoenix/phoenix.js" ~/.phoenix.js
