#!/bin/bash

source `dirname $0`/../framework

main() {
  header "(Neo)Vim"

  install_neovim
  install_symlinks
  install_plugins
  install_cli_tools

  (cd $DOTF/vim && ./ctags-build)
}

install_requirements() {
  if is_mac; then
    # python3 is required for the deoplete plugin
    brew_install python3 abduco
  elif is_arch; then
    pacman_install python-pip python2-pip abduco
  elif is_debian; then
    apt_install python-dev python-pip python3-dev python3-pip
  fi

  pip3_install neovim
  pip_install neovim
}

install_neovim() {
  if is_arch; then
    pacman_install neovim
  else
    brew_tap neovim/homebrew-neovim
    brew_install neovim
  fi
}

install_symlinks() {
  symlink "$DOTF/vim" ~/.config/nvim

  symlink "$DOTF/vim/pylintrc" ~/.pylintrc

  # vim backwards compatibility
  symlink "$DOTF/vim/init.vim" ~/.vimrc
  symlink "$DOTF/vim" ~/.vim
}

install_plugins() {
  bullet "Running PlugInstall... "
  nvim +PlugInstall +qall
  success "done"
}

install_cli_tools() {
  if is_arch; then
    pacman_install ctags tidy
  else
    brew_install ctags
    brew_install the_silver_searcher # ag
    brew_install global --with-pygments
  fi

  npm_install vimspec
  npm_install marked
  npm_install name-that-color
  npm_install livedown
  npm_install coffeelint
  npm_install eslint
  npm_install prettier
  npm_install jsonlint
  npm_install sass-lint
  pip_install pylint
  pip_install yamllint
}

main $@
