" vim: foldmethod=marker

if $SHELL =~ 'fish'
  set shell=/bin/sh
endif

let mapleader = ","

let $root=expand("<sfile>:p:h")

" OS-Specific {{{1

function! IdentifyOS()
  if system('uname -s') == "Darwin\n"
    return 'mac'
  elseif has('gui_win32')
    return 'windows'
  else
    return 'linux'
  end
endfunc

function! GetPythonVersion()
  if !exists('g:python_version')
    python <<endpython
import sys
import vim
version = sys.version.split(' ')[0].replace('.', '')
vim.command("let g:python_version=%s" % version)
endpython
  end
  return g:python_version

endfunc

let g:os = IdentifyOS()

if g:os == 'windows'
  let $temp_dir=$TEMP . '\\vim'
  let $vimrc=$VIMRUNTIME . '/../.vimrc'
  let $vimfiles=$VIMRUNTIME . '/../vimfiles'
  let $delimiter='\\'
  let $defaultfont="Consolas:h12:cANSI"
  let $alternatefont="Courier_New:h12:cHEBREW"
  let g:ruby_path='C:/ruby187'
  set grepprg="findstr /nI"
  let g:Powerline_symbols='compatible'
  let $opener='start'
else
  let $temp_dir='/tmp/vim-' . $USER
  let $vimrc=expand('~/.vimrc')
  let $vimfiles=expand('~/.vim')
  let $delimiter = '/'
  let $defaultfont='Monaco\ for\ Powerline:h13'
  let $alternatefont='Ubuntu\ Mono\ 13'
  let g:Powerline_symbols='fancy'

  if g:os == 'mac'
    " the 'wildignorecase' option is not available for windows
    set wildignorecase
  end
  
  if file_readable('/usr/local/bin/ctags')
    let g:ctags='/usr/local/bin/ctags'
  else
    let g:ctags='ctags'
  end

  let $opener='open'
  if g:os == 'linux'
    let $opener='/usr/bin/xdg-open'
  end

endif

exec "set guifont=" . $defaultfont

if getftype($temp_dir) != 'dir'
  exec 'silent !mkdir ' . $temp_dir
endif

" }}}1

if file_readable(expand("~/.dotlocal/before.vim"))
  source ~/.dotlocal/before.vim
endif

source $vimfiles/vundles.vim
source $vimfiles/settings.vim
source $vimfiles/functions.vim
source $vimfiles/keys.vim
source $vimfiles/autocmds.vim

if file_readable(expand("~/.dotlocal/after.vim"))
  source ~/.dotlocal/after.vim
endif
