#!/usr/bin/env bash

set -euo pipefail

source "$DOTF/framework"

VERSION=3.4.1

main() {
  if dotf-is-mac; then
    brew_install ffmpeg
  elif dotf-command-missing ffmpeg; then
    install_ffmpeg_binaries
  fi
}

install_ffmpeg_binaries() {
  local filename="ffmpeg-$VERSION-64bit-static.tar.xz"
  url="https://johnvansickle.com/ffmpeg/releases/$filename"

  curl -L "$url" -o "$TMP/$filename"

  install_dir=$HOME/.apps/ffmpeg/$VERSION
  mkdir -p "$install_dir"
  cd "$install_dir"

  tar --strip-components=1 -xf "$TMP/$filename"
  dotf-symlink "$install_dir/ffmpeg" "$HOME/bin/ffmpeg"
}

main "$@"
