#!/usr/bin/env bash

source $DOTF/framework.sh
source $DOTF/core/scripts/lib/build-helper.sh

MAC_VERSION=2.2.2.1

main() {
  if dotf-has-command pandoc; then return; fi

  if dotf-is-mac; then
    PRIMARY=yes install_on_mac
  else
    dotf-apt pandoc
  fi
}

install_on_mac() {
  prepare_build pandoc $MAC_VERSION "$*"

  url="https://github.com/jgm/pandoc/releases/download/$VERSION/pandoc-$VERSION-macOS.zip"
  curl -L "$url" -o $BUILD_DIR/pandoc.zip

  cd $INSTALL_DIR
  unzip $BUILD_DIR/pandoc.zip

  install_symlinks pandoc-$VERSION/bin/pandoc
}

main
