#!/usr/bin/env bash

function main() {
  install-rust

  if ! dfl has-command cargo-binstall; then
    cargo install cargo-binstall
  fi

  # Install rust sources (required by the LSP)
  # Based on https://rust-analyzer.github.io/manual.html#installation
  rustup component add rust-src
}

function install-rust() {
  dfl step start 'Installing rust...'
  if dfl has-command rustc; then
    dfl step skip 'already installed.'
  else
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -o /tmp/rustup-init
    sh /tmp/rustup-init --no-modify-path -y
  fi
}

main "$@"
