#!/usr/bin/env bash

source "$DOTF/framework.sh"

function main() {
  dotf-symlink "$DOTF/core/ripgrep/rgignore" "$HOME/.rgignore"
  # install-zsh-completion
}

function install-zsh-completion() {
  dotf-bullet "Installing ZSH Completion..."

  dir="$HOME/.zsh-complete"
  mkdir -p "$dir"
  rg --generate complete-zsh > "$dir/_rg"

  # Reset zsh completion cache
  rm ~/.zcompdump

  dotf-success "done"
}

main "$@"
