# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.

source "$DOTF/core/zsh/p10k-instant-prompt.zsh"

# Start fish shell on interactive shells
if [ -e ~/.try-fish ]; then
  if [[ $- = *i* ]]; then
    if [ -z "$WHICH_FISH" ]; then
      export WHICH_FISH="$(which fish)"
    fi
    exec "$WHICH_FISH" -i
    return
  fi
fi

typeset -F SECONDS=0
export START_TIME=$SECONDS

if [ -e ~/.profiling ]; then
  source $DOTF/core/zsh/profiling.zsh
fi

source $DOTF/core/zsh/core.sh
source_if_exists ~/.dotlocal/zsh/before.zsh
source $DOTF/core/zsh/zsh.zsh
source $DOTF/core/zsh/settings.sh
source $DOTF/core/zsh/dircolors/dircolors.sh
source $DOTF/core/zsh/widgets.zsh
source $DOTF/core/zsh/aliases.sh
source $DOTF/core/zsh/completion.zsh
source $DOTF/core/zsh/keybindings.zsh
source $DOTF/core/zsh/fzf-git.sh
source $DOTF/core/zsh/vendor/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ~/.powerlevel10k/powerlevel10k.zsh-theme
# source $DOTF/core/zsh/prompt.zsh
if is-nvm-providing-node; then
  source $DOTF/core/zsh/nvm.zsh
fi
if [ -e ~/.fzf.zsh ]; then
  source ~/.fzf.zsh
fi
source_if_exists ~/.dotlocal/zsh/after.zsh
source_if_exists ~/.dotprivate/zsh/after.zsh

# required so ~/.zshenv will be loaded by sub-processes
unset ZSHENV_LOADED

# duration=$((($SECONDS - $START_TIME) * 1000))
# echo "\033[1;30m($(printf '%.2f' $duration)ms)\033[0m"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
