# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.

# Start fish shell on interactive shells
if [ -e ~/.try-fish ]; then
  if [[ $- = *i* ]]; then
    if [ -z "$WHICH_FISH" ]; then
      export WHICH_FISH="$(which fish)"
    fi
    exec "$WHICH_FISH" -i
    return
  fi
fi

typeset -F SECONDS=0
export START_TIME=$SECONDS

if [ -e ~/.profiling ]; then
  source $DOTF/core/zsh/profiling.zsh
fi

source $DOTF/core/zsh/core.sh
for script in $(dotf-plugin-list-files zsh/before.zsh); do
  source "$script"
done
source $DOTF/core/zsh/zsh.zsh
source $DOTF/core/zsh/settings.sh
source $DOTF/core/zsh/dircolors/dircolors.sh
source $DOTF/core/zsh/widgets.zsh
source $DOTF/core/zsh/aliases.sh
source $DOTF/core/zsh/completion.zsh
source $DOTF/core/zsh/keybindings.zsh
source $DOTF/core/zsh/fzf-git.sh
source $DOTF/core/zsh/vendor/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source $DOTF/core/deno/shell-helpers.sh
if ! dotf-has-command starship; then
  source $DOTF/core/zsh/prompt.zsh
fi
if [ -e ~/.fzf.zsh ]; then
  source ~/.fzf.zsh
fi
for script in $(dotf-plugin-list-files zsh/after.zsh); do
  source "$script"
done

# required so ~/.zshenv will be loaded by sub-processes
unset ZSHENV_LOADED

eval "$(starship init zsh)"

duration=$((($SECONDS - $START_TIME) * 1000))
echo -e "\x1b[38;5;241m $(printf '%.2f' $duration)ms\033[0m"
