# Start fish shell on interactive shells
if [ -e ~/.try-fish ]; then
  if [[ $- = *i* ]]; then
    if [ -z "$WHICH_FISH" ]; then
      export WHICH_FISH="$(which fish)"
    fi
    exec "$WHICH_FISH" -i
    return
  fi
fi

typeset -F SECONDS=0
export START_TIME=$SECONDS

if [ -e ~/.profiling ]; then
  source $DOTF/core/zsh/profiling.zsh
fi

source $DOTF/core/zsh/core.sh
source_if_exists ~/.dotlocal/zsh/before.zsh
source $DOTF/core/zsh/zsh.zsh
source $DOTF/core/zsh/settings.sh
source $DOTF/core/zsh/dircolors/dircolors.sh
source $DOTF/core/zsh/widgets.zsh
source $DOTF/core/zsh/aliases.sh
source $DOTF/core/zsh/completion.zsh
source $DOTF/core/zsh/keybindings.zsh
source $DOTF/core/zsh/fzf-git.sh	
source $DOTF/core/zsh/vendor/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source $DOTF/core/zsh/prompt.zsh
if [ -e ~/.fzf.zsh ]; then
  source ~/.fzf.zsh
fi
source_if_exists ~/.dotlocal/zsh/after.zsh
source_if_exists ~/.dotprivate/zsh/after.zsh

# required so ~/.zshenv will be loaded by sub-processes
unset ZSHENV_LOADED

duration=$((($SECONDS - $START_TIME) * 1000))
echo "\033[1;30m($(printf '%.2f' $duration)ms)\033[0m"
