#!/usr/bin/env bash

source $DOTF/framework

function main() {
  if dotf-command-missing fish; then
    dotf-apt fish
    # $DOTF/extra/fish/build
  fi

  dotf-symlink "$DOTF/extra/fish" "$HOME/.config/fish"
}

main "$@"
