#!/bin/bash

source $DOTF/framework

main() {
  header 'Midnight Commander'

  if is_mac; then
    brew_install mc
  else
    apt_install mc
  fi

  make_dir ~/.config/mc
  symlink "$DOTF/plugin/mc/ini" ~/.config/mc/ini
}

main "$@"
