#!/usr/bin/env bash

# $DOTF/extra/gnome3/one-dark.sh

function gset() {
  gsettings set "$1" "$2" "$3"
  echo -n "$1.$2: "
  gsettings get "$1" "$2"
}

gset org.gnome.desktop.input-sources sources "[('xkb', 'us'), ('xkb', 'il')]"
gset org.gnome.desktop.input-sources xkb-options "['ctrl:nocaps']"
gset org.gnome.desktop.interface show-battery-percentage true
gset org.gnome.desktop.interface enable-animations false
gset org.gnome.desktop.wm.preferences resize-with-right-button true

# Auto-hide the dock
gset org.gnome.shell.extensions.dash-to-dock dock-fixed false

# Makes Alt+Tab switch only between windows in the current workspace.
gset org.gnome.shell.app-switcher current-workspace-only true
