#!/usr/bin/env bash

source $DOTF/framework

VERSION='0.8.1'

main() {
  header 'Ripgrep'

  bullet 'Installing ripgrep...'
  if is_ripgrep_installed; then
    info 'already installed'
  else
    install_ripgrep
  fi

  symlink $DOTF/plugins/ripgrep/rgignore $HOME/.rgignore
}

is_ripgrep_installed() {
  if command_missing rg; then
    return -1
  fi

  version="$(rg --version | head -1 | awk '{ print $2 }')"
  [ "$version" == "$VERSION" ]
}

install_ripgrep() {
  if is_arch; then
    pacman_install ripgrep
  elif is_debian; then
    PLATFORM='x86_64-unknown-linux-musl'
    install_ripgrep_tgz
  elif is_mac; then
    PLATFORM='x86_64-apple-darwin'
    install_ripgrep_tgz
  fi
}

install_ripgrep_tgz() {
  name="ripgrep-$VERSION-$PLATFORM"
  url="https://github.com/BurntSushi/ripgrep/releases/download/$VERSION/$name.tar.gz"


  curl -L "$url" -o $TMP/$name.tar.gz

  install_dir=$HOME/.apps/ripgrep/$VERSION
  mkdir -p $install_dir

  cd $install_dir

  tar --strip-components=1 -xzf $TMP/$name.tar.gz
  mkdir -p $HOME/bin
  symlink $install_dir/rg $HOME/bin/rg
}

main "$@"
