#!/usr/bin/env bash

source $DOTF/framework

VERSION='0.7.1'

main() {
  if is_arch; then
    pacman_install ripgrep
  elif is_debian; then
    install_ripgrep_tgz
  fi
}

install_ripgrep_tgz() {
  name="ripgrep-$VERSION-x86_64-unknown-linux-musl"
  url="https://github.com/BurntSushi/ripgrep/releases/download/$VERSION/$name.tar.gz"


  curl -L "$url" -o $TMP/$name.tar.gz

  install_dir=$HOME/.apps/ripgrep/$VERSION
  mkdir -p $install_dir

  cd $install_dir

  tar --strip-components=1 -xzf $TMP/$name.tar.gz
  symlink $install_dir/rg $HOME/bin/rg
}

main "$@"
