#!/bin/bash

main() {
  fix-smb
  setup-ssh
}

fix-smb() {
  echo "* Fixing SMB..."

  cd ~/.smb
  if [ -e "smb-original.conf" ]; then
    echo "  already fixed"
    return
  fi

  mv smb.conf smb-original.conf
  curl https://raw.githubusercontent.com/elentok/dotfiles/master/plugins/osmc/smb.conf > smb.conf
  echo "  replaced ~/.smb/smb.conf - you need to reboot"
}

setup-ssh() {
  echo "* Creating ~/.ssh"
  mkdir -p ~/.ssh
  chmod 700 ~/.ssh

  echo "* Creating ~/.ssh_authorized_keys"
  if [ ! -e ~/.ssh/authorized_keys ]; then
    touch ~/.ssh/authorized_keys
  fi
  chmod 600 ~/.ssh/authorized_keys
}

main
