#!/usr/bin/env bash

source $DOTF/framework

RUBY_VERSION='2.5.1'

main() {
  install_requirements
  install_rbenv
  install_ruby

  create_symlinks
}

install_requirements() {
  if is_debian; then
    # As instructed in https://github.com/rbenv/ruby-build/wiki
    apt-fast-install autoconf bison build-essential libssl-dev libyaml-dev \
      libreadline-dev zlib1g-dev libncurses5-dev libffi-dev libgdbm-dev
    # libgdbm5 libreadline6-dev 
  fi
}

install_rbenv() {
  if is_mac; then
    brew_install rbenv
    brew_install ruby-build
  else
    git_clone "https://github.com/rbenv/rbenv.git" "$HOME/.rbenv" --update
    git_clone "https://github.com/rbenv/ruby-build.git" \
      "$HOME/.rbenv/plugins/ruby-build" --update
  fi

  eval "$(rbenv init -)"
}

install_ruby() {
  bullet "Installing ruby $RUBY_VERSION... "
  if [ "`rbenv versions | grep $RUBY_VERSION`" == "" ]; then
    PATH="$(path_without_linuxbrew)" rbenv install $RUBY_VERSION
    rbenv global $RUBY_VERSION
    gem install bundler
    rbenv rehash
  else
    info "already installed"
  fi
}

path_without_linuxbrew() {
  echo $PATH | tr ':' '\n' | grep -v linuxbrew | tr '\n' ':' | sed 's/:$//'
}

create_symlinks() {
  symlink "$DOTF/plugins/ruby/irbrc" ~/.irbrc
  symlink "$DOTF/plugins/ruby/rdebugrc" ~/.rdebugrc
  symlink "$DOTF/plugins/ruby/editrc" ~/.editrc
}

main "$@"
