#!/bin/bash

source `dirname $0`/../../framework

RUBY_VERSION='2.3.0'

main() {
  header "Ruby"

  install_requirements
  install_rbenv
  install_ruby
  create_symlinks
}

install_requirements() {
  if is_debian; then
    # As instructed in https://github.com/rbenv/ruby-build/wiki
    apt_install autoconf bison build-essential libssl-dev libyaml-dev \
      libreadline6-dev zlib1g-dev libncurses5-dev libffi-dev libgdbm3 \
      libgdbm-dev
  fi
}

install_rbenv() {
  brew_install rbenv
  brew_install ruby-build
  eval "$(rbenv init -)"
}

install_ruby() {
  bullet "Installing ruby $RUBY_VERSION... "
  if [ "`rbenv versions | grep $RUBY_VERSION`" == "" ]; then
    rbenv install $RUBY_VERSION
    rbenv global $RUBY_VERSION
    gem install bundle
    rbenv rehash
  else
    info "already installed"
  fi
}

create_symlinks() {
  symlink "$DOTF/plugins/ruby/irbrc" ~/.irbrc
  symlink "$DOTF/plugins/ruby/rdebugrc" ~/.rdebugrc
  symlink "$DOTF/plugins/ruby/editrc" ~/.editrc
}

main "$@"
