#!/usr/bin/env bash

set -euo pipefail

tvroot="$DOTF/extra/television"

source "$DOTF/framework.sh"

dotf-symlink "$tvroot/" ~/.config/television

# Update shell integrations
mkdir -p "$tvroot/shell"
tv init fish >"$tvroot/shell/integration.fish"
