#!/usr/bin/env bash

source $DOTF/framework
source $DOTF/scripts/build-helper

prepare_build neovim-qt master "$*"

# if is_debian; then
  # apt_install libtool-bin autoconf automake cmake g++ pkg-config \
    # python-pip python-dev unzip
# fi

if [ "${CLEAN:-}" != "no" ]; then
  git clone --depth 1 --branch $VERSION https://github.com/equalsraf/neovim-qt
fi

cd neovim-qt

# mkdir build
# cd build
# cmake -DCMAKE_BUILD_TYPE=Release ..
# make
cp -R $BUILD_DIR/neovim-qt/build/bin $INSTALL_DIR/

install_symlinks bin/nvim-qt
