#!/usr/bin/env bash

source $DOTF/framework
source $DOTF/scripts/build-helper

prepare_build neovim v0.2.2 "$*"

if is_debian; then
  apt_install libtool-bin autoconf automake cmake g++ pkg-config \
    python-pip python-dev unzip
fi

git clone --depth 1 --branch $VERSION https://github.com/neovim/neovim.git

cd neovim
make install \
  CMAKE_EXTRA_FLAGS=-DCMAKE_INSTALL_PREFIX=$INSTALL_DIR \
  CMAKE_BUILD_TYPE=RelWithDebInfo

install_symlinks bin/nvim
