#!/usr/bin/env bash

rm -rf ~/.config/coc
rm -rf ~/.config/nvim/plugged/coc.nvim
nvim +PlugInstall +UpdateRemotePlugins

extensions="coc-tsserver coc-json coc-html coc-eslint coc-tslint coc-css coc-prettier"
nvim "+CocInstall $extensions"
