#!/usr/bin/env bash

VERSION=v0.4.3

source $DOTF/framework
source $DOTF/scripts/build-helper

prepare_build neovim $VERSION "$*"

ARCH=linux64
if is_mac; then ARCH=macos; fi

cd $INSTALL_DIR
FILENAME=nvim-$ARCH.tar.gz
echo https://github.com/neovim/neovim/releases/download/$VERSION/$FILENAME
curl -L -O https://github.com/neovim/neovim/releases/download/$VERSION/$FILENAME
tar xzvf $FILENAME

install_symlinks nvim-$ARCH/bin/nvim
