#!/usr/bin/env bash

set -euo pipefail

source "$DOTF/framework"

LUA_VERSION=5.3.5
LUAROCKS_VERSION=3.7.0
LSP_VERSION=master

LUA_ROOT="$(app-dir lua ${LUA_VERSION})"

function main() {
  apt-fast-install build-essential libreadline-dev cmake

  install-lua
  install-luarocks
  install-lua-language-server

  if command_missing lua-format; then
    luarocks install --local --server=https://luarocks.org/dev luaformatter
  fi

  symlink "$DOTF/.lua-format" "$HOME/.lua-format"
}

function install-lua() {
  if ! app-exists lua ${LUA_VERSION}; then
    build-lua
  fi
  app-set-default lua ${LUA_VERSION}
}

function install-luarocks() {
  if ! app-exists luarocks ${LUAROCKS_VERSION}; then
    build-luarocks
  fi
  app-set-default luarocks ${LUAROCKS_VERSION}
}

function build-lua() {
  header 'Building Lua'
  build_dir="$(app-prepare-build-dir lua)"
  app_dir="$(app-prepare-dir lua $LUA_VERSION)"

  cd "$build_dir"
  curl -R -O http://www.lua.org/ftp/lua-${LUA_VERSION}.tar.gz
  tar -zxf lua-${LUA_VERSION}.tar.gz
  cd lua-${LUA_VERSION}
  make linux test
  make install INSTALL_TOP="$app_dir"
}

function build-luarocks() {
  header 'Building Lua Rocks'
  build_dir="$(app-prepare-build-dir luarocks)"
  app_dir="$(app-prepare-dir luarocks $LUAROCKS_VERSION)"

  cd "$build_dir"
  wget https://luarocks.org/releases/luarocks-${LUAROCKS_VERSION}.tar.gz
  tar zxpf luarocks-${LUAROCKS_VERSION}.tar.gz
  cd luarocks-${LUAROCKS_VERSION}

  ./configure --with-lua="${LUA_ROOT}" --prefix="${app_dir}"
  make
  make install
}

function install-lua-language-server() {
  if ! app-exists lua-language-server $LSP_VERSION; then
    build-lua-language-server
  fi

  app-set-default lua-language-server $LSP_VERSION
}

function build-lua-language-server() {
  header 'Building Lua Language Server'

  die-unless-gcc-10

  app_dir="$(app-prepare-dir lua-language-server $LSP_VERSION)"

  cd "$app_dir/.."
  git clone https://github.com/sumneko/lua-language-server $LSP_VERSION
  cd $LSP_VERSION
  git submodule update --init --recursive

  cd 3rd/luamake
  compile/install.sh
  cd ../..
  ./3rd/luamake/luamake rebuild
}

function die-unless-gcc-10() {
  gcc_version=$(gcc --version | head -1 | awk '{print $NF}' | cut -d. -f1)
  if [ "$gcc_version" -lt 10 ]; then
    echo "WARNING: The lua language server requires gcc-10 at least."
    return
  fi
}

main "$@"
