#!/usr/bin/env bash

set -euo pipefail

source "$DOTF/framework"

CONFIG_DIR="$HOME/.config/i3"

dotf-apt i3 rofi dex compton

mkdir -p "$CONFIG_DIR"
symlink "$DOTF/extra/i3/config" "$CONFIG_DIR/config"
