#!/usr/bin/env bash

set -euo pipefail

source "$DOTF/framework.sh"

CONFIG_ROOT="$HOME/.config"
CONFIG_DIR="$CONFIG_ROOT/i3"

dotf-apt i3 rofi dex compton

mkdir -p "$CONFIG_DIR"
dotf-symlink "$DOTF/extra/i3/config" "$CONFIG_DIR/config"
dotf-symlink "$DOTF/extra/i3/compton.conf" "$CONFIG_ROOT/compton.conf"
