#!/usr/bin/env bash

set -euo pipefail

CONFIG_ROOT="$HOME/.config"
CONFIG_DIR="$CONFIG_ROOT/i3"

dfl pkg apt install i3 rofi dex compton

mkdir -p "$CONFIG_DIR"
dfl symlink "$DOTF/extra/i3/config" "$CONFIG_DIR/config"
dfl symlink "$DOTF/extra/i3/compton.conf" "$CONFIG_ROOT/compton.conf"
