#!/usr/bin/env bash

source "$DOTF/framework.sh"

main() {
  if dotf-is-linux; then
    dotf-apt openssh-server
  fi

  setup_authorized_keys

  echo
  echo "For extra security:"
  echo
  echo "1. Add a public key to ~/.ssh/authorized_keys"
  echo "2. Disable password auth:"
  echo
  echo "      PasswordAuthentication no"
  echo
  echo "3. Run 'systemctl restart ssh'"
}

setup_authorized_keys() {
  dotf-bullet 'Creating ~/.ssh/authorized_keys... '
  if [ -e ~/.ssh/authorized_keys ]; then
    dotf-info 'already exists'
  else
    mkdir -p ~/.ssh
    touch ~/.ssh/authorized_keys
    show_result
  fi

  dotf-bullet 'Setting ~/.ssh/authorized_keys permissions... '
  chmod 600 ~/.ssh/authorized_keys
  show_result
}

main
