#!/usr/bin/env bash

main() {
  if dfl os is-linux; then
    dfl pkg apt install openssh-server
  fi

  setup_authorized_keys

  echo
  echo "For extra security:"
  echo
  echo "1. Add a public key to ~/.ssh/authorized_keys"
  echo "2. Disable password auth:"
  echo
  echo "      PasswordAuthentication no"
  echo
  echo "3. Run 'systemctl restart ssh'"
}

setup_authorized_keys() {
  dfl step start 'Creating ~/.ssh/authorized_keys...'
  if [ -e ~/.ssh/authorized_keys ]; then
    dfl step skip 'already exists'
  else
    mkdir -p ~/.ssh
    touch ~/.ssh/authorized_keys
    dfl step success 'created'
  fi

  dfl step start 'Setting ~/.ssh/authorized_keys permissions...'
  chmod 600 ~/.ssh/authorized_keys
  dfl step success 'done'
}

main
