#!/usr/bin/env bash

set -euo pipefail

source "$(dirname "$0")/../../framework"

LUA_VERSION=5.3.5
LUAROCKS_VERSION=3.7.0

ALL_APPS="${HOME}/.apps/all"
LUA_ROOT="$(app-dir lua ${LUA_VERSION})"
LSP_ROOT="${ALL_APPS}/lua-language-server"

function main() {
  apt-fast-install build-essential libreadline-dev cmake

  if ! app-exists lua ${LUA_VERSION}; then
    build-lua
  fi
  app-set-default lua ${LUA_VERSION}

  if ! app-exists luarocks ${LUAROCKS_VERSION}; then
    build-luarocks
  fi
  app-set-default luarocks ${LUAROCKS_VERSION}

  if [ ! -e "$LSP_ROOT/bin/Linux/lua-language-server" ]; then
    install-language-server
  fi

  if command_missing lua-format; then
    luarocks install --local --server=https://luarocks.org/dev luaformatter
  fi
}

function build-lua() {
  build_dir="$(app-prepare-build-dir lua)"
  app_dir="$(app-prepare-dir lua $LUA_VERSION)"

  cd "$build_dir"
  curl -R -O http://www.lua.org/ftp/lua-${LUA_VERSION}.tar.gz
  tar -zxf lua-${LUA_VERSION}.tar.gz
  cd lua-${LUA_VERSION}
  make linux test
  make install INSTALL_TOP="$app_dir"
}

function build-luarocks() {
  build_dir="$(app-prepare-build-dir luarocks)"
  app_dir="$(app-prepare-dir luarocks $LUAROCKS_VERSION)"

  cd "$build_dir"
  wget https://luarocks.org/releases/luarocks-${LUAROCKS_VERSION}.tar.gz
  tar zxpf luarocks-${LUAROCKS_VERSION}.tar.gz
  cd luarocks-${LUAROCKS_VERSION}

  ./configure --with-lua="${LUA_ROOT}" --prefix="${app_dir}"
  make
  make install
}

function install-language-server() {
  gcc_version=$(gcc --version | head -1 | awk '{print $NF}' | cut -d. -f1)
  if [ "$gcc_version" -lt 10 ]; then
    echo "WARNING: The lua language server requires gcc-10 at least."
    return
  fi

  if [ -e "$LSP_ROOT" ]; then
    rm -rf "${LSP_ROOT}.old"
    mv "$LSP_ROOT" "${LSP_ROOT}.old"
  fi

  mkdir -p "$ALL_APPS"
  cd "$ALL_APPS"

  git clone https://github.com/sumneko/lua-language-server
  cd lua-language-server
  git submodule update --init --recursive

  cd 3rd/luamake
  compile/install.sh
  cd ../..
  ./3rd/luamake/luamake rebuild
}

main "$@"
