#!/usr/bin/env bash

source `dirname $0`/../../framework

main() {
  if [ "$OS" != "linux" ]; then
    echo 'Only supported on linux'
    exit 1
  fi

  header 'Java 16'

  if ! apt-key list | grep AdoptOpenJDK > /dev/null 2>&1; then
    bullet 'Installing jfrog key...'
    wget -qO - https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public | sudo apt-key add -
  fi
  echo
  apt-fast-add-repo https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/
  echo
  apt-fast-install adoptopenjdk-16-hotspot
}

main "$@"
