#!/bin/bash

source `dirname $0`/../../framework

GITCONFIG="$HOME/.gitconfig"

main() {
  header "Git"
  should_install_custom_git && install_git
  install_gitconfig
  install_symlinks
  install_diff_so_fancy
}

should_install_custom_git() {
  [ ! -x /usr/local/git/current/bin/git ]
}

install_git() {
  if is_mac; then
    brew_install git
    brew_install tig
  else
    apt_install git libncurses5-dev
    if ! has_command tig; then
      install_tgz --sudo 'https://github.com/jonas/tig/archive/tig-2.1.1.tar.gz'
    fi
  fi
}

install_gitconfig() {
  bullet "Installing $GITCONFIG... "
  if [ -e $GITCONFIG -o -h $GITCONFIG ]; then
    fix_existing_gitconfig
  else
    write_to_gitconfig
    success 'done'
  fi
}

fix_existing_gitconfig() {
  if [ -h $GITCONFIG ]; then
    backup $GITCONFIG
    write_to_gitconfig
    success 'done'
  else
    if [ -n "$(grep "path = $DOTF/plugins/git/gitconfig" $GITCONFIG)" ]; then
      info 'already installed'
    else
      echo >> $GITCONFIG
      write_to_gitconfig
      success 'done'
    fi
  fi
}

write_to_gitconfig() {
  if [ ! -e $GITCONFIG ]; then
    touch $GITCONFIG
  fi
  echo "[include]" >> $GITCONFIG
  echo "  path = $DOTF/plugins/git/gitconfig" >> $GITCONFIG
}

install_symlinks() {
  symlink "$DOTF/plugins/git/tigrc" ~/.tigrc
}

install_diff_so_fancy() {
  if is_mac; then
    brew_install diff-so-fancy
  else
    npm_install diff-so-fancy
  fi
}

main "$@"
