#!/bin/bash

source `dirname $0`/../../framework

GITCONFIG="$HOME/.gitconfig"

main() {
  header "Git"
  if [ "$1" != "symlinks" ]; then
    install_git
  fi
  install_gitconfig
  install_symlinks
}

install_git() {
  if [ "$OS" == "mac" ]; then
    brew_install git
    brew_install tig
  else
    apt_install git tig
  fi
}

install_gitconfig() {
  bullet "Installing $GITCONFIG... "
  if [ -e $GITCONFIG -o -h $GITCONFIG ]; then
    fix_existing_gitconfig
  else
    write_to_gitconfig
    success 'done'
  fi
}

fix_existing_gitconfig() {
  if [ -h $GITCONFIG ]; then
    backup $GITCONFIG
    write_to_gitconfig
    success 'done'
  else
    if [ -n "$(grep "path = $DOTF/plugins/git/gitconfig" $GITCONFIG)" ]; then
      info 'already installed'
    else
      echo >> $GITCONFIG
      write_to_gitconfig
      success 'done'
    fi
  fi
}

write_to_gitconfig() {
  if [ ! -e $GITCONFIG ]; then
    touch $GITCONFIG
  fi
  echo "[include]" >> $GITCONFIG
  echo "  path = $DOTF/plugins/git/gitconfig" >> $GITCONFIG
}

install_symlinks() {
  symlink "$DOTF/plugins/git/tigrc" ~/.tigrc
}

main "$@"
