# Default keymaps: https://github.com/sxyazi/yazi/blob/shipped/yazi-config/preset/keymap-default.toml

[manager]

prepend_keymap = [
  { on = "o", run = "create", desc = "Create a file (ends with / for directories)" },
  { on = "<Enter>", run = "enter", desc = "Enter the child directory" },
  { on = [
    "g",
    "x",
  ], run = "open", desc = "Open selected files" },
  { on = [
    "c",
    "w",
  ], run = "rename --cursor=before_ext", desc = "Rename selected file(s)" },
]

[input]

prepend_keymap = [{ on = "q", run = "close", desc = "Cancel input" }]
