for config_file in $HOME/.zsh/before/*.zsh; do
  source $config_file
done

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

for config_file in $HOME/.zsh/after/*.zsh; do
  source $config_file
done
