# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="robbyrussell"
#ZSH_THEME="terminalparty"
#ZSH_THEME="gnzh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Example format: plugins=(rails git textmate ruby lighthouse)
#plugins=(git)
plugins=(git rails3 mercurial python bundler)
# IMPORTANT: the 'gem' and 'rvm' plugins cause a slowdown


source $ZSH/oh-my-zsh.sh


# Customize to your needs...
export PATH=$HOME/.rvm/bin:$HOME/.config/dotfiles/scripts:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/home/david/bin
#export PATH=/home/david/.rvm/gems/ruby-1.9.3-p0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/home/david/bin
#export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/home/david/bin

export MPD_HOST=bob@localhost

# ALIASES
alias m=ncmpcpp
alias x=exit
alias mf='mpc search filename'
alias ma='mpc add'
alias mp='mpc play'
alias mcl='mpc clear'
alias sr='screen -R'
alias ak='ssh-add ~/.keys/bitbucket.ssh.private'
alias cl='xclip -selection clipboard -o'
alias ft="ruby /home/david/projects/tvutils/bin/filestube.rb -s filesonic"
alias sub="ruby /home/david/projects/tvutils/bin/download_subtitles.rb"
alias clean="ruby /home/david/projects/tvutils/bin/clean.rb"
alias ack='ack-grep'
alias ackc='ack-grep --coffee'
alias st='scrot -s'
alias dotf='cd ~/.config/dotfiles'
alias dotv='cd ~/.config/dotvim'
alias rr='source ~/.config/dotfiles/scripts/init-rvm'
alias ls='ls --color=always -XFhs'
alias mac='ruby ~/projects/macrumors/macrumors.rb'
alias wp='feh --bg-fill'
alias pryy='pry -r ./config/environment'

# so tmux will allow 256 colors:
export TERM=xterm-256color
