#!/usr/bin/env bash

source $DOTF/framework

pip-fast-install ranger-fm python-bidi

mkdir -p ~/.config/ranger
symlink $DOTF/plugins/ranger/rc.conf ~/.config/ranger/rc.conf
symlink $DOTF/plugins/ranger/commands.py ~/.config/ranger/commands.py

if is_debian; then
  apt_install atool w3m highlight
fi

#brew_install atool # archive tool (for als)
#brew_install w3c

# these require XQuarts to be installed
# brew_install xpdf
# brew_install imlib2 # for libcaca
# brew_install libcaca --with-imlib2 # for img2txt

