#!/usr/bin/env bash

brew_install ranger

brew_install atool # archive tool (for als)
brew_install w3c

# these require XQuarts to be installed
brew_install xpdf
brew_install imlib2 # for libcaca
brew_install libcaca --with-imlib2 # for img2txt

