#!/usr/bin/env bash

set -euo pipefail

source "$DOTF/framework.sh"

function main() {
  install-poetry

  # Clear the pyver cache (so it's rebuilt on the next shell)
  rm -f ~/.local/cache/dotfiles/pyver
}

function install-poetry() {
  dfl step start "Installing poetry... "

  # dotf-bullet "Installing poetry... "
  if ! dfl has-command poetry; then
    curl -sSL https://install.python-poetry.org | python3 -
    dfl step success
  else
    dfl step skip "already installed."
  fi
}

main "$@"
