#!/usr/bin/env bash

set -euo pipefail

source "$DOTF/framework.sh"

function main() {
  install-poetry

  # Clear the pyver cache (so it's rebuilt on the next shell)
  rm -f ~/.local/cache/dotfiles/pyver
}

function install-poetry() {
  dotf-bullet "Installing poetry... "
  if dotf-command-missing poetry; then
    curl -sSL https://install.python-poetry.org | python3 -
    dotf-success "done"
  else
    dotf-info "already installed."

  fi
}

main "$@"
