#!/usr/bin/env bash

set -euo pipefail

function main() {
  dfl mkdir ~/.config

  install-homebrew

  dfl shell "Installing Homebrew bundle" -- brew bundle install

  install-apt-pkgs

  dfl install fish nvim git ripgrep tig bat bash tmux yazi nodejs python ai

  if dfl os is-mac; then
    dfl symlink ~/Library/Mobile\ Documents/com~apple~CloudDocs ~/iCloud
    dfl install osx-tuning
  fi
}

function install-homebrew() {
  if dfl os is-mac; then
    export PATH="/opt/homebrew/bin:$PATH"
  else
    export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
  fi

  if dfl has-command brew; then
    return
  fi

  if dfl os is-linux; then
    dfl pkg apt install curl
  fi

  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
}

function install-apt-pkgs() {
  if dfl os is-linux; then
    dfl pkg apt install build-essential cmake libreadline-dev cifs-utils curl git htop ncdu plantuml \
      unzip wget qalc ffmpeg pv fish xclip toilet
  fi
}

main "$@"
