#!/usr/bin/env bash

source $DOTF/framework

VERSION=0.5.1

main() {
  header 'Gron'

  if is_linux; then
    PLATFORM='linux-amd64'
    install_gron_tgz
  elif is_mac; then
    PLATFORM='darwin-amd64'
    install_gron_tgz
  elif command_missing gron; then
    echo 'Error: Unsupported platform for gron'
  fi
}

install_gron_tgz() {
  name="gron-$PLATFORM-$VERSION.tgz"
  url="https://github.com/tomnomnom/gron/releases/download/v$VERSION/$name"


  curl -L "$url" -o $TMP/$name

  install_dir=$HOME/.apps/gron/$VERSION
  mkdir -p $install_dir

  cd $install_dir

  tar -xzvf $TMP/$name
  symlink $install_dir/gron $HOME/bin/gron
}

main "$@"
