#!/usr/bin/env bash

source $DOTF/framework

header "GUI Apps"

COMMON="vlc feh gimp qalculate-gtk keepassxc"

if is_arch; then
  pacman_install $COMMON gvfs
elif is_debian; then
  apt_install $COMMON
elif is_fedora; then
  yum_install $COMMON
fi
