#!/usr/bin/env bash

source "$DOTF/framework"

bullet 'Installing rust...'
if has_command rustc; then
  info 'already installed.'
else
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -o /tmp/rustup-init
  sh /tmp/rustup-init --no-modify-path -y
fi

if command_missing exa; then
  cargo install exa
fi

if command_missing alacritty; then
  apt-fast-install cmake pkg-config libfreetype6-dev libfontconfig1-dev libxcb-xfixes0-dev python3
  cargo install alacritty
fi
