#!/usr/bin/env bash

source $DOTF/framework

if is_linux; then
  apt-fast-install ncdu curl wget htop imagemagick
elif is_mac; then
  brew_install ncdu
  brew_install curl
  brew_install wget
  brew_install htop
  brew_install imagemagick
fi
