#!/usr/bin/env bash

source $DOTF/framework

VERSION=5.3.0

if command_missing ulauncher; then
  apt-fast-install python3-distutils-extra python3-levenshtein python3-websocket

  cd $TMP
  curl -L -O https://github.com/Ulauncher/Ulauncher/releases/download/${VERSION}/ulauncher_${VERSION}_all.deb
  sudo dpkg -i ulauncher_${VERSION}_all.deb
fi
