#!/usr/bin/env bash
#
# ./install {service-name} [user|system]

name="$1"
mode="$2"

name="$(echo $name | sed 's/\.service\.erb$//')"

if [ ! -e "$name.service.erb" ]; then
  usage "$0"
  exit 1
fi

if [ "$mode" == "user" ]; then
  erb "$name.service.erb" > "$HOME/.local/share/systemd/user/$name.service"
else
  erb "$name.service.erb" > /tmp/$name.service
  sudo mv /tmp/$name.service "/usr/lib/systemd/system/$name.service"
fi
