#!/usr/bin/env bash

apt-get install g++ gcc make git build-essential \
  libc6-dev patch openssl libmysql++-dev \
  ca-certificates libreadline6  curl zlibg1 libsqlite3-dev \
  libyaml-dev libreadline6-dev zlib1g-dev libyaml-dev \
  sqlite3 libreadline-dev libxslt1-dev \
  libffi-dev libgdbm-dev \
  libxml2-dev libxslt1-dev autoconf libc6-dev libgdbm-dev \
  libncurses5-dev automake libtool bison pkg-config libffi-dev \
  ncurses-dev libssl-dev libssl \
  imagemagick libmagickwand-dev \
  postgresql-server-dev-9.1
