#!/bin/bash
RAILS_VERSIONS=( 1.9.3-p0 2.0.0-p0 2.0.0-p247 )
DEFAULT_RAILS=${RAILS_VERSIONS[$(( $total-1 ))]}

BLUE="\033[34m"
RESET="\033[0m"

main() {
  install_rbenv
  load_rbenv
  install_ruby_build
  install_ruby
}

install_rbenv() {
  header "Installing rbenv"
  git clone https://github.com/sstephenson/rbenv.git ~/.rbenv
  add_rbenv_to_bash_profile
}

add_rbenv_to_bash_profile() {
  echo '' >> ~/.bash_profile
  echo '# rbenv:' >> ~/.bash_profile
  echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bash_profile
  echo 'eval "$(rbenv init -)"' >> ~/.bash_profile
}

load_rbenv() {
  header "Loading rbenv"
  export PATH="$HOME/.rbenv/bin:$PATH"
  eval "$(rbenv init -)"
}

install_ruby_build() {
  header "Installing ruby-build"
  git clone https://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build
}

install_ruby() {
  for rv in "${RAILS_VERSIONS[@]}"
  do
    header "Installing Ruby $rv"
	  rbenv install $rv
	  
	  header "Setting up Ruby $rv"
	  rbenv global $rv
	  gem install bundler
	  rbenv rehash
  done
  
  header "Initializing global Ruby"
  rbenv global $DEFAULT_RAILS
  rbenv rehash

  echo "Active ruby version: (should be $DEFAULT_RAILS)"
  ruby --version # should output 2.0.0-p247
}

header() {
  echo ""
  echo -e "${BLUE}==============================${RESET}"
  echo -e "${BLUE}* $*${RESET}"
}

main
