#!/usr/bin/env bash

set -euo pipefail

function main() {
  for key in $(dup-keys); do
    echo "=== ${key} ==="
    rg --case-sensitive "$key" || rg --case-sensitive "${key//leader/space}"
    echo
  done
}

function dup-keys() {
  rg --case-sensitive --no-filename -tlua --only-matching '<(space|leader)>[a-zA-Z0-9]+' \
    | sed 's/space/leader/' \
    | sort \
    | uniq -c \
    | grep -v '^\s*1 ' \
    | awk '{print $2}'
}

main
