#!/usr/bin/env bash

# NOTE: If I ever want to go back to zsh I need to run this on setup:
# git submodule update --init --recursive

function main() {
  set_zsh_as_default_shell
  install_symlinks
  install_fzf
  install_starship
  reset_completion_cache

  # fix premissions issue
  chmod -R g-w "$DOTF/extra/zsh/vendor/zsh-completions"
}

function set_zsh_as_default_shell() {
  if dfl os is-mac; then
    my_shell=$(echo "$SHELL" | rev | cut -d/ -f1 | rev)
    if [ "$my_shell" != "zsh" ]; then
      zsh_bin="$(which zsh)"
      dfl step start "Changing shell to ${zsh_bin}..."
      chsh -s "$zsh_bin"
    fi
  else
    zsh_bin="$(which zsh)"
    dfl step start "Changing user's shell to $zsh_bin..."
    if [[ "$SHELL" =~ /zsh ]]; then
      dfl step skip 'already set'
    else
      chsh -s "$zsh_bin"
    fi
  fi
}

function install_symlinks() {
  dfl symlink "$DOTF/extra/zsh" ~/.zsh
  dfl symlink "$DOTF/extra/zsh/zshrc" ~/.zshrc
  dfl symlink "$DOTF/extra/zsh/zshenv" ~/.zshenv
  dfl symlink "$DOTF/extra/zsh/zprofile" ~/.zprofile
}

function install_starship() {
  # On Mac starship is installed via Homebrew
  if ! dfl has-command starship; then
    if dfl os is-linux; then
      curl -sS https://starship.rs/install.sh | sh
    fi
  fi

  mkdir -p ~/.config
  dfl symlink "$DOTF/extra/zsh/starship.toml" ~/.config/starship.toml
}

function install_fzf() {
  dfl step start 'Installing FZF...'
  if [ -e ~/.fzf ]; then
    dfl step skip 'already installed.'
  else
    git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
    ~/.fzf/install --completion --key-bindings --no-update-rc
  fi
}

reset_completion_cache() {
  dfl step start 'Resetting completion cache...'
  rm -rf ~/.zcompcache
  rm -rf ~/.local/share/zcompcache
  rm -f ~/.zcompdump
  zsh -c 'autoload -U compinit && compinit'
}

main "$@"
