#!/bin/bash

set -e

sudo apt-get install libxinerama-dev libxft2 libpango1.0-dev \
  libpangocairo-1.0-0 libcairo2-dev libglib2.0-dev libx11-dev \
  libstartup-notification0-dev libxkbcommon-dev libxkbcommon-x11-dev \
  libxcb1-dev libx11-xcb-dev libxcb-ewmh-dev libxcb-icccm4-dev libxcb-util0-dev \
  libxcb-xinerama0-dev libgtk2.0-dev libperl-dev

cd /tmp
wget https://github.com/DaveDavenport/rofi/releases/download/1.1.0/rofi-1.1.0.tar.gz -O rofi.tgz

tar xvzf rofi.tgz
cd rofi*
./configure
make
sudo make install
