edge center-sized

lines 25
columns 60

margin_left 20
margin_top 20
margin_right 20
margin_bottom 20

background_opacity 0.95

kitty_override font_size 22.0
kitty_override modify_font cell_height +14px
