#!/usr/bin/env bash

set -euo pipefail

source "$DOTF/framework.sh"

CONFIG_DIR="$HOME/.config/wezterm"

function main() {
  if dotf-command-missing wezterm; then
    if dotf-is-mac; then
      dotf-brew wezterm
    else
      echo 'Not supported!'
      # install_deb "wezterm" "https://github.com/wez/wezterm/releases/download/20220807-113146-c2fee766/wezterm-20220807-113146-c2fee766.Debian11.deb"
    fi
  fi

  mkdir -p "$CONFIG_DIR"
  dotf-symlink "$DOTF/extra/wezterm" "$CONFIG_DIR"
  # dotf-symlink "$DOTF/extra/wezterm/wezterm.lua" "$CONFIG_DIR/wezterm.lua"
}

main "$@"
