#!/usr/bin/env bash

set -euo pipefail

source "$DOTF/framework"

CONFIG_DIR="$HOME/.config/wezterm"

function main() {
  if command_missing wezterm; then
    if dotf-is-mac; then
      dotf-brew wezterm
    else
      echo "TODO: Support installing wezterm on other platforms"
    fi
  fi

  mkdir -p "$CONFIG_DIR"
  symlink "$DOTF/extra/wezterm/wezterm.lua" "$CONFIG_DIR/wezterm.lua"
}

main "$@"
