#!/usr/bin/env bash

set -euo pipefail

CONFIG_DIR="$HOME/.config/wezterm"

function main() {
  if ! dfl has-command wezterm; then
    if dfl os is-mac; then
      brew install wezterm
    else
      echo 'Not supported!'
      # install_deb "wezterm" "https://github.com/wez/wezterm/releases/download/20220807-113146-c2fee766/wezterm-20220807-113146-c2fee766.Debian11.deb"
    fi
  fi

  # brew install --cask font-zed-mono-nerd-font
  brew install --cask font-caskaydia-cove-nerd-font

  mkdir -p "$CONFIG_DIR"
  dfl symlink "$DOTF/extra/wezterm" "$CONFIG_DIR"
}

main "$@"
