#!/usr/bin/env bash

main() {
  if ! dfl os is-mac; then
    if ! dfl has-command alacritty; then
      dfl pkg apt install cmake pkg-config libfreetype6-dev libfontconfig1-dev libxcb-xfixes0-dev python3 libxkbcommon-dev
      cargo install alacritty
    fi
  fi

  mkdir -p ~/.config/alacritty
  dfl symlink "$DOTF/extra/alacritty/alacritty.yml" ~/.config/alacritty/alacritty.yml

  if dfl os is-linux; then
    add-desktop-entry alacritty Alacritty "$(command -v alacritty)"
  fi
}

main "$@"
