#!/usr/bin/env bash

source "$DOTF/framework"

dotconfig verify telegram_bot_token 'Telegram bot token?'
dotconfig verify telegram_chat_id 'Telegram chat id?'

NODE=$(which node)
TELEGRAM_BOT_TOKEN=$(dotconfig get telegram_bot_token)
TELEGRAM_CHAT_ID=$(dotconfig get telegram_chat_id)

export NODE
export TELEGRAM_BOT_TOKEN
export TELEGRAM_CHAT_ID

install-service "$DOTF/extra/telegram-proxy/telegram-proxy.service" system

systemctl daemon-reload
systemctl start telegram-proxy
