#!/usr/bin/env bash

set -euo pipefail

source "$DOTF/framework"
source "$DOTF/scripts/build-helper"

version="$(dotf-trim < "$DOTF/core/tig/VERSION")"
prepare_build tig "$version" "$*"

BASENAME=tig-$version
FILENAME=$BASENAME.tar.gz

curl -O -L "https://github.com/jonas/tig/releases/download/$BASENAME/$FILENAME"
tar xzvf "$FILENAME"

cd "$BASENAME"

./configure
make prefix="$INSTALL_DIR"
make install prefix="$INSTALL_DIR"

install_symlinks bin/tig
