#!/usr/bin/env bash

source "$DOTF/framework"

main() {
  if is_mac; then
    brew_install tig
  elif command_missing tig; then
    PRIMARY=yes "$DOTF/core/tig/build"
  fi

  symlink "$DOTF/core/tig/tigrc" ~/.tigrc
}

main "$@"
