#!/usr/bin/env bash

source $DOTF/framework

if is_wsl; then
  win_home="$(wsl-path2mnt $(wsl-get-env UserProfile))"
  dirs=("$win_home/AppData/Roaming/Code")
else
  dirs=("$HOME/.config/Code" "$HOME/Library/Application Support/Code")
fi

for dir in ${dirs[@]}; do
  if [ -d "$dir" ]; then
    echo "$dir"
    exit 0
  fi
done

exit 1
