#!/usr/bin/env bash

source $DOTF/framework

ROOT=$DOTF/plugins/vscode

if is_wsl; then
  symlink \
    $(wslpath $(wsl-get-env USERPROFILE))/AppData/Roaming/Code \
    $HOME/.config/Code
fi

yarn vscode:sync