#!/usr/bin/env bash

set -euo pipefail

branch="$(git branch --show-current)"
remote_url="$(git config --get remote.origin.url)"

if [ "${1:-}" == "-b" ]; then
  shift
  branch="$(git all-branches | fzf-tmux -p --prompt 'Pick branch:')"
fi

file_suffix=""
if [ $# -gt 0 ]; then
  filepath="$(realpath "$1")"
  repo_root="$(git rev-parse --show-toplevel)"

  file_suffix="$(realpath "$filepath" | sed "s|$repo_root||")"
fi

# shellcheck disable=SC2001
echo "$remote_url" \
  | sed -E "s|git@(.*):(.*)(.git)?|https://\1/\2/tree/${branch}${file_suffix}|" \
  | sed "s/github.com-[^\/]*/github.com/"
