#!/usr/bin/env bash
#
# Pushes the current branch
#
# If there's more than one remote asks the user to pick
#
# Usage:
#
#   git psme [remote]
#

set -euo pipefail

function main() {
  if [ $# -gt 0 ]; then
    remote="${1}"
    shift
  else
    remote="$(pick-remote)"
  fi

  branch="$(git rev-parse --abbrev-ref HEAD)"

  echo
  echo "Pushing $branch to remote $remote"
  echo
  echo
  if ! git push -u "$remote" "$branch" "$@"; then
    if gum confirm --prompt.foreground=9 "Push failed, use force? 💪"; then
      echo
      echo "Pushing $branch to remote $remote with force"
      echo
      echo
      if git push -u -f "$remote" "$branch" "$@"; then
        echo
        dfl step success "Pushed successfuly"
      else
        echo
        dfl step error "Failed to push"
      fi
    fi
  else
    echo
    dfl step success "Pushed successfuly"
  fi
}

function pick-remote() {
  remotes="$(git remote)"
  count="$(echo "$remotes" | wc -l)"
  if [ "$count" -eq 0 ]; then
    echo >&2 "Error: No remotes found"
    exit 1
  elif [ "$count" -eq 1 ]; then
    echo "$remotes"
  else
    echo "$remotes" | fzf-tmux -p
  fi
}

main "$@"
