#!/usr/bin/env bash

set -euo pipefail

function main() {
  branch="$(git branch --show-current)"
  if [ "${1:-}" == "-b" ]; then
    shift
    branch="$(git all-branches | fzf-tmux -p --prompt 'Pick branch:')"
  fi

  file_suffix="$(url-file-suffix "$@")"

  echo "$(repo-base-url)/tree/${branch}${file_suffix}"
}

function repo-base-url() {
  remote="$(git-pick-remote)"
  git config --get "remote.$remote.url" \
    | ssh-to-https \
    | sed "s|github.com-[^/]*|github.com|" \
    | sed "s|.git$||"
}

function git-pick-remote() {
  git remote | fzf-tmux -p --prompt 'Pick remote:' --select-1
}

function ssh-to-https() {
  sed -E 's|git@(.*):(.*)(.git)?|https://\1/\2|'
}

function url-file-suffix() {
  if [ $# -gt 0 ]; then
    filepath="$(realpath "$1")"
    repo_root="$(git rev-parse --show-toplevel)"

    realpath "$filepath" | sed "s|$repo_root||"
  fi
}

main "$@"
