#!/usr/bin/env bash

set -e

main() {
  echo 'Git Auto Sync'

  check-if-autosync-is-enabled

  commit-if-needed
  if [ "${1:-}" != "--commit-only" ]; then
    pull
    push
  fi
  dfl step success 'done'
}

check-if-autosync-is-enabled() {
  if [ "$(git config --local --get elentok.autosync)" == "true" ]; then
    return
  fi

  if dfl confirm "Autosync is not enabled for this repo, enable?"; then
    git config --local --add elentok.autosync true
    return
  fi

  exit 1
}

commit-if-needed() {
  dfl step start 'Checking for changes...'
  if [ -n "$(git status --porcelain)" ]; then
    commit
  else
    dfl step skip 'no changes'
  fi
}

commit() {
  dfl step start "Commiting changes..."
  date=$(date +%Y-%m-%d\ %H:%M)
  host=$(short-hostname)
  git add --all
  git commit -m "Update $date ($host)"
}

pull() {
  dfl step start "Pulling changes..."
  git pull --rebase
}

push() {
  dfl step start "Pushing changes..."
  git push
}

main "$@"
