#!/usr/bin/env bash
#
# Pushes the current branch
#
# If there's more than one remote asks the user to pick
#
# Usage:
#
#   git psme [remote]
#

set -euo pipefail

source "$DOTF/core/scripts/lib/ui.sh"

function main() {
  if [ $# -gt 0 ]; then
    remote="${1}"
    shift
  else
    remote="$(pick-remote)"
  fi

  branch="$(git rev-parse --abbrev-ref HEAD)"

  pretty_branch=" $branch"

  echo
  dotf-color blue "Pushing [$pretty_branch] 󰳟 [remote $remote]"
  echo
  echo
  if ! git push -u "$remote" "$branch" "$@"; then
    if dotf-confirm "$(dotf-color red "Push failed, use force?")"; then
      echo
      dotf-color red "Pushing [$pretty_branch] 󰳟 [remote $remote] with force"
      echo
      echo
      if git push -u -f "$remote" "$branch" "$@"; then
        echo
        dotf-success "Pushed successfuly"
      else
        echo
        dotf-error "Failed to push"
      fi
    fi
  else
    echo
    dotf-success "Pushed successfuly"
  fi
}

function pick-remote() {
  remotes="$(git remote)"
  count="$(echo "$remotes" | wc -l)"
  if [ "$count" -eq 0 ]; then
    echo >&2 "Error: No remotes found"
    exit 1
  elif [ "$count" -eq 1 ]; then
    echo "$remotes"
  else
    echo "$remotes" | fzf-tmux -p
  fi
}

main "$@"
