#!/usr/bin/env bash
#
# Creates a fixup commit and rebases it
#
# Usage:
#
# git fix <revision>
#

main() {
  if [ $# -eq 0 ]; then
    usage "$0"
  else
    fix-commit "$1"
  fi
}

fix-commit() {
  rev="$1"
  title=$(commit-title $rev)

  if dfl confirm "Fixup '$title'" yes; then

    dfl step start "Creating fixup commit..."
    git commit --fixup $rev
    dfl step success "done."

    if dfl confirm "Autosquash" yes; then
      dfl step start "Autosquashing..."
      git rebase -i --autosquash $rev~1
      dfl step success "done."
    fi
  fi
}

commit-title() {
  git log -1 --pretty=%s $1
}

main "$@"
