#!/usr/bin/env bash

set -e

source "$DOTF/framework.sh"

main() {
  dotf-header h1 'Git Auto Sync'

  check-if-autosync-is-enabled

  commit-if-needed
  pull
  push
  dotf-success 'done'
}

check-if-autosync-is-enabled() {
  if [ "$(git config --local --get elentok.autosync)" == "true" ]; then
    return
  fi

  if dotf-confirm "Autosync is not enabled for this repo, enable?"; then
    git config --local --add elentok.autosync true
    return
  fi

  exit 1
}

commit-if-needed() {
  dotf-bullet 'Checking for changes... '
  if [ -n "$(git status --porcelain)" ]; then
    echo
    commit
  else
    dotf-info 'no changes'
  fi
}

commit() {
  dotf-bullet "Commiting changes..."
  echo
  date=$(date +%Y-%m-%d\ %H:%M)
  host=$(short-hostname)
  git add --all
  git commit -m "Update $date ($host)"
  echo
}

pull() {
  dotf-bullet "Pulling changes... "
  git pull --rebase
}

push() {
  dotf-bullet "Pushing changes... "
  git push
}

main "$@"
