#!/usr/bin/env bash

set -euo pipefail

git config github.user elentok
git config user.name 'David Elentok'
git config user.email '3david@gmail.com'

origin="$(git config remote.origin.url)"
if [[ "$origin" =~ github.com: ]]; then
  origin="${origin/github.com:/github.com-personal:}"
  git config remote.origin.url "$origin"
fi
