#!/usr/bin/env bash
#
# Creates a fixup commit and rebases it
#
# Usage:
#
# git fix <revision>
#

source $DOTF/framework.sh

main() {
  if [ $# -eq 0 ]; then
    usage "$0"
  else
    fix-commit "$1"
  fi
}

fix-commit() {
  rev="$1"
  title=$(commit-title $rev)

  if dotf-confirm "Fixup $BLUE'$title'$RESET" yes; then

    dotf-bullet "Creating fixup commit... "
    git commit --fixup $rev
    dotf-info "done."

    if dotf-confirm "Autosquash" yes; then
      dotf-bullet "Autosquashing... "
      git rebase -i --autosquash $rev~1
      dotf-info "done."
    fi
  fi
}

commit-title() {
  git log -1 --pretty=%s $1
}

main "$@"
