#!/usr/bin/env fish

git config github.user elentok
git config user.name 'David Elentok'
git config user.email '3david@gmail.com'

set origin (git config remote.origin.url)

if string match -r -q "github.com:" $origin
    set new_origin (string replace -r "github.com:" "github.com-personal:" $origin)
else if string match -r -q "^https://github.com/" $origin
    set new_origin (string replace -r "^https://github.com/" "git@github.com-personal:" $origin)
else
    echo "no need to change"
    exit
end

echo "changing origin to $new_origin"
git config remote.origin.url $new_origin
