#!/usr/bin/env bash

set -euo pipefail

source "$DOTF/framework.sh"

function main() {
  if dotf-command-missing syncthing; then
    if dotf-is-linux; then
      install-on-linux
    fi
  fi
}

function install-on-linux() {

  # From https://apt.syncthing.net/

  # Add the release PGP keys:
  sudo mkdir -p /etc/apt/keyrings
  sudo curl -L -o /etc/apt/keyrings/syncthing-archive-keyring.gpg https://syncthing.net/release-key.gpg

  # Add the "stable" channel to your APT sources:
  echo "deb [signed-by=/etc/apt/keyrings/syncthing-archive-keyring.gpg] https://apt.syncthing.net/ syncthing stable" | sudo tee /etc/apt/sources.list.d/syncthing.list

  # Increase preference of Syncthing's packages ("pinning")
  printf "Package: *\nPin: origin apt.syncthing.net\nPin-Priority: 990\n" | sudo tee /etc/apt/preferences.d/syncthing.pref

  # Update and install syncthing:
  sudo apt-get update
  sudo apt-get install syncthing

  sudo systemctl enable syncthing@david
  sudo systemctl start syncthing@david
}

main
