#!/usr/bin/env bash

set -euo pipefail

source "$DOTF/framework"
source "$DOTF/core/scripts/lib/build-helper.sh"

version="$(dotf-trim < "$DOTF/core/tmux/VERSION")"
prepare_build tmux "$version" "$*"

git clone --depth 1 --branch "$version" https://github.com/tmux/tmux.git

cd tmux
sh autogen.sh
./configure
make prefix="$INSTALL_DIR"
make install prefix="$INSTALL_DIR"

install_symlinks bin/tmux
