#!/usr/bin/env bash

set -euo pipefail

PLUGIN_ROOT=~/.tmux/plugins

if [ "${1:-}" == "-f" ]; then
  rm -rf "$PLUGIN_ROOT"
fi

dfl mkdir ~/.tmux/plugins
dfl git-clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

dfl step start "Installing tpm plugins..."
~/.tmux/plugins/tpm/bin/install_plugins && dfl step success || dfl step error

# catppuccin
if [ ! -e ~/.tmux/plugins/catppuccin ]; then
  dfl mkdir ~/.tmux/plugins/catppuccin
  dfl git-clone -b v2.3.0 https://github.com/catppuccin/tmux.git ~/.tmux/plugins/catppuccin/tmux
fi
