#!/usr/bin/env bash

main() {
  if dfl os is-mac; then
    install-tmux-256color-terminfo
  fi
  dfl symlink "$DOTF/core/tmux/tmux.conf" ~/.tmux.conf

  $DOTF/core/tmux/install-plugins
}

# This function is based on https://github.com/tmux/tmux/issues/1257#issuecomment-581378716
install-tmux-256color-terminfo() {
  dfl step start "Setting up tmux-256color terminfo... "

  if has-tmux-256color-terminfo; then
    dfl step skip "already set up, skipping."
    return
  fi

  dfl pkgs brew install ncurses
  $BREW_HOME/opt/ncurses/bin/infocmp tmux-256color >/tmp/tmux-256color.info

  # This creates a complied entry in ~/.terminfo
  tic -xe tmux-256color /tmp/tmux-256color.info

  infocmp tmux-256color >/dev/null 2>&1 && dfl step success || dfl step error
}

has-tmux-256color-terminfo() {
  infocmp tmux-256color >/dev/null 2>&1
}

main "$@"
