#!/usr/bin/env bash

source "$(dirname "$0")/../../framework"

main() {
  install_tmux
  install_symlinks
  install_plugins
}

install_tmux() {
  dotf-bullet "Installing tmux... "
  if command_missing tmux; then
    PRIMARY=yes "$DOTF/core/tmux/build" && dotf-success "done."
  else
    version="$(dotf-trim < "$DOTF/core/tmux/VERSION")"
    current_version="$(tmux -V | head -1 | awk '{print $2}')"
    if [ "$current_version" == "$version" ]; then
      dotf-info "version $version already installed."
    else
      dotf-info "found $current_version, upgrading to $version..."
      PRIMARY=yes "$DOTF/core/tmux/build" && dotf-success "done."
    fi
  fi
}

install_symlinks() {
  symlink "$DOTF/core/tmux/tmux.conf" ~/.tmux.conf
}

install_plugins() {
  mkdir -p ~/.tmux/plugins
  git_clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
}

main "$@"
