#!/usr/bin/env bash

# Most of these settings where taken from Steve losh:
# http://stevelosh.com/blog/2012/10/a-modern-space-cadet/#controlescape

source `dirname $0`/../../framework

header "Karabiner Elements"

# brew_cask_install karabiner

symlink $DOTF/plugins/karabiner ~/.config/karabiner
