#!/bin/bash

# Most of these settings where taken from Steve losh:
# http://stevelosh.com/blog/2012/10/a-modern-space-cadet/#controlescape

source `dirname $0`/../../framework

header "Karabiner (previously KeyRemap4MacBook)"

brew_cask_install karabiner

bullet "Setting up"
source $DOTF/plugins/karabiner/settings
