#!/usr/bin/env bash

source "$DOTF/framework"

GITCONFIG="$HOME/.gitconfig"

main() {
  install_gitconfig
  setup_git_user
  setup_lazygit
}

install_gitconfig() {
  dotf-bullet "Installing $GITCONFIG... "
  if [ -e "$GITCONFIG" ] || [ -h "$GITCONFIG" ]; then
    fix_existing_gitconfig
  else
    write_to_gitconfig
    dotf-success 'done'
  fi
}

fix_existing_gitconfig() {
  if [ -h "$GITCONFIG" ]; then
    dotf-backup "$GITCONFIG"
    write_to_gitconfig
    dotf-success 'done'
  else
    if [ -n "$(grep "path = $DOTF/core/git/gitconfig" "$GITCONFIG")" ]; then
      dotf-info 'already installed'
    else
      echo >> "$GITCONFIG"
      write_to_gitconfig
      dotf-success 'done'
    fi
  fi
}

write_to_gitconfig() {
  if [ ! -e "$GITCONFIG" ]; then
    touch "$GITCONFIG"
  fi
  echo "[include]" >> "$GITCONFIG"
  echo "  path = $DOTF/core/git/gitconfig" >> "$GITCONFIG"
}

setup_git_user() {
  if [ -z "$(git config --global --includes user.name)" ]; then
    ask 'Git username?' git_username 'David Elentok'
    git config --global user.name "$git_username"
  fi

  if [ -z "$(git config --global --includes user.email)" ]; then
    ask 'Git email?' git_email '3david@gmail.com'
    git config --global user.email "$git_email"
  fi
}

function setup_lazygit() {
  local config_path="$HOME/.config/lazygit/config.yml"
  if dotf-is-mac; then
    config_path="$HOME/Library/Application Support/lazygit/config.yml"
  fi

  mkdir -p "$(dirname "$config_path")"

  dotf-symlink "$DOTF/core/git/lazygit.yml" "$config_path"
}

main "$@"
