#!/usr/bin/env bash

GITCONFIG="$HOME/.gitconfig"

main() {
  install-gitconfig
  setup_git_user
  setup_lazygit
}

install-gitconfig() {
  dfl step start "Installing $GITCONFIG... "
  if [ -e "$GITCONFIG" ] || [ -h "$GITCONFIG" ]; then
    fix-existing-gitconfig
  else
    write-to-gitconfig && dfl step success || dfl step error
  fi
}

fix-existing-gitconfig() {
  dfl step start "Fixing existing $GITCONFIG... "
  # -h == is symbolic link
  if [ -h "$GITCONFIG" ]; then
    dfl backup "$GITCONFIG"
    write-to-gitconfig && dfl step success || dfl step error
  else
    if [ -n "$(grep "path = $DOTF/core/git/gitconfig" "$GITCONFIG")" ]; then
      dfl step skip 'already fixed'
    else
      echo >>"$GITCONFIG"
      write-to-gitconfig && dfl step success || dfl step error
    fi
  fi
}

write-to-gitconfig() {
  if [ ! -e "$GITCONFIG" ]; then
    touch "$GITCONFIG"
  fi
  echo "[include]" >>"$GITCONFIG"
  echo "  path = $DOTF/core/git/gitconfig" >>"$GITCONFIG"
}

setup_git_user() {
  if [ -z "$(git config --global --includes user.name)" ]; then
    git_username="$(dfl ask 'Git username?' 'David Elentok')"
    git config --global user.name "$git_username"
  fi

  if [ -z "$(git config --global --includes user.email)" ]; then
    git_email="$(ask 'Git email?' '3david@gmail.com')"
    git config --global user.email "$git_email"
  fi
}

function setup_lazygit() {
  local config_path="$HOME/.config/lazygit/config.yml"
  if dfl os is-mac; then
    config_path="$HOME/Library/Application Support/lazygit/config.yml"
  fi

  dfl mkdir "$(dirname "$config_path")"

  dfl symlink "$DOTF/core/git/lazygit.yml" "$config_path"
}

main "$@"
