#!/usr/bin/env bash

set -euo pipefail

source "$DOTF/framework"

# make_dir ~/.config/kitty
# dotf-symlink "$DOTF/extra/kitty/kitty.conf" ~/.config/kitty/kitty.conf
dotf-symlink "$DOTF/extra/kitty" ~/.config/kitty
