#!/usr/bin/env bash

set -euo pipefail

source "$DOTF/framework"
source "$DOTF/scripts/build-helper"

prepare_build tmux 3.1b "$*"

if is_debian; then
  apt-fast-install libevent-dev libncurses5-dev libncursesw5-dev build-essential \
    pkg-config byacc autotools-dev automake
elif is_mac; then
  echo 'Unsupported platform'
  exit 1
fi

git clone --depth 1 --branch "$VERSION" https://github.com/tmux/tmux.git

cd tmux
sh autogen.sh
./configure
make prefix="$INSTALL_DIR"
make install prefix="$INSTALL_DIR"

install_symlinks bin/tmux
