#!/bin/bash

source `dirname $0`/../../framework

main() {
  header "tmux"

  install_tmux
  install_symlinks
  install_plugins
}

install_tmux() {
  if [ "$OS" == "mac" ]; then
    brew_install tmux
    brew_install reattach-to-user-namespace
    # for more info, see:
    #   http://robots.thoughtbot.com/post/19398560514/how-to-copy-and-paste-with-tmux-on-mac-os-x
  else
    if ! has_command tmux; then
      apt_install libevent-dev
      install_tgz --sudo \
        --install=no \
        'https://github.com/tmux/tmux/releases/download/2.1/tmux-2.1.tar.gz'
    fi
  fi
}

install_symlinks() {
  symlink "$DOTF/plugins/tmux/tmux.conf" ~/.tmux.conf
}

install_plugins() {
  mkdir -p ~/.tmux/plugins
  git_clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
}

main $*
