#!/usr/bin/env bash

source `dirname $0`/../../framework

main() {
  install_tmux
  install_symlinks
  install_plugins
}

install_tmux() {
  if is_mac; then
    brew_install tmux
    brew_install reattach-to-user-namespace
    # for more info, see:
    #   http://robots.thoughtbot.com/post/19398560514/how-to-copy-and-paste-with-tmux-on-mac-os-x

    brew unlink openssl
  else
    if command_missing tmux; then
      PRIMARY=yes "$DOTF/plugins/tmux/build"
    fi
  fi
}

install_symlinks() {
  symlink "$DOTF/plugins/tmux/tmux.conf" ~/.tmux.conf
}

install_plugins() {
  mkdir -p ~/.tmux/plugins
  git_clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
}

main $*
