#!/usr/bin/env bash

source "$DOTF/framework"

set -euo pipefail

if [ ! -e ~/.local/share/nvim/site/pack/packer/start/packer.nvim ]; then
  dotf-bullet "Cloning packer..."
  git clone --depth 1 https://github.com/wbthomason/packer.nvim \
    ~/.local/share/nvim/site/pack/packer/start/packer.nvim
fi

dotf-bullet "Running PackerSync..."
nvim --noplugin --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
