return {
  "WhoIsSethDaniel/mason-tool-installer.nvim",
  dependencies = {
    "mason-org/mason.nvim",
    opts = {},
  },
  lazy = false,
  opts = {
    ensure_installed = {
      "bash-language-server",
      "biome",
      "css-lsp",
      "docker-compose-language-service",
      "dockerfile-language-server",
      "dprint",
      "eslint_d",
      "fish-lsp",
      "gopls",
      "harper-ls",
      "html-lsp",
      "json-lsp",
      "lua-language-server",
      "marksman",
      "openscad-lsp",
      "prettierd",
      "pyright",
      "rust-analyzer",
      "stylua",
      "taplo",
      "ty",
      "vtsls",
      "yaml-language-server",
    },
  },
  keys = {
    {
      "<leader>om",
      ":Mason<cr>",
      desc = "Open Mason",
    },
  },
}
