#!/usr/bin/env bash

source "$DOTF/framework"

install-service "$DOTF/extra/web-diff-monitor/web-diff-monitor.service" system

systemctl daemon-reload
systemctl enable web-diff-monitor
systemctl start web-diff-monitor
