#!/bin/bash

(
  echo "======================================"

  source $HOME/.dotfiles/zsh/core.zsh

  setxkbmap -option 'grp:alt_shift_toggle' -option 'ctrl:nocaps'

  has_command cinnamon-settings-daemon && cinnamon-settings-daemon &
  has_command cinnamon-screensaver && cinnamon-screensaver &

  # Set the wallpaper
  if has_command feh; then
    (sleep 3; feh --bg-fill ~/.config/wallpaper.jpg) &
  fi

  # Network Management Applet
  has_command nm-applet && nm-applet &

  if has_command google-chrome-stable; then
    google-chrome-stable &
  elif has_command google-chrome; then
    google-chrome &
  fi

  if has_command x-terminal-emulator; then
    x-terminal-emulator &
  elif has_command i3-sensible-terminal; then
    i3-sensible-terminal &
  fi

  i3

) >> ~/.i3/log 2>&1
