#!/bin/bash

(
  echo "======================================"

  source $HOME/.dotfiles/zsh/core.zsh

  # Keyboard settings
  # This is required for some reason, or the next "setxkbmap" won't work.
  setxkbmap us

  # see /usr/share/X11/xkb/rules/base.lst for more options
  # setxkbmap -option 'grp:alt_shift_toggle' -option 'ctrl:nocaps'
  setxkbmap -option 'grp:menu_toggle' -option 'ctrl:nocaps'

  light-locker --lock-on-suspend --no-late-locking &
  xfce4-session &

  # Network Management Applet
  has_command nm-applet && nm-applet &

  if has_command google-chrome-stable; then
    google-chrome-stable &
  elif has_command google-chrome; then
    google-chrome &
  fi

  if has_command x-terminal-emulator; then
    x-terminal-emulator &
  elif has_command i3-sensible-terminal; then
    i3-sensible-terminal &
  fi

  xrdb ~/.Xresources

  if [ -e $DOTL/i3-session ]; then
    source $DOTL/i3-session
  fi

  i3

) >> ~/.i3/log 2>&1
