#!/bin/bash

source $DOTF/zsh/core.zsh

setxkbmap -option 'grp:alt_shift_toggle' -option 'ctrl:nocaps'

has_command cinnamon-settings-daemon && cinnamon-settings-daemon &

# Set the wallpaper
if has_command feh; then
  (sleep 3; feh --bg-fill ~/.config/wallpaper.jpg) &
fi

# Network Management Applet
has_command nm-applet && nm-applet &

google-chrome &
x-terminal-emulator &

i3
