#!/bin/bash

source $DOTF/framework

header "i3 Window Manager"

if command_missing i3; then
  pacman_install i3
fi

I3="$DOTF/plugins/i3"

mkdir -p ~/.i3
symlink "$I3/config" "$HOME/.i3/config"
symlink "$I3/i3status.conf" "$HOME/.i3/i3status.conf"
symlink "$I3/i3-session" "$HOME/.i3/i3-session"

sudo sh -c "cat $I3/i3-session.desktop | sed \"s#{HOME}#$HOME#\" > /usr/share/xsessions/i3-session.desktop"

# Make nemo (cinnamon's nautilus) not show desktop icons
gsettings set org.nemo.desktop show-desktop-icons false
