#!/bin/bash

source $DOTF/framework

main() {
  if [ $# -eq 0 ]; then
    usage
  else
    run "$@"
  fi
}

usage() {
  cat<<EOF

app-id

Usage:
  app-id <app-title>

EOF
}

run() {
  osascript -e "id of app \"$1\""
}

main "$@"
