#!/usr/bin/env bash

source $DOTF/framework

function main() {
  ROOT=$(find-parent-with .git tags Gemfile)

  header "Generating ctags for ${ROOT}"

  ctags -R --c++-kinds=+p --fields=+ilaS --extra=+q \
    --exclude=@$DOTF/nvim/ctags/ignore \
    $(project-exclude-arg $ROOT) \
    -f $ROOT/tags $ROOT
  if [ $? -eq 0 ]; then
    success "done (generated $(count-ctags) tags)."
  else
    error 'FAILED.'
  fi
}

function project-exclude-arg() {
  local root=$1

  if [ -e "$root/.ctagsignore" ]; then
    bullet "Loading $root/.ctagsignore\n" >&2
    echo "--exclude=@$root/.ctagsignore"
  fi
}

function count-ctags() {
  grep -v '^!' $ROOT/tags | wc -l | sed 's/\s*//g'
}

main "$@"
