#!/usr/bin/env bash

source $DOTF/framework

function main() {
  ROOT=$(find-parent-with .git tags Gemfile)

  header "Generating ctags for ${ROOT}"

  build_exclude_args

  bullet 'Generating... '

  ctags $EXCLUDE_ARGS -R --c++-kinds=+p --fields=+ilaS --extra=+q \
    --exclude=@$DOTF/nvim/ctagsignore \
    -f $ROOT/tags $ROOT
  if [ $? -eq 0 ]; then
    success "done (generated $(count-ctags) tags)."
  else
    error 'FAILED.'
  fi
}

function build_exclude_args() {
  EXCLUDE_ARGS=""

  if [ -e "$DOTF/nvim/ctagsignore" ]; then
    bullet "Loading $DOTF/nvim/ctagsignore\n"
    EXCLUDE_ARGS="--exclude=@$DOTF/nvim/ctagsignore"
  fi

  if [ -e "$ROOT/.ctagsignore" ]; then
    bullet "Loading $ROOT/.ctagsignore\n"
    EXCLUDE_ARGS="$EXCLUDE_ARGS --exclude=@$ROOT/.ctagsignore"
  fi
}

function count-ctags() {
  grep -v '^!' $ROOT/tags | wc -l | sed 's/\s*//g'
}

main "$@"
