#!/usr/bin/env zsh
#
# Usage:
#
#   clip copy
#   clip paste
#

source $DOTF/zsh/core.sh

# if [ -z "$DISPLAY" ]; then
#   export DISPLAY=":0"
# fi

main() {
  case "$1" in
    c|copy) copy;;
    p|paste) paste;;
    *) usage $DOTF/scripts/clip
  esac
}

copy() {
  if is_wsl; then
    win32yank -i
  elif has_command pbcopy; then
    pbcopy
  elif has_command xsel; then
    xsel --clipboard --input
  elif has_command xclip; then
    xclip -selection clipboard -in
  else
    echo 'Error: missing copy command (pbcopy, xclip or xsel)'
  fi
}

paste() {
  if is_wsl; then
    win32yank -o
  elif has_command pbpaste; then
    pbpaste
  elif has_command xclip; then
    xclip -selection clipboard -out
  elif has_command xsel; then
    xsel --clipboard --output
  else
    echo 'Error: missing copy command (pbpaste, xclip or xsel)'
  fi
}

main "$@"
