#!/usr/bin/env bash

if [ $# -eq 0 ]; then
  echo 'Usage:'
  echo ''
  echo '  coffeefy [file1] [file2] ...'
  echo ''
  echo 'To change the default extension (.js.coffee) set the EXT variable:'
  echo '  EXT=.coffee coffeefy file1.js'
fi

if [ "$EXT" == "" ]; then
  EXT=".js.coffee"
fi

for file in $@; do
  if [[ $file =~ \.js$ ]]; then
    new_file=${file/.js/$EXT}
    echo "Converting ${file}..."
    js2coffee "$file" > "$new_file"
    mv "$file" "${file}.original"
  fi
done
