#!/usr/bin/env python

import sys, re, color2css

#color2css = imp.load_source("color2css", os.path.dirname(__file__))

COLORS = {}
LINES = []

for line in sys.stdin:

    match = re.match(r"^\$([^:]*): *(#[a-fA-F0-9]{3,6});?$", line.strip())
    if match:
        var_name = match.group(1)
        color = match.group(2)
        color = color2css.normalize_color(color)
        if color in COLORS:
            color_name = COLORS[color]
        else:
            color_name = color2css.find_name(color)
            COLORS[color] = color_name

        LINES.append("$%s: $%s;" % (var_name, color_name))
    else:
        LINES.append(line.strip())

print "// colors:"
for color in COLORS.keys():
    print "$%s: %s;" % (COLORS[color], color)

print
print "// variables:"
for line in LINES:
    print line

