#!/usr/bin/env ruby

require "#{ENV['DOTF']}/framework.rb"
require 'ostruct'
require 'date'
require 'fileutils'
require 'pathname'

def main(source_dir, target_dir)
  puts 'Analyzing...'
  result = analyze(source_dir, target_dir)

  if result.added.empty?
    puts 'No new files'
  else
    puts "#{result.added.length} new file(s) (#{result.totals[:added] / 1024 / 1024}mb):"
    result.added.each { |added| puts "- #{added.target} (#{added.item.size_mb})" }
    puts
  end

  if result.modified.empty?
    puts 'No modified files'
  else
    puts "#{result.modified.length} new file(s) (#{result.totals[:modified] / 1024 / 1024}mb):"
    result.modified.each { |modified| puts "- #{modified.target} (#{modified.item.size_mb})" }
    puts
  end

  puts
  if confirm?('Copy files?', 'yes')
    copy(result.added, target_dir)
  end
end

def copy(added_files, target_dir)
  FileUtils.mkdir_p(target_dir)
  f = open(File.join(target_dir, 'copy.log'), 'a')
  f.puts "# Copy start (#{DateTime.now})"

  target_pathname = Pathname.new(target_dir)

  added_files.each do |added_file|
    target_rel_path = Pathname.new(added_file.target).relative_path_from(target_pathname)
    puts "Copying #{target_rel_path}..."
    FileUtils.mkdir_p(File.dirname(added_file.target))
    FileUtils.cp(added_file.item.filename, added_file.target)
    f.puts ">> #{target_rel_path}"
  end

  puts "Done."
  f.puts "# Copy complete (#{DateTime.now})"
ensure
  f.close() unless f.nil?
end

def analyze(source_dir, target_dir)
  result = OpenStruct.new(added: [], modified: [], totals: {})

  find_items(source_dir).each do |item|
    target = find_target(item, target_dir)
    status = identify_status(item, target)
    if status != :same
      result[status] << OpenStruct.new(item: item, target: target)
      result.totals[status] ||= 0
      result.totals[status] += item.size
    end
  end

  result
end

def identify_status(item, target)
  return :added unless File.exist?(target)

  if File.size(target) == item.size
    :same
  else
    :modified
  end
end

def find_items(dir)
  fields = %w(FileName DateTimeOriginal Model FocalLengthIn35mmFormat Aperture
              ExposureTime ISO)

  root = File.file?(dir) ? File.dirname(dir) : dir

  `exiftool "#{dir}" -recurse -ignoreMinorErrors \
    -dateFormat '%Y-%m-%d %H:%M' \
    -printFormat '$#{fields.join(',$')}' \
    2>/dev/null`
  .split("\n")
  .map { |raw| parse(raw, root) }
end

def parse(raw, dir)
  filename, date, model, focal_length, aperture, exposure_time, iso =
    raw.split(',')

  date = DateTime.parse(date)

  prefix = [
    date.strftime("%H%M"),
    File.basename(filename, '.*').downcase.gsub(/^_+/, '')
  ].join('-')

  if model
    model = model.downcase.sub('dmc-', '')
      .sub('canon eos ', '').sub(' digital', '')
  end

  if focal_length && focal_length.length > 0
    focal_length.sub!(' ', '')
  else
    focal_length = nil
  end

  if exposure_time
    if exposure_time.include?('/')
      exposure_time = "#{exposure_time.sub('1/', '')}hz"
    else
      exposure_time = "#{exposure_time}s"
    end
  end

  aperture = "f#{aperture.sub(/\.0+/, '')}" if aperture
  iso = "i#{iso}" if iso

  params = [
    model.downcase.sub('dmc-', '').sub('canon eos ', '').sub(' digital', ''),
    focal_length, exposure_time, aperture, iso].compact.join('-')

  Item.new(
    filename: File.join(dir, filename),
    ext:      File.extname(filename).downcase,
    date:     date,
    prefix:   prefix,
    params:   params
  )
end

class Item < OpenStruct
  def size
    return @size unless @size.nil?
    @size = File.size(filename)
  end

  def size_mb
    @size_mb ||= "#{size / 1024 / 1024}mb"
  end
end

TARGET_CACHE = {}

def find_target(item, target_dir)
  year_dir = File.join(target_dir, item.date.strftime('%Y'))
  day_dir = File.join(year_dir, item.date.strftime('%m-%d'))
  original_day_dir = day_dir

  if TARGET_CACHE[original_day_dir]
    day_dir = TARGET_CACHE[original_day_dir]
  else
    alternate = find_alternate_day_dir(item, year_dir, day_dir)
    day_dir = alternate if alternate
  end

  TARGET_CACHE[original_day_dir] = day_dir

  if Dir.exists?(day_dir)
    target = find_item_in_target_dir(item, day_dir)
    return target if target
  end

  File.join(day_dir, [item.prefix, item.params].join('-') + item.ext)
end

def find_alternate_day_dir(item, year_dir, day_dir)
  if Dir.exists?(year_dir)
    dir_with_desc = Dir["#{day_dir}*"].first
    if dir_with_desc
      day_dir = dir_with_desc
    else
      dir = find_multi_day_target(item, year_dir)
      day_dir = dir if dir
    end
  end
end

def find_multi_day_target(item, year_dir)
  year = item.date.strftime('%Y')

  Dir[File.join(year_dir, '*')].each do |dir|
    dates = /^[\d\-_]+/.match(File.basename(dir))[0]
    from, to = dates.split('_')
    next unless to

    from_month, _ = from.split('-')
    from = DateTime.parse("#{year}-#{from}")
    if to.include? '-'
      to = DateTime.parse("#{year}-#{to} 23:59:59")
    else
      to = DateTime.parse("#{year}-#{from_month}-#{to} 23:59:59")
    end

    if item.date >= from && item.date <= to
      days = (item.date - from).to_i + 1
      return File.join(dir, "day#{days.to_s.rjust(2, '0')}")
    end
  end

  nil
end

def find_item_in_target_dir(item, dir)
  Dir[File.join(dir, "#{item.prefix}*#{item.ext}")].sort.first
end

main(*ARGV) if __FILE__ == $PROGRAM_NAME
