#!/bin/bash
#
# ddd - dd with progress report
#
# Usage:
#   ddd <input> <output>

source $DOTF/framework

main() {
  check_pv
  if [ $# -lt 2 ]; then
    usage "$0"
  else
    echo
    echo "Copying from $1"
    echo "          to $2"
    echo
    sudo sh -c "dd if='$1' | pv | dd of='$2'"
  fi
}

check_pv() {
  if ! has_command pv; then
    install_package --apt=pv --brew=pv --pacman=pv
  fi
}

main "$@"
