#!/bin/bash
#
# Kills docker containers (with "rm -f")
#
# Usage:
#
# dockill [pattern]

docker ps | grep "$1" | awk '{print $1}' | grep -v CONTAINER | while read id; do
  echo "Killing container ${id}..."
  docker rm -f ${id}
done
