#!/usr/bin/env bash
#
# Cleans up zombie containers and images
#
echo 'Cleaning containers...'
containers=$(docker ps -qa --no-trunc --filter "status=exited")
[ -n "$containers" ] && docker rm $containers

echo 'Cleaning images...'
images=$(docker images -q --no-trunc --filter "dangling=true")
[ -n "$images" ] && docker rmi $images

echo 'Cleaning volumes...'
volumes=$(docker volume ls -q --filter "dangling=true")
[ -n "$volumes" ] && docker volume rm $volumes
