#!/bin/bash
#
# Cleans up zombie containers and images
#
containers=$(docker ps -qa --no-trunc --filter "status=exited")
[ -n "$containers" ] && docker rm $containers

images=$(docker images -q --no-trunc --filter "dangling=true")
[ -n "$images" ] && docker rmi $images
