#!/usr/bin/env bash
#
# Usage:
#
#   dotf-component <component>...
#

source "$(dirname "$0")/../framework"

main() {
  if [ $# -eq 0 ]; then
    usage "$0"
    exit 1
  fi

  while [ $# -gt 0 ]; do
    install-component "$1"
    shift
  done
}

install-component() {
  local name="$1"
  local filename
  filename="$(find-component "$name")"

  if [ -z "$filename" ]; then
    dotf-error "Cannot find component '$name'"
    exit 1
  fi

  dotf-header h2 "[dotf-component] Setting up: $name..."
  benchmark-start "$name"
  $filename

  echo
  echo "=> component '$name' installed in $(benchmark-stop "$name")"
}

find-component() {
  local filenames=(
    "$DOTF/$name/install"
    "$DOTF/core/$name/install"
    "$DOTF/core/$name"
    "$DOTF/extra/$name/install"
    "$DOTF/extra/$name"
    "$DOTL/plugins/$name/install"
    "$DOTL/plugins/$name"
  )

  for filename in "${filenames[@]}"; do
    if [ -x "$filename" ]; then
      echo "$filename"
      return 0
    fi
  done

  return 1
}

main "$@"
