#!/usr/bin/env bash

set -euo pipefail

for terminal in alacritty x-terminal-emulator urxvt rxvt termit terminator Eterm aterm uxterm xterm gnome-terminal roxterm xfce4-terminal termite lxterminal mate-terminal terminology st qterminal lilyterm tilix terminix konsole kitty guake tilda hyper; do
  if command -v "$terminal" > /dev/null 2>&1; then
    exec "$terminal" "$@"
  fi
done
