#!/usr/bin/env bash

set -euo pipefail

source "$(dirname "$0")/../framework"

benchmark-start

main() {
  cd "$DOTF"

  dotf-header h1 "Setting up dotfiles..."

  dotf-pkgs install apt

  dotf-header h2 "[dotf-install] Updating git submodules..."
  git submodule update --init --recursive

  dotf-bullet "Updating pip..."
  update-pip

  dotf-bullet "Installing pip packages..."
  dotf-pkgs install pip

  dotf-header h2 "[dotf-install] Installing Github packages..."
  dotf-github install

  dotf-component nodejs
  dotf-pkgs install npm
  dotf-component git zsh nvim ripgrep tig bash tmux vifm

  if is_mac; then
    dotf-component osx-tuning iterm
  fi

  dotf-header h2 '[dotf-install] Running npm install...'
  npm install

  show-done
}

update-pip() {
  if command_missing pip3; then
    if is_termux; then
      apt-fast-install python
    elif is_debian; then
      apt-fast-install python3 python3-pip
    elif is_mac; then
      brew_install python3
    else
      echo 'TODO: support installing pip3'
      exit 1
    fi
  fi

  pip3 install pip --upgrade --user
}

show-done() {
  echo -e "$GREEN=========================="
  echo "Done ($(benchmark-stop))"
  echo -e "==========================$RESET"
}

main "$@"
