#!/usr/bin/env bash
#
# Usage:
#
#   dotf-component <component>...
#

source "$DOTF/framework"

main() {
  if [ $# -eq 0 ]; then
    usage "$0"
    exit 1
  fi

  while [ $# -gt 0 ]; do
    install-component "$1"
    shift
  done
}

install-component() {
  local filename
  filename="$(find-component "$1")"

  if [ -z "$filename" ]; then
    error "Cannot find component '$1'"
    exit 1
  fi

  header "$1"
  benchmark-start "$1"
  $filename

  echo
  echo "=> component '$1' installed in $(benchmark-stop "$1")"
}

find-component() {
  local filenames=(
    "$DOTF/$1/install"
    "$DOTF/core/$1/install"
    "$DOTF/core/$1"
    "$DOTF/extra/$1/install"
    "$DOTF/extra/$1"
    "$DOTL/plugins/$1/install"
    "$DOTL/plugins/$1"
  )

  for filename in "${filenames[@]}"; do
    if [ -x "$filename" ]; then
      echo "$filename"
      return 0
    fi
  done

  return 1
}

main "$@"
