#!/usr/bin/env bash

source $DOTF/framework

header 'General'
echo "Plugins: $(command ls -1 $DOTF/plugins | wc -l)"

header 'Scripts'
find $DOTF/scripts -maxdepth 1 -type f \
  | xargs head -1 --quiet \
  | sort | uniq -c | sort -nr

