#!/usr/bin/env bash

set -euo pipefail

source "$(dirname "$0")/../framework"

benchmark-start

main() {
  cd "$DOTF"

  title "Starting DOTF INSTALL"

  header "Installing apt packages..."
  dotf-pkgs install apt

  header "Updating git submodules..."
  git submodule update --init --recursive

  header "Install pip packages..."

  bullet "Updating pip..."
  update-pip

  bullet "Installing pip packages..."
  dotf-pkgs install pip

  header "Installing Github packages..."
  dotf-github install

  dotf-component nodejs
  dotf-pkgs install npm
  dotf-component git zsh nvim ripgrep tig bash tmux vifm

  if is_mac; then
    dotf-component osx-tuning iterm
  fi

  header 'npm install'
  npm install

  show-done
}

update-pip() {
  if command_missing pip3; then
    if is_termux; then
      apt-fast-install python
    elif is_debian; then
      apt-fast-install python3 python3-pip
    elif is_mac; then
      brew_install python3
    else
      echo 'TODO: support installing pip3'
      exit 1
    fi
  fi

  pip3 install pip --upgrade --user
}

show-done() {
  echo -e "$GREEN=========================="
  echo "Done ($(benchmark-stop))"
  echo -e "==========================$RESET"
}

main "$@"
