#!/usr/bin/env bash

source "$DOTF/framework"

header 'General'
echo "Dotfiles Plugins: $(command ls -1 "$DOTF/plugins" | wc -l)"
echo "Neovim Plugins:   $(grep -c " use" "$DOTF/nvim/lua/elentok/plugins.lua")"

header 'Scripts'
find "$DOTF/scripts" -maxdepth 1 -type f -exec head -1 '{}' \; \
  | sort | uniq -c | sort -nr

