#!/usr/bin/env bash
#
# Elentok's dotfiles
#
# Usage:
#
#   dotf list                         - lists all plugins
#   dotf install                      - installs all plugins
#   dotf install [plugin] [plugin]... - install specific plugins
#   dotf update                       - pulls from git and reruns install
#   dotf export-vim                   - exports vim config to .tar.gz
#

source `dirname $0`/../framework

main() {
  cmd="${1:-}"
  shift || true
  case "$cmd" in
  list | l)
    list_plugins
    ;;
  install | i)
    install "$@"
    ;;
  update | u)
    update
    ;;
  export-vim)
    export_vim
    ;;
  *)
    usage "$0"
    ;;
  esac
}

list_plugins() {
  (
    echo vim
    echo zsh
    /bin/ls -1 $DOTF/plugins
    /bin/ls -1 $DOTL/plugins 2>/dev/null
  ) | sort
}

install() {
  if [ $# -eq 0 ]; then
    dotf-install
  else
    dotf-plugin "$@"
  fi
}

update() {
  header "Updating dotfiles"
  cd $DOTF

  bullet "Pulling changes... "
  old_head=`git rev-parse HEAD`
  git pull
  new_head=`git rev-parse HEAD`

  if [ "$old_head" != "$new_head" ]; then
    echo -e "\nPulled the following changes:"
    git changelog ${old_head}..${new_head}

    echo -ne "\nPress any key to run the installer..."
    read -n 1

    if is_mac; then
      bullet 'Updating brew... '
      brew update
    fi

    dotf-install
  fi
}

export_vim() {
  tar czvf vim-$(date +%Y%m%d).tar.gz \
    --exclude 'YouCompleteMe' \
    --exclude 'node_modules' \
    --exclude '.git' \
    vim framework
}

main "$@"
