#!/usr/bin/env python3

import sys

from lib import package_manager


def main():
    manager = package_manager.PackageManager()

    command = sys.argv[1] if len(sys.argv) > 1 else 'list'
    if command == 'list':
        manager.list()
    elif command == 'update':
        manager.update()
    else:
        print('Usage: dotf-pkgs <list|update>')


main()
