#!/usr/bin/env bash

source `dirname $0`/../framework

benchmark-start

main() {
  mkdir -p ~/bin

  cd $DOTF

  git submodule update --init --recursive
  update-pip
  dotf-plugin tools nodejs git zsh nvim ripgrep tig bash tmux ruby

  gui-plugins

  npm install

  show-done
}

update-pip() {
  if missing_command pip3; then
    if is_debian; then
      apt_install python3 python3-pip
    elif is_mac; then
      brew_install python3
    else
      echo 'TODO: support installing pip3'
      exit 1
    fi
  fi

  pip3 install pip --upgrade --user
}

gui-plugins() {
  if is_mac; then
    dotf-plugin osx-tuning iterm
  elif is_linux; then
    if [ "$HAS_GUI" = 'yes' ]; then
      dotf-plugin linux-gui-apps
    fi
  fi
}

show-done() {
  echo -e "$GREEN=========================="
  echo "Done ($(benchmark-stop))"
  echo -e "==========================$RESET"
}


main "$@"
