#!/usr/bin/env bash

main() {
  file="$(select-file)"
  $EDITOR $file
  echo $file
}

select-file() {
  list-files | fzf
}

list-files() {
  ls -1 $DOTF/zsh/*.{z,}sh
  ls -1 $DOTL/zsh/*.{z,}zsh
}

main
