#!/usr/bin/env bash

# Setup the buttons on an evoluent mouse

name="$(xinput list --name-only | grep -i evoluent)"

# Original Setup:
# Left:        1
# Middle:      3  ==> change to 2
# Right:       8  ==> change to 3
# Wheel Up:    4
# Wheel Down:  5
# Wheel Click: 2
# Side button: 9

xinput set-button-map "$name" 1 2 2 4 5 6 7 3 9 10 11 12 13
