#!/usr/bin/env ruby

require "#{ENV['DOTF']}/framework.rb"
require 'fileutils'

USAGE = "
geographic utils

geo bbox-to-polygon <bbox>
"

class CLI < BaseCLI
  def usage
    puts USAGE
  end

  def bbox_to_polygon(bbox)
    south_west, north_east = parse_bbox(bbox)
    south_east = LatLng.new(lng: north_east.lng, lat: south_west.lat)
    north_west = LatLng.new(lat: north_east.lat, lng: south_west.lng)

    puts [south_west, south_east, north_east, north_west, south_west]
      .map { |latlng| [latlng.lat, latlng.lng] }
      .flatten
      .join(',')
  end

  private

  def parse_bbox(bbox)
    bbox.split(',').each_slice(2).map do |lng, lat|
      LatLng.new(lng: lng, lat: lat)
    end
  end
end

class LatLng
  attr_reader :lat, :lng

  def initialize(options = {})
    @lat = options[:lat]
    @lng = options[:lng]
  end

  def to_s
    "{lat: #{@lat}, lng: #{@lng}}"
  end
end

CLI.new.start
