#!/usr/bin/env bash

source $DOTF/framework

default_branch=master
if [ -n "$(git all-branches | grep '^develop$')" ]; then
  default_branch=develop
fi

branch_to_pull=${1:-$default_branch}

branch=$(git my-branch)

echo -e "${BLUE}➜ Switching to ${branch_to_pull} branch...$RESET"
git checkout ${branch_to_pull}
echo

echo -e "${BLUE}➜ Pulling ${branch_to_pull} branch...$RESET"
git pull
echo

echo -e "${BLUE}➜ Switching back to ${branch} branch...$RESET"
git checkout $branch
echo

success 'DONE'
