#!/bin/bash

main() {
  if [ "$1" != "" ]; then
    changelog $1
  else
    usage
  fi
}

usage() {
  echo
  echo "Usage:"
  echo
  echo "  git changelog [commit or revision range]"
  echo
}

changelog() {
  if [[ "$1" == *..* ]]; then
    range="$1"
  else
    range="${1}~1..HEAD"
  fi

  git_log "$range" | while read line; do
    echo "* $line"
  done
}

git_log() {
  range="$1"
  git log --pretty=format:%s "$range"
}

main $@
