#!/usr/bin/env bash

set -e

source $DOTF/framework

main() {
  title 'Git Sync'

  commit-if-needed
  pull
  push
  success 'done'
}

commit-if-needed() {
  bullet 'Checking for changes... '
  if git-repo-is-dirty; then
    echo
    commit
  else
    info 'no changes'
  fi
}

commit() {
  bullet "Commiting changes...\n"
  date=$(date +%Y-%m-%d\ %H:%M)
  host=$(short-hostname)
  git add --all
  git commit -m "Update $date ($host)"
  echo
}

pull() {
  bullet "Pulling changes... "
  git pull --rebase
}

push() {
  bullet "Pushing changes... "
  git push
}

main "$@"
