#!/bin/bash
#
# Git Pull Other Branch
#
# Usage:
#
#   git plo <branch>

branch="$1"

if [ -z "$branch" ]; then
  usage $0
  exit 1
fi

prev_branch="$(git my-branch)"
git checkout $branch
git pull
git checkout
git checkout $prev_branch
