#!/usr/bin/env bash
#
# Creates a fixup commit and rebases it
#
# Usage:
#
# git fix <revision>
#

source $DOTF/framework

main() {
  if [ $# -eq 0 ]; then
    usage "$0"
  else
    fix-commit "$1"
  fi
}

fix-commit() {
  rev="$1"
  title=$(commit-title $rev)

  if confirm "Fixup $BLUE'$title'$RESET" yes; then

    bullet "Creating fixup commit... "
    git commit --fixup $rev
    info "done."

    if confirm "Autosquash" yes; then
      bullet "Autosquashing... "
      git rebase -i --autosquash $rev~1
      info "done."
    fi
  fi
}

commit-title() {
  git log -1 --pretty=%s $1
}

main "$@"
