#!/usr/bin/env bash

remote='noreview'
branch=$(git rev-parse --abbrev-ref HEAD)

read -p "Push $branch to $remote? [Y/n] " yesno

echo

if [[ "$yesno" =~ [nN] ]]; then
  echo "Aborted."
else
  echo "Pushing ${branch} to ${remote}..."
  git push $remote $branch $*
fi

