#!/usr/bin/env ruby

def main
  if ARGV.length > 0
    changelog ARGV[0]
  else
    usage
  end
end

def usage
  puts <<EOF
  Usage:

    git changelog [commit or revision range]
EOF
end

def changelog(hash)
  if hash =~ /\.\./
    range="#{hash}"
  else
    range="#{hash}~1..HEAD"
  end

  `git log --pretty=%h #{range}`.each_line do |line|
    puts Commit.new(line.strip).format
  end
end

def format_commit(hash)
end

class Commit
  def initialize(hash)
    @hash = hash
  end

  def title
    @title ||= `git log -1 --pretty=%s #{@hash}`.strip
  end

  def issues
    @issues ||= find_issues
  end

  def format
    [
      "* #{title}",
      issues.length == 0 ? nil : "(#{issues.join(', ')})"
    ].compact.join(' ')
  end

  private

  def find_issues
    `git log -1 --pretty=%B #{@hash}`.scan(/b\/[0-9]+/)
  end
end

main
