#!/usr/bin/env bash

source $DOTF/framework

branch_to_pull=${1:-develop}

branch=$(git my-branch)

echo -e "${BLUE}➜ Switching to ${branch_to_pull} branch...$RESET"
git checkout ${branch_to_pull}
echo

echo -e "${BLUE}➜ Pulling ${branch_to_pull} branch...$RESET"
git pull
echo

echo -e "${BLUE}➜ Switching back to ${branch} branch...$RESET"
git checkout $branch
echo

success 'DONE'

