#!/bin/bash

export BLUE="\033[34m"
export RED="\033[31m"
export RESET="\033[0m"

bounce() {
  git diff $* | grep --line-number 'console\.'
}

git diff --name-only | while read filename; do
  result=`bounce "$filename"`
  if [[ "$result" != "" ]]; then
    echo -e "${BLUE}${filename}${RESET}"
    echo -e "${RED}${result}${RESET}"
  fi
done
