#!/bin/bash
#
# Usage:
#
#   git commit-order [revision range]

main() {
  if [ "$1" != "" ]; then
    commit-order $1
  else
    usage "$0"
  fi
}

commit-order() {
  i=1
  git_log "$1" | reverse_lines | while read line; do
    echo "$i. $line"
    i=$(($i+1))
  done
}

git_log() {
  range="$1"
  git log --pretty=format:%s "$range"
}

reverse_lines() {
  sed '1!G;h;$!d'
}

main $@
