#!/usr/bin/env ruby

HELP_FILENAME = "#{ENV['DOTF']}/docs/help.md"

module HelpReader

  def self.read_sections(filename, query = nil)
    sections = []

    File.open(filename, 'r') do |f|
      section = ""

      f.each_line do |line|
        if starts_section?(line)
          add_section!(sections, section, query)
          section = line
        else
          section += line
        end
      end

      add_section!(sections, section, query)
    end

    sections
  end
  
private
  def self.starts_section?(line)
    line =~ /^\#/
  end

  def self.add_section!(sections, section, query)
    return if section.strip.empty?
    if query.nil?
      sections << section
    elsif matches?(section, query)
      sections << SectionRenderer.render(section, query) 
    end
  end

  def self.matches?(section, text)
    section =~ Regexp.new(text, 'i')
  end

end

module SectionRenderer
  GREEN = "\e[32m"
  DEFAULT = "\e[0m"
  BOLD_ON = "\033[1m"
  BOLD_OFF = "\033[22m"

  def self.render(section, query)
    highlight = "#{GREEN}#{BOLD_ON}#{query}#{DEFAULT}#{BOLD_OFF}"
    section.gsub Regexp.new(query, 'i'), highlight
  end
end

def main
  query = nil
  query = ARGV[0] if ARGV.length > 0

  if query == 'e'
    system("vim #{HELP_FILENAME} < `tty` > `tty`")
  else
    puts HelpReader.read_sections(HELP_FILENAME, query)
  end
end

if __FILE__ == $0
  main
end
