#!/usr/bin/env python3

import sys


def main():
    if len(sys.argv) < 2:
        usage()
    else:
        hex2rgb(sys.argv[1])


def usage():
    print(("Usage:"
           ""
           "  hex2rgb abcdef"))


def hex2rgb(hex_value):
    red = int(hex_value[0:2], 16)
    green = int(hex_value[2:4], 16)
    blue = int(hex_value[4:6], 16)
    print(f'({red},{green},{blue})')


if __name__ == "__main__":
    main()
