#!/usr/bin/env bash

OPTIONS="
Appearance (xfce4-appearance-settings)
Sound (pavucontrol)
Login Screen (gksu lightdm-gtk-greeter-settings)
Session (xfce4-session-settings)
Keyboard (xfce4-keyboard-settings)
Mouse (xfce4-mouse-settings)
Power Management (xfce4-power-manager-settings)
Monitors (xfce4-display-settings)"

# -i: case insensitive
result="$(echo "$OPTIONS" | grep -v '^$' | rofi -dmenu -i -p "> ")"

if [ -z "$result" ]; then
  exit 1
fi

cmd="$(echo $result | sed -E 's/^.*\((.*)\)/\1/')"
$cmd
