#!/usr/bin/env bash

ips-linux-arch() {
  ip addr show | grep 'inet ' | awk '{print $2}' | sed -E 's#/[0-9]+##'
}

ips-mac-() {
  ifconfig | grep 'inet ' | awk '{print $2}'
}

ips() {
  ips-$OS-$DISTRO
}

ips
