#!/bin/bash

source $DOTF/framework

run_app() {
  bullet "Starting $1... "
  if is_running "$1"; then
    info 'already started.'
  else
    open /Applications/$1.app
  fi
}

run_command --bg 'Music Player Daemon' mpd
run_command --sudo 'Nginx' nginx

bullet "Add ssh key... "
if [ -z "$(ssh-add -l)" ]; then
  ssh-add
else
  info 'already added.'
fi

