#!/usr/bin/env node

const fs = require("fs")
const { execSync } = require("child_process")

function main() {
  if (process.argv.length < 4) {
    usage()
    process.exit(1)
  }

  const to = process.argv[2]
  const subject = process.argv[3]

  const body = process.argv[4] || getBodyFromStdin()

  let url = `mailto:${to}?subject=${encodeURIComponent(subject)}`
  if (body != null) {
    url = `${url}&body=${encodeURIComponent(body.replace(/\\n/g, "\r\n"))}`
  }

  execSync(`open '${url}'`)
}

function usage() {
  console.info(`
Usage:

  mailto <recipient> <subject> [body]`)
}

function getBodyFromStdin() {
  try {
    return fs.readFileSync(process.stdin.fd).toString().trim()
  } catch (e) {
    console.error("ERROR", e)
    return null
  }
}

main()
