#!/usr/bin/env node

const axios = require("axios");
const $ = require("cheerio");
const chalk = require("chalk");

// Keep colors when piping to head/less/...
chalk.enabled = true;

function main() {
  const url = process.argv[2];

  if (url == null || url.length === 0) {
    console.info("Usage:\n\n  meta <url>\n");
    process.exit(1);
  }

  axios
    .get(url)
    .then(response => {
      const $html = $.load(response.data);
      $html("meta").toArray().forEach(meta => {
        printMeta(meta);
      });
    })
    .catch(err => {
      console.error("ERROR: ", err);
    });
}

function printMeta(meta) {
  process.stdout.write(chalk.gray("<meta "));
  Object.keys(meta.attribs).forEach(key => {
    const value = meta.attribs[key];
    process.stdout.write(
      [
        chalk.green(key),
        chalk.gray(`="`),
        chalk.blue(value),
        chalk.gray(`"`),
        " "
      ].join("")
    );
    // process.stdout.write(`${chalk.green(key)}="${chalk.blue(value)}" `);
  });
  process.stdout.write(chalk.gray("/>\n"));
}

main();
