#!/usr/bin/env bash

source "$DOTF/framework"

dotf-header h1 'Good morning :-)'

dotf-header h2 'Setting up ssh agent...'
agent setup

dotf-header h2 'Add ssh key...'
ssh-add

if [ -e "$DOTL/scripts/morning-local" ]; then
  "$DOTL/scripts/morning-local"
fi

dotf-header h2 'Updating dotlocal...'
cd ~/.dotlocal && git pull

dotf-header h2 'Updating dotfiles...'
dotf update

if [ -e "$HOME/notes" ]; then
  dotf-header h2 'Syncing notes...'
  (cd ~/notes && git sync)
fi

dotf-header h1 'Have a wonderful day :-)'
