#!/usr/bin/env bash

source $DOTF/framework

header 'Setting up ssh agent'
agent setup

header 'Add ssh key'
ssh-add

if [ -e $DOTL/scripts/morning-local ]; then
  $DOTL/scripts/morning-local
fi

header 'Updating dotlocal'
cd ~/.dotlocal && git pull

header 'Updating dotfiles'
dotf update
