#!/bin/bash

music_root="$HOME/Music"
deleted_songs="/media/Stuff/Music-Deleted/"

mkdir -p $deleted_songs

song_title=`mpc current --format '[%artist% - %title%]'`
song_filename=`mpc current --format '[%file%]'`

echo "Song Title:    $song_title"
echo "Song Filename: $song_filename"
read -p "Delete? (y/n)?"
if [ $REPLY == "y" ]; then
  echo "Deleting..."
  cd "$music_root"
  mv "$song_filename" "$deleted_songs"
  echo "Deleted"
  mpc next
  mpc update
fi
