#!/bin/bash
#
# Creates a new script in ~/.dotfiles/scripts
#
# Usage:
#   newsh <filename> [optional:bash/zsh]

main() {
  if [[ "$1" == "" ]]; then
    usage "$0"
  else
    create $*
  fi
}

create() {
  file=$1
  shell=${2-bash}
  echo "#!/bin/$shell" > "$file"
  chmod +x "$file"
  vim "$file"
}

main $*
