#!/usr/bin/env bash
#
# Usage:
#
#   nextjs-deployer deploy <appname> <host>
#   nextjs-deployer pack [optional: appname]
#   nextjs-deployer unpack <file.tar.gz>

set -euo pipefail

NEXT_APPS_ROOT="/opt/next-apps"
NODE_ROOT="/opt/n"
NPM="$NODE_ROOT/bin/npm"

function main() {
  local cmd="${1:-}"
  shift || true

  case "$cmd" in
    deploy)
      deploy "$@"
      ;;
    pack)
      pack "$@"
      ;;
    unpack)
      unpack "$@"
      ;;
    *)
      usage "$0"
      ;;
  esac
}


function deploy() {
  local name="$1"
  local host="$2"

  # 1. Pack
  pack "$name"

  # 2. Upload
  ssh "$host" rm -f "/tmp/${name}.tar.gz"
  scp "${name}.tar.gz" "${host}:/tmp"

  # 3. Unpack
  ssh "$host" nextjs-deployer unpack "/tmp/${name}.tar.gz"
}

function pack() {
  local name
  if [ $# -gt 0 ]; then
    name="$1"
  else
    name="$(basename "$PWD")"
  fi

  npm run build

  tgz_file="$name.tar.gz"
  if [ -e "$tgz_file" ]; then
    rm -rf "$tgz_file"
  fi
  tar czvf "$tgz_file" package.json package-lock.json .next

  echo
  echo "Created $tgz_file."
}

function unpack() {
  lovsl tgz_file
  tgz_file="$(realpath "$1")"

  local tgz_basename
  tgz_basename="$(basename "$tgz_file")"
  local name="${tgz_basename/.tar.gz/}"

  sudo mkdir -p "$NEXT_APPS_ROOT"
  sudo chgrp nodejs "$NEXT_APPS_ROOT"
  cd "$NEXT_APPS_ROOT"
  if [ -e "$name" ]; then
    rm -rf "$name.old"
    mv "$name" "$name.old"
  fi

  mkdir "$name"
  cd "$name"
  sudo tar xzvf "$tgz_file"
  sudo "$NPM" install --production
}

main "$@"
