#!/usr/bin/env bash

source $DOTF/framework

if [ "${1:-}" == "--local" ]; then
  shift
  NODE_MODULES="$(pwd)/node_modules"

  function install() {
    npm install $NPM_ARGS $*
  }
else
  NODE_MODULES="$(cd "$(dirname $(which node))/../lib/node_modules" && pwd)"

  function install() {
    if is-user-nodejs; then
      sudo npm install -g $NPM_ARGS $*
    else
      npm install -g $NPM_ARGS$ *
    fi
  }
fi

function main() {
  bullet "Installing npm packages: $@..."
  die-if-npm-missing

  local missing=$(find-missing-packages "$@")
  if [ -z "$missing" ]; then
    info " already installed."
  else
    install $missing
  fi
}

function die-if-npm-missing() {
  if ! has_command npm; then
    error "npm is not installed, skipping"
    exit 1
  fi
}

function find-missing-packages() {
  for pkg in $*; do
    if [ ! -d "$NODE_MODULES/$pkg" ]; then
      printf "$pkg "
    fi
  done
}

is-user-nodejs() {
  [ "$(file-owner $(which node))" = "$(whoami)" ]
}

main "$@"
