#!/usr/bin/env bash

set -euo pipefail

cd

for dir in .dotfiles/core/nvim .dotlocal/nvim; do
  if [ ! -e "$dir" ]; then
    continue
  fi

  find "$dir" -name '*.vim' | sed 's/^\.\///'
  find "$dir" -name '*.lua' | sed 's/^\.\///'
done
