#!/usr/bin/env bash

cd

for dir in .dotfiles/nvim .dotlocal/nvim; do
  if [ ! -e "$dir" ]; then
    continue
  fi

  find "$dir" -name '*.vim' | sed 's/^\.\///'
  find "$dir" -name '*.lua' | sed 's/^\.\///'
done
