#!/bin/bash
#
# osx-apps
#
# Usage:
#   osx-apps list
#   osx-apps id [app-title]

source $DOTF/framework

main() {
  cmd="$1"
  shift

  case "$cmd" in
    list | l)
      list
      ;;
    id)
      find-id "$@"
      ;;
    *)
      usage "$0"
      ;;
  esac
}

list() {
  list_osascript | osascript | sed 's/, /\n/g' | sort
}

list_osascript() {
  cat <<EOF
tell application "System Events"
  name of every process where background only is false
end tell
EOF
}

find-id() {
  local name="$1"
  if [ -z "$name" ]; then
    name="$(list | fzf)"
  fi

  id=$(osascript -e "id of app \"$name\"")
  echo $id | pbcopy
  echo "$id (copied to clipboard)"
}

main "$@"
