#!/bin/bash

if [ $# -eq 0 ]; then
  echo "Usage:"
  echo
  echo "  pdfmerge {output.pdf} {input1.pdf} {input2.pdf} ..."
else
  output=$1
  shift

  echo "Merging"
  for file in "$@"; do
    echo "  $file"
  done
  echo "  => into $output"

  command gs -dBATCH -dNOPAUSE -q -sDEVICE=pdfwrite -sOutputFile=$output "$@"
fi
