#!/bin/bash

main() {
  if [ $# -eq 0 ]; then
    usage
  else
    find_pid "$1"
  fi
}

find_pid() {
  results=$(ps axc | awk '{print $1" "$5}' | grep " $1\$")
  [ ! -z "$results" ] && echo "$results" | cut -d' ' -f1
}

usage() {
  echo
  echo "Usage:"
  echo
  echo "  pidof {process-name}"
  echo
}

main $*
