#!/usr/bin/env bash

source $DOTF/framework

PIP='pip'
if has_command 'pip3'; then
  PIP='pip3'
fi

main() {
  bullet "Installing pip3 packages $*... "

  die-if-pip-missing
  INSTALLED="$($PIP list)"
  local missing=$(find-missing-packages "$@")

  echo "MISSING: [$missing]"

  if [ -z "$missing" ]; then
    info " already installed."
  else
    $PIP install $missing --user $*
  fi
}

function die-if-pip-missing() {
  if ! has_command $PIP; then
    error "pip is not installed, skipping"
    exit 1
  fi
}

function find-missing-packages() {
  for pkg in $*; do
    if ! has-package $pkg; then
      printf "$pkg "
    fi
  done
}

has-package() {
  # echo "$INSTALLED" | grep \"^$1\b\" > /dev/null
  [ "$(echo "$INSTALLED" | grep \"^$1\b\")" != "" ]
}

main "$@"
