#!/bin/bash

rr='source ~/.config/dotfiles/scripts/init-rvm'

tmux new-session -d -n "server" "bash -c '$rr && rails server'"
tmux new-window -n "livereload" "bash -c '$rr && bundle exec guard'"
tmux new-window -n "spork" "bash -c '$rr && spork'"
tmux new-window -n "rails console" "bash -c '$rr && rails c'"
tmux attach
