#!/bin/bash

tmux new-session -d -n "server" "bash -c 'rails server'"
tmux new-window -n "livereload" "bash -c 'bundle exec guard'"
tmux new-window -n "spork" "bash -c 'spork'"
tmux new-window -n "rails console" "bash -c 'rails c'"
tmux attach
