#!/bin/bash
#
# Usage:
#
#  release (major|minor|patch)

source $DOTF/framework

main() {
  if [ $# -eq 0 ]; then
    usage "$0"
    exit 1
  fi

  header 'Generate changelog (also copied to clipboard)'
  git changelog $(git lasttag)
  git changelog $(git lasttag) | pbcopy

  header 'Create version tag'
  gever create "$1"

  if has-develop-branch; then
    header 'Pushing develop branch'
    git push noreview develop

    header 'Merge Develop into Master'
    git mtd
  fi

  header 'Pushing master branch (and tags)'
  git push noreview master --tags
}

has-develop-branch() {
  git all-branches | grep '^develop$' > /dev/null 2>&1
}

main "$@"
