#!/usr/bin/env bash
#
# rm-empty - Removes empty directories
#
# Usage:
#   rm-empty <path>...

source $DOTF/framework

main() {
  if [ $# -eq 0 ]; then
    usage "$0"
  else
    run "$@"
  fi
}

run() {
  empty-directories "$1"
}

empty-directories() {
  find "$1" -type d | while read dir; do
    if is-empty "$dir"; then
      bullet "Deleting ${dir}... "
      rmdir "$dir" && success 'done.' || error 'failed!'
    fi
  done
}

is-empty() {
  rm -f "$1/.DS_Store"
  [ -z "$(ls -A "$1")" ]
}

main "$@"
