#!/bin/bash
#
# s3upload
#
# Usage:
#
#   s3upload <bucket_path> <local_file>...

source "$DOTF/framework"

MAX_AGE=${MAX_AGE:-600}

main() {
  if [ $# -lt 2 ]; then
    usage "$0"
  else
    upload "$@"
  fi
}

upload() {
  BUCKET_PATH="$1"

  shift

  while [ $# -gt 0 ]; do
    upload_single "$1"
    shift
  done
}

upload_single() {
  local local_file="$1"
  local name=$(basename $local_file)

  echo
  echo -e "${BLUE}Uploading ${local_file}...$RESET"
  s3cmd put "$local_file" "s3://$BUCKET_PATH/$name"

  bullet "Setting Public ACL on ${local_file}..."
  s3cmd setacl "s3://$BUCKET_PATH/$name" --acl-public --verbose

  bullet "Setting max-age to $MAX_AGE Public ACL on ${local_file}..."
  s3cmd modify "s3://$BUCKET_PATH/$name" --add-header=Cache-Control:max-age=$MAX_AGE
}

main "$@"
