#!/bin/bash
#
# s3upload
#
# Usage:
#
#   s3upload <bucket> <bucket_path> <local_file>...

main() {
  if [ $# -lt 3 ]; then
    usage "$0"
  else
    upload "$@"
  fi
}

upload() {
  BUCKET="$1"
  BUCKET_PATH="$2"

  shift
  shift

  while [ $# -gt 0 ]; do
    upload_single "$1"
    shift
  done
}

upload_single() {
  local local_file="$1"
  local name=$(basename $local_file)

  echo "Uploading ${local_file}..."
  s3cmd put "$local_file" "s3://$BUCKET/$BUCKET_PATH/$name"

  echo "Setting Public ACL on ${local_file}..."
  s3cmd setacl "s3://$BUCKET/$BUCKET_PATH/$name" --acl-public --verbose
}

main "$@"
