#!/usr/bin/env ruby

RESET="\033[0m"

colors = {
  black: 30,
  red: 31,
  green: 32,
  yellow: 33,
  blue: 34,
  purple: 35,
  cyan: 36,
  white: 37
}

def show_color(name, value, bold = false)
  mode = bold ? 1 : 0
  name = "bold #{name}" if bold
  code = "\033[#{mode};#{value}m"
  display = "\\033[#{mode};#{value}m"

  puts "#{code}#{display}\t#{name}#{RESET}"
end

colors.each do |name, value|
  show_color(name, value)
  show_color(name, value, true)
end

