#!/bin/bash

eval "$(rbenv init --no-rehash -)"

what=$*

use_zeus='no'

if [ -e "zeus.json" ]; then
  use_zeus='yes'
fi

if [ "$what" == "" ]; then
  #what=`find spec -name '*_spec.rb' | xargs`
  what='spec'
else
  file="`echo $what | sed 's/:.*$//'`"
  fast_spec_helper=`grep fast_spec_helper $file`
  echo "what = [$fast_spec_helper]"
  if [ "$fast_spec_helper" != "" ]; then
    use_zeus='no'
  fi
fi

if [ -e ".zeus.sock" ]; then
  echo "Running 'zeus rspec $what'"
  zeus rspec $what
elif [ -x "bin/rspec" ]; then
  echo "Running 'bin/rspec $what'"
  bin/rspec $what
else
  echo "Running 'rspec $what'"
  rspec $what
fi
