#!/bin/bash

what=$*

if [ "$what" == "" ]; then
  what=`find spec -name '*_spec.rb' | xargs`
fi

if [ -e "zeus.json" ]; then
  echo "Running 'zeus rspec $what'"
  zeus rspec $what
else
  echo "Running 'rspec $what'"
  rspec $what
fi
