#!/usr/bin/env bash

title="${*:-$(pretty-hostname)}"

termcode="\033]0;${title}\007"
echo -ne "$termcode"

if [ -n "${TMUX:-}" ]; then
  tty=$(tmux list-panes -F "#{pane_active} #{pane_tty}" | awk '$1=="1" { print $2 }')
  echo -ne "\033Ptmux;\033$termcode\033\\" > "$tty"
fi
