#!/usr/bin/env bash

termcode="\033]0;$*\007"
printf "$termcode"

if [ -n "${TMUX:-}" ]; then
  tty=$(tmux list-panes -F "#{pane_active} #{pane_tty}" | awk '$1=="1" { print $2 }')
  printf "\033Ptmux;\033$termcode\033\\" > $tty
fi
