#!/bin/bash

BLUE="\033[34m"
RESET="\033[0m"

if [ $# -gt 0 ]; then
  echo -e "$BLUE============================="
  echo 'Running:'
  echo "  $@"
  echo -e "=============================$RESET"
  echo

  "$@"

  echo
  echo -e "$BLUE============================="
  echo 'Done running:'
  echo "  $@"
  echo -e "=============================$RESET"
fi

$SHELL
