#!/usr/bin/env bash

source $DOTF/framework

PIP_PKGS="pip neovim neovim-remote httpie ranger"
NPM_PKGS="npm yarn json diff-so-fancy"

header 'Updating NodeJS'
n 11


header 'Updating pip packages'
for pkg in $PIP_PKGS; do
  pip3 install $pkg --upgrade --user
done

header 'Updating npm packages'
for pkg in $NPM_PKGS; do
  npm install -g $pkg
done

header 'Neovim: PlugUpdate'
(cd ~/.local/share/nvim-plugins/coc.nvim && git reset --hard origin/master)
nvim +PlugUpdate +qall

header 'Neovim: CocUpdateSync'
nvim +CocUpdateSync +qall
