#!/usr/bin/env bash

source "$DOTF/framework"

function main() {
  update-node
  dotf-github update
  dotf-pkgs upgrade
  update-neovim-stuff
}

function update-node() {
  if is-n-providing-node; then
    header 'Updating N'
    (cd "$N_PREFIX" && git pull)

    header 'Updating NodeJS'
    n --preserve lts # Preserve npm (don't downgrade to lts version)
  fi
}

function update-neovim-stuff() {
  header 'Neovim: Upgrade'
  dotf-github u nvim
  nvim-packer-sync
}

main "$@"
