#!/bin/bash

source $DOTF/framework

header "Updating scripts"

update_script() {
  bullet "Updating ${2}... "
  wget "$1" --output-document "$2"
  chmod +x "$2"
}

update_script "https://github.com/garybernhardt/selecta/raw/master/selecta" selecta


