#!/usr/bin/env ruby
# Watermarker
#
# Usage:
#
#   watermark <text> <color> <image>...

require 'fileutils'

HEIGHT_PERCENTAGE = 1.3
PADDING_PERCENTAGE = 0.5
STROKE_PERCENTAGE = 0.05

def main
  if ARGV.length < 3
    system "usage '#{__FILE__}'"
  end

  text = ARGV.shift
  color = ARGV.shift

  ARGV.each do |filename|
    add_watermark(text, color, filename)
  end
end

def add_watermark(text, color, filename)
  puts "Adding watermark '#{text}' (#{color}) to '#{filename}'..."

  dir = File.join(File.dirname(filename), 'watermarked')
  FileUtils.mkdir_p dir

  output = File.join(dir, File.basename(filename))

  img = Image.new(filename)

  font_size = img.height * HEIGHT_PERCENTAGE / 100
  padding = img.height * PADDING_PERCENTAGE / 100
  stroke_width = img.height * STROKE_PERCENTAGE / 100

  puts "Using font size '#{font_size}'"

  cmd = <<-EOF
    convert "#{filename}" -pointsize "#{font_size}" \
      -stroke black \
      -strokewidth #{stroke_width} \
      -weight bold \
      -draw "gravity southeast \
            fill #{color} text #{padding},#{padding} '#{text}'" \
      "#{output}"
  EOF

  puts "Running:"
  puts cmd
  system(cmd)
end

class Image
  def initialize(filename)
    @filename = filename
  end

  def identify
    @identify ||= `identify "#{@filename}"`.split(' ')
  end

  def size
    @size ||= identify[2].split('x').map(&:to_i)
  end

  def height
    size[0]
  end
end

main
