#!/usr/bin/env bash

evoluent_id="$(xinput | grep Evoluent  | sed 's/^.*id=//' | awk '{ print $1 }')"

echo "ID: $evoluent_id"
if [ -n "$evoluent_id" ]; then
  xinput set-button-map $evoluent_id 1 3 2 4 5 6 7 8 9 10
fi
