#!/usr/bin/env bash

yarn="yarn"

if [ -e docker-compose.yml ]; then
  if grep "node:" docker-compose.yml > /dev/null 2>&1; then
    echo "(running yarn via docker-compose)"
    yarn="docker-compose run node yarn"
  fi
fi

$yarn "$@"
