#!/usr/bin/env bash
#
# Usage:
#
#   yank-osc52 {file}    - yank file to clipboard
#   yank-osc52 -         - yank stdin to clipboard

# based on
# https://www.freecodecamp.org/news/tmux-in-practice-integration-with-system-clipboard-bcd72c62ff7b/

buflen=$(printf %s "$buf" | wc -c)

function main() {
  BUF=$(cat "$@")
  validate-input-length
  print-osc52-codes > $(identify-target-tty)
  echo "$BUF"
}

function validate-input-length() {
  maxlen=74994
  if [[ $buflen -gt $maxlen ]]; then
    printf "input is %d bytes too long" "$(( buflen - maxlen ))" >&2
    exit 1
  fi
}

function print-osc52-codes() {
  printf "\033]52;c;$( printf %s "$BUF" | base64 | tr -d '\r\n' )\a"
}

function identify-target-tty() {
  if [ -n "$SSH_TTY" ]; then
    echo "$SSH_TTY"
  elif [ -n "$TMUX_PANE" ]; then
    tmux list-panes -F "#{pane_active} #{pane_tty}" | awk '$1=="1" { print $2 }'
  else
    echo '&1'
  fi
}

main "$@"
