#!/usr/bin/env bash

set -euo pipefail

dfl symlink config.toml ~/.config/herdr/config.toml

herdr integration install claude
herdr integration install codex

herdr plugin link ~/.local/share/nvim/site/pack/core/opt/smart-splits.nvim
