#!/usr/bin/env bash

set -euo pipefail

dfl symlink config.toml ~/.config/herdr/config.toml

herdr integration install claude
herdr integration install codex

herdr plugin install lmilojevicc/herdr-splits.nvim --ref v0.5.1 --yes
