#!/usr/bin/env bash

set -euo pipefail

tvroot="$DOTF/core/television"

dfl symlink "$tvroot/" ~/.config/television

# Update shell integrations
dfl mkdir "$tvroot/shell"
tv init fish >"$tvroot/shell/integration.fish"
