#!/usr/bin/env bash

dfl symlink "$DOTF/extra/ssh/rc" ~/.ssh/rc
dfl symlink "$DOTF/extra/ssh/config" ~/.ssh/config

if [ ! -e ~/.ssh/machine.config ]; then
  echo "# vim: syntax=sshconfig" >~/.ssh/machine.config
fi
