#!/usr/bin/env bash

set -euo pipefail

dfl pkg npm install opencode-ai
dfl symlink "$DOTF/extra/opencode/opencode.jsonc" "$HOME/.config/opencode/opencode.jsonc"
dfl symlink "$DOTF/extra/opencode/tui.jsonc" "$HOME/.config/opencode/tui.jsonc"
