#!/usr/bin/env bash

VERSION=1911.21

fonts_dir=$HOME/.fonts

rm -f "$fonts_dir/Cascadia.ttf"
curl -L https://github.com/microsoft/cascadia-code/releases/download/v${VERSION}/Cascadia.ttf \
     -o "$fonts_dir/Cascadia.ttf"

fc-cache -v -f "$fonts_dir"
