#!/usr/bin/env bash

source `dirname $0`/../../framework

header 'Installing fonts'

if is_mac; then
  font_dir="$HOME/Library/Fonts"
else
  font_dir="$HOME/.fonts"
  mkdir -p $font_dir
fi

find "$DOTF/plugins/fonts" -name '*.[o,t]tf' -type f | \
  while read file; do
    copy_to_dir "$file" "$font_dir"
  done

if [ ! -e "$font_dir/Cascadia.ttf" ]; then
  curl -L https://github.com/microsoft/cascadia-code/releases/download/v1909.16/Cascadia.ttf > $font_dir/Cascadia.ttf
fi

# For linux
if is_linux; then
  bullet "Updating font cache"
  fc-cache -v -f $font_dir
fi
