#!/usr/bin/env bash

set -euo pipefail

if ! dfl has-command ghostty; then
  brew install --cask ghostty
fi

dfl symlink "$DOTF/extra/ghostty" ~/.config/ghostty
dfl symlink "$DOTF/extra/ghostty" "$HOME/Library/Application Support/com.mitchellh.ghostty"
