#!/usr/bin/env bash

set -euo pipefail

source "$DOTF/framework.sh"

if dotf-command-missing ghostty; then
  brew install --cask ghostty
fi

dotf-symlink "$DOTF/extra/ghostty" ~/.config/ghostty
dotf-symlink "$DOTF/extra/ghostty" "$HOME/Library/Application Support/com.mitchellh.ghostty"
