#!/usr/bin/env bash

source $DOTF/framework
source $DOTF/scripts/build-helper

prepare_build oni master "$*"

git clone --recursive --depth 1 \
  --branch $VERSION \
  https://github.com/onivim/oni.git

cd oni

yarn install
yarn run build
yarn link
