#!/usr/bin/env bash

source $DOTF/framework

# symlink "$DOTF/plugins/oni" ~/.config/oni
mkdir -p ~/.config/oni
symlink "$DOTF/plugins/oni/config.tsx" ~/.config/oni/config.tsx

# npm-fast-install typescript
# npm-fast-install ts-server
