#!/bin/bash

source `dirname $0`/../framework

install_zsh() {
  if is_mac; then
    my_shell=$(echo $SHELL | rev | cut -d/ -f1 | rev)
    if [ "$my_shell" != "zsh" ]; then
      zsh_bin="$(which zsh)"
      bullet "Changing shell to ${zsh_bin}... "
      chsh -s "$zsh_bin"
    fi
  else
    if is_arch; then
      pacman_install zsh
    else
      apt_install zsh
    fi
    
    bullet "Changing user's shell to $THE_ZSH... "
    if [[ "$SHELL" =~ /zsh ]]; then
      info 'already set'
    else
      THE_ZSH="$(which zsh)"
      sudo usermod -s $THE_ZSH $USER
    fi
  fi
}

install_symlinks() {
  symlink "$DOTF/zsh" ~/.zsh 
  symlink "$DOTF/zsh/zshrc" ~/.zshrc
  symlink "$DOTF/zsh/zshenv" ~/.zshenv
}

install_requirements() {
  if is_mac; then
    install_gnu_utils
    brew_install rbenv fasd
  elif is_arch; then
    yaourt_install rbenv fasd
  fi
}

install_gnu_utils() {
  brew_install coreutils
  brew_install findutils --with-default-names
  brew_install fasd
  brew_install gnu-sed

  brew_tap homebrew/dupes
  brew_install grep --with-default-names
}

install_fzf() {
  bullet 'Installing FZF... '
  if [ -e ~/.fzf ]; then
    info 'already installed.'
  else
    git_clone https://github.com/junegunn/fzf.git ~/.fzf --depth 1
    ~/.fzf/install
  fi
}

reset_completion_cache() {
  bullet 'Resetting completion cache...'
  rm -rf ~/.zcompcache
  rm -rf ~/.local/share/zcompcache
  rm -f ~/.zcompdump
  zsh -c 'autoload -U compinit && compinit'
}

header "Zsh"

if [ "$1" == "symlinks" ]; then
  install_symlinks
else
  install_requirements
  install_zsh
  install_symlinks
  install_fzf
  reset_completion_cache

  # fix premissions issue
  chmod -R g-w $DOTF/zsh/vendor/zsh-completions
fi
