#!/usr/bin/env bash

source `dirname $0`/../framework

function main() {
  install_requirements
  install_zsh
  install_symlinks
  install_fzf
  reset_completion_cache

  # fix premissions issue
  chmod -R g-w $DOTF/zsh/vendor/zsh-completions
}

function install_zsh() {
  if is_mac; then
    my_shell=$(echo $SHELL | rev | cut -d/ -f1 | rev)
    if [ "$my_shell" != "zsh" ]; then
      zsh_bin="$(which zsh)"
      bullet "Changing shell to ${zsh_bin}... "
      chsh -s "$zsh_bin"
    fi
  else
    install_package zsh

    zsh_bin="$(which zsh)"
    bullet "Changing user's shell to $zsh_bin... "
    if [[ "$SHELL" =~ /zsh ]]; then
      info 'already set'
    else
      chsh -s $zsh_bin
    fi
  fi
}

function install_symlinks() {
  symlink "$DOTF/zsh" ~/.zsh
  symlink "$DOTF/zsh/zshrc" ~/.zshrc
  symlink "$DOTF/zsh/zshenv" ~/.zshenv
}

function install_requirements() {
  if is_arch; then
    pacman_install fasd
  elif is_debian; then
    apt-fast-install fasd
  fi

  if is_mac; then
    install_gnu_utils
  fi
}

function install_gnu_utils() {
  brew_install coreutils
  brew_install findutils
  brew_install fasd
  brew_install gnu-sed
  brew_install grep
}

function install_fzf() {
  bullet 'Installing FZF... '
  if [ -e ~/.fzf ]; then
    info 'already installed.'
  else
    git_clone https://github.com/junegunn/fzf.git ~/.fzf --depth 1
    ~/.fzf/install --completion --key-bindings --no-update-rc
  fi
}

reset_completion_cache() {
  bullet 'Resetting completion cache...'
  rm -rf ~/.zcompcache
  rm -rf ~/.local/share/zcompcache
  rm -f ~/.zcompdump
  zsh -c 'autoload -U compinit && compinit'
}

main "$@"
