typeset -F SECONDS=0
export START_TIME=$SECONDS

if [ -e ~/.profiling ]; then
  source $DOTF/zsh/profiling.zsh
fi

source $DOTF/zsh/core.sh
source_if_exists ~/.dotlocal/zsh/before.zsh
source $DOTF/zsh/zsh.zsh
source $DOTF/zsh/settings.sh
source $DOTF/zsh/widgets.zsh
source $DOTF/zsh/aliases.sh
source $DOTF/zsh/completion.zsh
source $DOTF/zsh/keybindings.zsh
source $DOTF/zsh/fzf-git.sh	
source $DOTF/zsh/vendor/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source $DOTF/zsh/prompt.zsh
if [ -e ~/.fzf.zsh ]; then
  source ~/.fzf.zsh
fi
source_if_exists ~/.dotlocal/zsh/after.zsh

# required so ~/.zshenv will be loaded by sub-processes
unset ZSHENV_LOADED

duration=$((($SECONDS - $START_TIME) * 1000))
echo "\033[1;30m($(printf '%.2f' $duration)ms)\033[0m"
