#!/usr/bin/env bash

set -euo pipefail

source "$DOTF/framework"

CONFIG_DIR="$HOME/.config/pulse"
mkdir -p "$CONFIG_DIR"

dotf-symlink "$DOTF/extra/pulseaudio/default.pa" "$CONFIG_DIR/default.pa"

echo "Killing pulseaudio"
pulseaudio -k || true

echo "Starting pulseaudio"
systemctl --user start pulseaudio
