#!/usr/bin/env bash

set -euo pipefail

mkdir -p ~/.config/zed
dfl symlink "$DOTF/extra/zed/settings.json" ~/.config/zed/settings.json
dfl symlink "$DOTF/extra/zed/keymap.json" ~/.config/zed/keymap.json
