#!/usr/bin/env bash
#
# Cross-platform "opener" (xdg-open/open/start)
# Usage:
#
#   o <file-or-directory>
#

source $DOTF/core/zsh/core.sh

if dotf-is-wsl; then
  explorer.exe "$@"
elif dotf-is-linux; then
  xdg-open "$@"
elif dotf-is-mac; then
  open "$@"
else
  echo 'ERROR: no idea how to open this file (not linux, mac or wsl)'
  exit 1
fi
