#!/usr/bin/env bash
#
# Usage:
#
#   dotf-host-info <pretty-name|tmux-color>
#

set -euo pipefail

function main() {
  cmd="${1:-}"
  shift

  case "$cmd" in
    "pretty-name")
      get-host-field 2
      ;;
    "tmux-color")
      get-host-field 3
      ;;
    *)
      usage "$0"
      exit 1
      ;;
  esac
}

function get-host-field() {
  local index="$1"

  local file=""
  local files=("$DOTL/pretty-hostnames" "$DOTL/hosts-info" "$DOTP/hosts-info")
  for file in "${files[@]}"; do
    if [ -e "$file" ]; then
      break
    fi
  done

  if [ ! -e "$file" ]; then
    echo >&2 "Error: hosts info file not found"
    echo "ERROR"
    return
  fi

  hostname="$(hostname)"
  grep --no-messages "^${hostname}:" "$file" \
    | cut -d: "-f$index" \
    || echo "$hostname"
}

main "$@"
