#!/usr/bin/env bash

set -euo pipefail

source "$(dirname "$0")/../../framework"

benchmark-start

main() {
  cd "$DOTF"

  dotf-header h1 "Setting up dotfiles..."

  if dotf-is-mac; then
    dotf-pkgs install brew
  else
    dotf-pkgs install apt
  fi

  dotf-header h2 "[dotf-setup] Updating git submodules..."
  git submodule update --init --recursive

  dotf-bullet "Installing pip packages..."
  dotf-pkgs install pip

  dotf-header h2 "[dotf-setup] Installing Github packages..."
  dotf-github install

  dotf-component nodejs
  dotf-pkgs install npm
  dotf-component git zsh nvim ripgrep tig bash tmux vifm python

  dotf-header h2 "[dotf-setup] Running deno cache..."
  (cd extra/scripts/deno && deno cache ./**/*.ts)

  #if dotf-is-mac; then
  #dotf-component osx-tuning iterm
  #fi

  show-done
}

show-done() {
  echo -e "$GREEN=========================="
  echo "Done ($(benchmark-stop))"
  echo -e "==========================$RESET"
}

main "$@"
