#!/usr/bin/env bash

set -euo pipefail

source "$(dirname "$0")/../../framework.sh"

benchmark-start

main() {
  cd "$DOTF"

  dotf-header h1 "Setting up dotfiles..."

  dotf-pkgs install brew
  if ! dotf-is-linux; then
    dotf-pkgs install apt
  fi

  if dotf-is-linux; then
    if [ -e /usr/lib/python3.11/EXTERNALLY-MANAGED ]; then
      sudo mv /usr/lib/python3.11/EXTERNALLY-MANAGED{,.disabled}
    fi
  fi

  dotf-header h2 "[dotf-setup] Setting up repositories..."
  dotf-repos setup

  dotf-bullet "Installing pip packages..."
  dotf-pkgs install pip

  # dotf-header h2 "[dotf-setup] Installing Github packages..."
  # github-pkgs install

  dotf-component fish nvim fzf git ripgrep tig bash tmux vifm nodejs python 
  dotf-pkgs install npm

  dotf-header h2 "[dotf-setup] Running deno cache..."
  (cd extra/scripts/deno && deno cache ./**/*.ts)

  #if dotf-is-mac; then
  #dotf-component osx-tuning iterm
  #fi

  show-done
}

show-done() {
  echo -e "$GREEN=========================="
  echo "Done ($(benchmark-stop))"
  echo -e "==========================$RESET"
}

main "$@"
