#!/usr/bin/env bash

source "$DOTF/framework.sh"

set -euo pipefail

function main() {
  dotf-summary start -i

  dotf-header h1 "Upgrading environment..."
  cd "$DOTF"

  dotf-repos pull
  dotf-summary run 'Update packages' dotf-pkgs upgrade
  upgrade-neovim-stuff

  # Clear cached direnv fish setup (regenerated when missing on new shells)
  rm -f ~/.cache/dotfiles/direnv.fish

  dotf-summary stop
}

function upgrade-neovim-stuff() {
  dotf-header h2 'Neovim: Upgrade'
  dotf-summary run 'Neovim: brew update' brew upgrade neovim
  dotf-summary run 'Neovim: Lazy update' nvim --headless "+Lazy! update" +qa
  dotf-summary run 'Neovim: Reinstall treesitter' nvim --headless "+lua require('elentok.treesitter-parsers')" +qa
}

main "$@"
