#!/usr/bin/env bash
#
# Cross-platform "opener" (xdg-open/open/start)
# Usage:
#
#   o <file-or-directory>
#

source "$DOTF/core/zsh/core.sh"

cmd="${1:-}"

if [ "$cmd" == "-" ]; then
  cmd="$(cat -)"
fi

if dotf-is-wsl; then
  explorer.exe "$cmd"
elif dotf-is-linux; then
  xdg-open "$cmd"
elif dotf-is-mac; then
  open "$cmd"
else
  echo 'ERROR: no idea how to open this file (not linux, mac or wsl)'
  exit 1
fi
