#!/usr/bin/env bash
#
# Usage:
#
#   dotf-host-info <pretty-name|tmux-color>
#

set -euo pipefail

function main() {
  cmd="${1:-}"
  shift

  case "$cmd" in
    "pretty-name")
      if ! get-host-field 2; then
        hostname
      fi
      ;;
    "tmux-color")
      if ! get-host-field 3; then
        echo "blue"
      fi
      ;;
    *)
      usage "$0"
      exit 1
      ;;
  esac
}

function get-host-field() {
  local index="$1"

  local file=""
  for hostsfile in "$DOTP"/*/hosts-info; do
    file="$hostsfile"
    break
  done

  if [ ! -e "$file" ]; then
    echo >&2 "Error: hosts info file not found"
    return 1
  fi

  hostname="$(hostname)"
  grep --no-messages "^${hostname}:" "$file" \
    | cut -d: "-f$index" \
    || echo "$hostname"
}

main "$@"
