#!/usr/bin/env bash

echo "========================================"
echo "Running: [$*]"
echo "========================================"
echo

"$@"
exitcode="$?"

echo
echo "========================================"
if [ "$exitcode" == "0" ]; then
  dfl step success "Exited with exitcode $exitcode"
else
  dfl step error "Exited with exitcode $exitcode"
fi
echo "========================================"
echo
echo "Press 'q' to quit"

while true; do
  read -r -n 1 answer
  if [ "$answer" == "q" ]; then
    break
  fi
done
