#!/usr/bin/env bash

set -euo pipefail

WIDTH='90%'
HEIGHT='90%'
SESSION_NAME="Floating"

function main() {
  # tmux display-message -p "#{session_name}" >>~/tmux.log
  if is-floating; then
    # echo "is floating for some reason" >>~/tmux.log
    tmux detach-client
    return
  fi

  if ! tmux-has-session; then
    tmux new-session -d -s "$SESSION_NAME"
  fi

  # -E closes the popup when the shell command exits
  tmux popup -E -b rounded -h "$HEIGHT" -w "$WIDTH" "tmux attach-session -t ${SESSION_NAME}" || true
}

function is-floating() {
  test "$(tmux display-message -p '#{session_name}')" == "$SESSION_NAME"
}

function tmux-has-session() {
  tmux has-session -t "$SESSION_NAME" 2>/dev/null
}

main "$@"
