#!/usr/bin/env bash

source "$DOTF/framework.sh"

set -euo pipefail

function main() {
  dotf-summary start -i

  dotf-header h1 "Upgrading environment..."
  cd "$DOTF"

  dotf-repos upgrade
  dotf-summary run 'Update github packages' github-pkgs update
  dotf-summary run 'Update packages' dotf-pkgs upgrade
  dotf-summary run 'Update fisher' fish -c "fisher update"
  upgrade-neovim-stuff

  # Clear cached direnv fish setup (regenerated when missing on new shells)
  rm -f ~/.cache/dotfiles/direnv.fish

  dotf-summary stop
}

function upgrade-neovim-stuff() {
  dotf-header h2 'Neovim: Upgrade'
  if dotf-is-mac; then
    dotf-summary run 'Neovim: brew update' brew upgrade neovim
    # Non-mac uses github-pkgs to update
  fi
  dotf-summary run 'Neovim: Lazy sync' dotf-nvim-lazy sync
}

main "$@"
