#!/usr/bin/env bash
#
# Elentok's dotfiles
#
# Usage:
#
#   dotf install                            - installs all components
#   dotf install [component] [component]... - install specific components
#   dotf update                             - pulls from git and reruns install
#

source "$(dirname "$0")/../../framework"

main() {
  cmd="${1:-}"
  shift || true
  case "$cmd" in
    install | i) install "$@" ;;
    update | u) dotf-update ;;
    stats | s) dotf-stats ;;
    *) usage "$0" ;;
  esac
}

install() {
  if [ $# -eq 0 ]; then
    dotf-install
  else
    dotf-component "$@"
  fi
}

main "$@"
