#!/usr/bin/env bash
#
# Usage:
#
#   dotf-brew <package>...
#

set -euo pipefail
source "$DOTF/framework.sh"

main() {
  if [ $# -eq 0 ]; then
    usage "$0"
    exit 1
  fi

  dotf-bullet "Installing brew packages $*... "
  missing=$(find-missing-packages "$@")

  if [ -z "$missing" ]; then
    dotf-info " already installed."
  else
    echo
    dotf-bullet "Installing missing packages: $missing..."
    echo

    # shellcheck disable=SC2086
    brew install --force $missing
  fi
}

function find-missing-packages() {
  already_installed="$(mktemp)"
  find-already-installed "$@" > "$already_installed"

  diff="$(echo "$*" | tr ' ' '\n' | sort | (diff "$already_installed" - || true))"

  if [ -n "$diff" ]; then
    echo "$diff" | grep '^>' | sed 's/^> //' | xargs
  fi
}

function find-already-installed() {
  regexp="^($(echo "$@" | sed -E 's/\s+/|/g'))$"
  all-installed-packages | grep -E "$regexp" | sort
}

function all-installed-packages() {
  brew list -1 --full-name
}

main "$@"
