#!/usr/bin/env bash

source "$DOTF/framework.sh"

set -euo pipefail

function main() {
  dotf-summary start -i

  dotf-header h1 "Upgrading environment..."
  cd "$DOTF"

  dotf-repos upgrade
  upgrade-node
  dotf-summary run 'Update github packages' github-pkgs update
  dotf-summary run 'Update packages' dotf-pkgs upgrade
  dotf-summary run 'Update fisher' fish -c "fisher update"
  upgrade-neovim-stuff

  dotf-summary stop
}

function upgrade-node() {
  if is-n-providing-node; then
    dotf-header h2 'Updating N...'
    (cd "$N_PREFIX" && dotf-summary run 'n: pull' git pull)

    dotf-header h2 'Updating NodeJS...'
    dotf-summary run 'n: update' n --preserve "$(dotf-node-version)" # Preserve npm (don't downgrade to lts version)
  fi
}

function upgrade-neovim-stuff() {
  dotf-header h2 'Neovim: Upgrade'
  if dotf-is-mac; then
    dotf-summary run 'Neovim: brew update' brew upgrade neovim
    # Non-mac uses github-pkgs to update
  fi
  dotf-summary run 'Neovim: Lazy sync' dotf-nvim-lazy sync
}

main "$@"
