#!/usr/bin/env bash

source "$DOTF/core/scripts/lib/ui.sh"

dotf-color blue
echo "========================================"
echo "Running: [$*]"
echo "========================================"
dotf-color reset
echo

"$@"
exitcode="$?"

echo
echo "========================================"
if [ "$exitcode" == "0" ]; then
  dotf-success "Exited with exitcode $exitcode"
else
  dotf-error "Exited with exitcode $exitcode"
fi
echo "========================================"
echo
echo "Press 'q' to quit"

while true; do
  read -r -n 1 answer
  if [ "$answer" == "q" ]; then
    break
  fi
done
