#!/usr/bin/env bash
#
# Usage:
#
#   dotf-clipboard copy|yank
#   dotf-clipboard paste
#

source ~/.dotfiles/core/bash/core.sh

main() {
  cmd="${1:-}"
  shift
  case "$cmd" in
  c | copy | y | yank) copy ;;
  p | paste) paste ;;
  *) usage "$DOTF/core/scripts/dotf-clipboard" ;;
  esac
}

copy() {
  if dotf-is-wsl; then
    clip.exe
  elif [ -n "${TMUX:-}" ]; then
    dotf-yank-osc52 | system-copy
  else
    system-copy
  fi
}

function system-copy() {
  if dotf-has-command pbcopy; then
    pbcopy
  elif [ -n "$DISPLAY" ]; then
    if dotf-has-command xsel; then
      xsel --clipboard --input 2>&1
    elif dotf-has-command xclip; then
      xclip -selection clipboard -in 2>&1
    fi
  fi
}

paste() {
  if dotf-is-wsl; then
    win32yank -o
  elif dotf-has-command pbpaste; then
    pbpaste
  elif dotf-has-command xclip; then
    xclip -selection clipboard -out
  elif dotf-has-command xsel; then
    xsel --clipboard --output
  else
    echo 'Error: missing copy command (pbpaste, xclip or xsel)'
  fi
}

main "$@"
