#!/usr/bin/env bash
#
# Usage:
#
#   dotf-notify <message>
#

set -euo pipefail

source "$DOTF/core/scripts/lib/os.sh"

function main() {
  if [ $# -eq 0 ]; then
    usage "$0"
    exit 1
  fi

  message="$1"
  if dotf-is-mac; then
    terminal-notifier -message "$message"
  else
    zenity --notification --text "$message"
  fi
}

main "$@"
