#!/usr/bin/env bash

source ~/.dotfiles/core/bash/core.sh

TMP_BUFFER="$TMP/nvim-pager-buffer"

function main {
  if [ $# -gt 0 ]; then
    exec nvim --noplugin \
      -u "$DOTF/core/nvim/init-pager.lua" \
      -c 'autocmd VimEnter * normal G' "$@"
  else
    exec nvim --noplugin \
      -u "$DOTF/core/nvim/init-pager.lua" \
      -c "silent write! $TMP_BUFFER | te cat $TMP_BUFFER - " \
      -c 'autocmd VimEnter * normal G'
  fi
}

main "$@"
