#!/usr/bin/env bash

set -euo pipefail

source "$(dirname "$0")/../../framework"

benchmark-start

main() {
  cd "$DOTF"

  dotf-header h1 "Setting up dotfiles..."

  dotf-pkgs install apt

  dotf-header h2 "[dotf-bootstrap] Updating git submodules..."
  git submodule update --init --recursive

  dotf-bullet "Installing pip packages..."
  dotf-pkgs install pip

  dotf-header h2 "[dotf-bootstrap] Installing Github packages..."
  dotf-github install

  dotf-component nodejs
  dotf-pkgs install npm
  dotf-component git zsh nvim ripgrep tig bash tmux vifm

  if dotf-is-mac; then
    dotf-component osx-tuning iterm
  fi

  dotf-header h2 '[dotf-bootstrap] Running npm install...'
  npm install

  show-done
}

show-done() {
  echo -e "$GREEN=========================="
  echo "Done ($(benchmark-stop))"
  echo -e "==========================$RESET"
}

main "$@"
