#!/usr/bin/env bash
#
# Elentok's dotfiles
#
# Usage:
#
#   dotf bootstrap                          - installs all components
#   dotf install [component] [component]... - install specific components
#   dotf update                             - pulls from git and reruns install
#

source "$(dirname "$0")/../../framework"

main() {
  cmd="${1:-}"
  shift || true
  case "$cmd" in
    b | bootstrap) "$DOTF/bootstrap.sh" ;;
    i | install) dotf-component "$@" ;;
    u | update) dotf-update "$@" ;;
    st | stats) dotf-stats "$@" ;;
    setup) dotf-setup "$@" ;;
    *) usage "$0" ;;
  esac
}

main "$@"
