#!/usr/bin/env bash

set -euo pipefail

LOCAL_CONFIG_FILE=~/.config/dotfiles/projects

source "$DOTF/core/scripts/lib/core-helpers.sh"

function main() {
  local cmd="${1:-}"
  shift || true

  if type "dotf-projects-${cmd}" > /dev/null 2>&1; then
    "dotf-projects-${cmd}" "$@"
  else
    usage "$0"
    exit 1
  fi
}

function dotf-projects-list() {
  list-projects "$DOTF/config/projects"

  if [ -e "$LOCAL_CONFIG_FILE" ]; then
    list-projects "$LOCAL_CONFIG_FILE"
  fi

  for file in $(dotf-plugin-list-files config/projects); do
    list-projects "$file"
  done
}

function list-projects() {
  grep -E -v '^(#|\s*$)' "$1" | while read -r line; do
    line="${line/\~/$HOME}"
    compgen -G "$line" || true
  done | sed "s#$HOME#~#"
}

function dotf-projects-pick() {
  dotf-projects-list | fzf-tmux -p | sed "s#~#$HOME#"
}

main "$@"
