#!/usr/bin/env bash
#
# Usage:
#
#   dotf-clipboard copy|yank
#   dotf-clipboard paste
#

source "$DOTF/core/zsh/core.sh"

main() {
  cmd="${1:-}"
  shift
  case "$cmd" in
    c | copy | y | yank) copy ;;
    p | paste) paste ;;
    *) usage "$DOTF/core/scripts/dotf-clipboard" ;;
  esac
}

copy() {
  if is_wsl; then
    clip.exe
  else
    dotf-yank-osc52
    # if has_command pbcopy; then
    #    pbcopy
    # elif [ -n "$DISPLAY" ]; then
    #   if has_command xsel; then
    #      xsel --clipboard --input 2>&1
    #   elif has_command xclip; then
    #      xclip -selection clipboard -in 2>&1
    #   fi
    # fi
  fi
}

paste() {
  if is_wsl; then
    win32yank -o
  elif has_command pbpaste; then
    pbpaste
  elif has_command xclip; then
    xclip -selection clipboard -out
  elif has_command xsel; then
    xsel --clipboard --output
  else
    echo 'Error: missing copy command (pbpaste, xclip or xsel)'
  fi
}

main "$@"
