#!/usr/bin/env bash

source "$DOTF/framework"

main() {
  dotf-bullet "Installing apt packages $*... "
  missing=$(find-missing-packages "$@")

  if [ -z "$missing" ]; then
    dotf-info " already installed."
  else
    echo
    dotf-bullet "Installing missing packages: $missing..."
    echo

    if is_termux; then
      # shellcheck disable=SC2086
      apt install -y $missing
    else
      # shellcheck disable=SC2086
      sudo apt install -y $missing
    fi
  fi
}

function find-missing-packages() {
  already_installed="$(mktemp)"
  find-already-installed "$@" > "$already_installed"

  diff="$(echo "$*" | tr ' ' '\n' | sort | (diff "$already_installed" - || true))"

  if [ -n "$diff" ]; then
    echo "$diff" | grep '^>' | sed 's/^> //' | xargs
  fi
}

function find-already-installed() {
  regexp="^($(echo "$@" | escape-package-name))$"
  all-installed-packages | grep -E "$regexp" | sort
}

function escape-package-name() {
  sed -E 's/\s+/|/g' | sed -E 's/\+/\\+/g'
}

function all-installed-packages() {
  dpkg --get-selections | grep '\<install' | awk '{print $1}' | sed 's/:amd64//'
}

main "$@"
