#!/usr/bin/env bash

set -euo pipefail

source "$DOTF/framework"

dotf-header h1 "Updating dotfiles..."
cd "$DOTF"

dotf-header h2 "Pulling changes... "
old_head=$(git rev-parse HEAD)
git pull
new_head=$(git rev-parse HEAD)

if [ "$old_head" == "$new_head" ]; then
  echo -e "\\nUp to date."
else
  echo -e "\\nPulled the following changes:"
  git log --pretty=%s "${old_head}..${new_head}" | sed 's/^/- /'

  echo -ne "\\nPress any key to run the installer..."
  read -r -n 1

  if is_mac; then
    dotf-bullet 'Updating brew... '
    brew update
  fi

  "$DOTF/bootstrap.sh"

  update-stuff
fi
