#!/usr/bin/env bash

set -euo pipefail

source "$(dirname "$0")/../../framework.sh"

benchmark-start

main() {
  cd "$DOTF"

  dotf-header h1 "Setting up dotfiles..."

  dotf-header h2 "[dotf-setup] Setting up repositories..."
  dotf-repos setup

}

main "$@"
