#!/usr/bin/env bash

source "$DOTF/framework.sh"

dotf-summary start -i

dotf-header h1 'Good morning :-)'

dotf-header h2 'Add ssh key...'
dotf-summary run 'Add SSH Key' ssh-add

for script in $(dotf-plugin-list-files scripts/morning-plugin); do
  "$script"
done

dotf-header h2 'Pulling dotfiles...'
(cd "$DOTF" && dotf-summary run 'Pull dotfiles' git pull)

dotf-summary run 'Setup repositories' dotf-repos setup

"$DOTF/bootstrap.sh"

dotf-autosync-notes

if dotf-has-command dotf-autosync; then
  dotf-summary run "Autosync" dotf-autosync
fi

dotf-summary stop

dotf-header h1 'Have a wonderful day :-)'
