#!/usr/bin/env bash

set -euo pipefail

mkdir -p ~/.config/skhd
dfl symlink "$DOTF/extra/skhd/skhdrc" ~/.config/skhd/skhdrc

if ! dfl has-command skhd; then
  brew install koekeishiya/formulae/skhd
  skhd --start-service
fi
