#!/usr/bin/env bash

source $DOTF/framework

VERSION=0.12.1
ARCH=amd64
PKG_NAME=bat_${VERSION}_${ARCH}
URL=https://github.com/sharkdp/bat/releases/download/v$VERSION/$PKG_NAME.deb

if command_missing bat; then
  install_deb $PKG_NAME $URL
fi
