alias dotfi 'cd $DOTF'
alias dotl 'cd $DOTL'
alias f 'vifm'
alias g 'git'
alias gp 'cd (list-projects | fzf | sed "s#~#$HOME#")'
alias se 'sudoedit'
alias tm 'DISPLAY=${DISPLAY:-:0} tmux -u'
alias ts 'tig status'
alias v 'nvim'
alias vi 'nvim'
