#!/usr/bin/env bash

source $DOTF/framework

function main() {
  if command_missing fish; then
    apt-fast-install fish
    # $DOTF/plugins/fish/build
  fi

  symlink "$DOTF/plugins/fish" "$HOME/.config/fish"
}

main "$@"

