#!/usr/bin/env bash

if dfl os is-mac; then
  font_dir="$HOME/Library/Fonts"
else
  font_dir="$HOME/.fonts"
  mkdir -p "$font_dir"
fi

function copy-fonts() {
  find "$1" -name '*.[o,t]tf' -type f |
    while read -r file; do
      dfl copy "$file" "$font_dir/$(basename "$file")"
    done
}

copy-fonts "$DOTF/extra/fonts"
for dir in "$DOTP"/*/fonts; do
  copy-fonts "$dir"
done

# if [ ! -e "$font_dir/CascadiaMonoPL.ttf" ]; then
#   "$DOTF/extra/fonts/install-cascadia"
# fi

# For linux
if dfl os is-linux; then
  dfl step start "Updating font cache"
  fc-cache -v -f "$font_dir"
fi
