#!/usr/bin/env bash

source "$DOTF/framework"

if dotf-is-mac; then
  font_dir="$HOME/Library/Fonts"
else
  font_dir="$HOME/.fonts"
  mkdir -p "$font_dir"
fi

find "$DOTF/extra/fonts" -name '*.[o,t]tf' -type f \
  | while read file; do
    copy_to_dir "$file" "$font_dir"
  done

# if [ ! -e "$font_dir/CascadiaMonoPL.ttf" ]; then
#   "$DOTF/extra/fonts/install-cascadia"
# fi

# For linux
if dotf-is-linux; then
  dotf-bullet "Updating font cache"
  fc-cache -v -f "$font_dir"
fi
