#!/usr/bin/env bash

VERSION=1911.21

fonts_dir=$HOME/.fonts
filename="CascadiaMonoPL.ttf"

rm -f "${fonts_dir}/${filename}"
curl -L https://github.com/microsoft/cascadia-code/releases/download/v${VERSION}/${filename} \
     -o "${fonts_dir}/${filename}"

fc-cache -v -f "$fonts_dir"
