#!/usr/bin/env bash

source "$DOTF/framework"

if dotf-is-mac; then
  font_dir="$HOME/Library/Fonts"
else
  font_dir="$HOME/.fonts"
  mkdir -p "$font_dir"
fi

function copy-fonts() {
  find "$1" -name '*.[o,t]tf' -type f \
    | while read -r file; do
      copy_to_dir "$file" "$font_dir"
    done
}

copy-fonts "$DOTF/extra/fonts"
if [ -e "$DOTP/fonts" ]; then
  copy-fonts "$DOTP/fonts"
fi

# if [ ! -e "$font_dir/CascadiaMonoPL.ttf" ]; then
#   "$DOTF/extra/fonts/install-cascadia"
# fi

# For linux
if dotf-is-linux; then
  dotf-bullet "Updating font cache"
  fc-cache -v -f "$font_dir"
fi
