#!/usr/bin/env bash

set -euo pipefail

if [ ! -e "$DOTF/core/bat/themes" ]; then
  mkdir "$DOTF/core/bat/themes"
  wget -P "$DOTF/core/bat/themes" https://github.com/catppuccin/bat/raw/main/themes/Catppuccin%20Mocha.tmTheme
fi

dfl symlink "$DOTF/core/bat" "$(bat --config-dir)"
bat cache --build
